#include "hls_design_meta.h"
const Port_Property HLS_Design_Meta::port_props[]={
	Port_Property("v217_address0", 3, hls_out, 0, "ap_memory", "mem_address", 1),
	Port_Property("v217_ce0", 1, hls_out, 0, "ap_memory", "mem_ce", 1),
	Port_Property("v217_d0", 32, hls_out, 0, "ap_memory", "mem_din", 1),
	Port_Property("v217_q0", 32, hls_in, 0, "ap_memory", "mem_dout", 1),
	Port_Property("v217_we0", 1, hls_out, 0, "ap_memory", "mem_we", 1),
	Port_Property("v217_address1", 3, hls_out, 0, "ap_memory", "mem_address", 1),
	Port_Property("v217_ce1", 1, hls_out, 0, "ap_memory", "mem_ce", 1),
	Port_Property("v217_d1", 32, hls_out, 0, "ap_memory", "mem_din", 1),
	Port_Property("v217_q1", 32, hls_in, 0, "ap_memory", "mem_dout", 1),
	Port_Property("v217_we1", 1, hls_out, 0, "ap_memory", "mem_we", 1),
	Port_Property("v218_address0", 11, hls_out, 1, "ap_memory", "mem_address", 1),
	Port_Property("v218_ce0", 1, hls_out, 1, "ap_memory", "mem_ce", 1),
	Port_Property("v218_d0", 32, hls_out, 1, "ap_memory", "mem_din", 1),
	Port_Property("v218_q0", 32, hls_in, 1, "ap_memory", "mem_dout", 1),
	Port_Property("v218_we0", 1, hls_out, 1, "ap_memory", "mem_we", 1),
	Port_Property("v218_address1", 11, hls_out, 1, "ap_memory", "mem_address", 1),
	Port_Property("v218_ce1", 1, hls_out, 1, "ap_memory", "mem_ce", 1),
	Port_Property("v218_d1", 32, hls_out, 1, "ap_memory", "mem_din", 1),
	Port_Property("v218_q1", 32, hls_in, 1, "ap_memory", "mem_dout", 1),
	Port_Property("v218_we1", 1, hls_out, 1, "ap_memory", "mem_we", 1),
	Port_Property("v219_address0", 8, hls_out, 2, "ap_memory", "mem_address", 1),
	Port_Property("v219_ce0", 1, hls_out, 2, "ap_memory", "mem_ce", 1),
	Port_Property("v219_d0", 32, hls_out, 2, "ap_memory", "mem_din", 1),
	Port_Property("v219_q0", 32, hls_in, 2, "ap_memory", "mem_dout", 1),
	Port_Property("v219_we0", 1, hls_out, 2, "ap_memory", "mem_we", 1),
	Port_Property("v219_address1", 8, hls_out, 2, "ap_memory", "mem_address", 1),
	Port_Property("v219_ce1", 1, hls_out, 2, "ap_memory", "mem_ce", 1),
	Port_Property("v219_d1", 32, hls_out, 2, "ap_memory", "mem_din", 1),
	Port_Property("v219_q1", 32, hls_in, 2, "ap_memory", "mem_dout", 1),
	Port_Property("v219_we1", 1, hls_out, 2, "ap_memory", "mem_we", 1),
	Port_Property("ap_clk", 1, hls_in, -1, "", "", 1),
	Port_Property("ap_rst", 1, hls_in, -1, "", "", 1),
	Port_Property("ap_start", 1, hls_in, -1, "", "", 1),
	Port_Property("ap_done", 1, hls_out, -1, "", "", 1),
	Port_Property("ap_ready", 1, hls_out, -1, "", "", 1),
	Port_Property("ap_idle", 1, hls_out, -1, "", "", 1),
};
const char* HLS_Design_Meta::dut_name = "systolic_modulate";
