// ==============================================================
// Generated by Vitis HLS v2023.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module systolic_modulate_dataflow_in_loop_l_ni_1 (
        ap_clk,
        ap_rst,
        indvars_iv26,
        v219_address0,
        v219_ce0,
        v219_d0,
        v219_q0,
        v219_we0,
        v219_address1,
        v219_ce1,
        v219_d1,
        v219_q1,
        v219_we1,
        v218_address0,
        v218_ce0,
        v218_d0,
        v218_q0,
        v218_we0,
        v218_address1,
        v218_ce1,
        v218_d1,
        v218_q1,
        v218_we1,
        v217_address0,
        v217_ce0,
        v217_d0,
        v217_q0,
        v217_we0,
        v217_address1,
        v217_ce1,
        v217_d1,
        v217_q1,
        v217_we1,
        indvars_iv26_ap_vld,
        ap_start,
        ap_done,
        ap_ready,
        ap_idle,
        ap_continue
);


input   ap_clk;
input   ap_rst;
input  [4:0] indvars_iv26;
output  [7:0] v219_address0;
output   v219_ce0;
output  [31:0] v219_d0;
input  [31:0] v219_q0;
output   v219_we0;
output  [7:0] v219_address1;
output   v219_ce1;
output  [31:0] v219_d1;
input  [31:0] v219_q1;
output   v219_we1;
output  [10:0] v218_address0;
output   v218_ce0;
output  [31:0] v218_d0;
input  [31:0] v218_q0;
output   v218_we0;
output  [10:0] v218_address1;
output   v218_ce1;
output  [31:0] v218_d1;
input  [31:0] v218_q1;
output   v218_we1;
output  [2:0] v217_address0;
output   v217_ce0;
output  [31:0] v217_d0;
input  [31:0] v217_q0;
output   v217_we0;
output  [2:0] v217_address1;
output   v217_ce1;
output  [31:0] v217_d1;
input  [31:0] v217_q1;
output   v217_we1;
input   indvars_iv26_ap_vld;
input   ap_start;
output   ap_done;
output   ap_ready;
output   ap_idle;
input   ap_continue;

wire   [31:0] local_B_i_q0;
wire   [31:0] local_B_t_q0;
wire   [31:0] local_B_1_49_i_q0;
wire   [31:0] local_B_1_49_t_q0;
wire   [31:0] local_B_2_50_i_q0;
wire   [31:0] local_B_2_50_t_q0;
wire   [31:0] local_B_3_51_i_q0;
wire   [31:0] local_B_3_51_t_q0;
wire   [31:0] local_B_3_i_q0;
wire   [31:0] local_B_3_t_q0;
wire   [31:0] local_B_2_i_q0;
wire   [31:0] local_B_2_t_q0;
wire   [31:0] local_B_1_i_q0;
wire   [31:0] local_B_1_t_q0;
wire   [31:0] local_B_4_i_q0;
wire   [31:0] local_B_4_t_q0;
wire   [31:0] local_A_0_i_q0;
wire   [31:0] local_A_0_t_q0;
wire    dataflow_in_loop_l_ni_1_Loop_l_load_A_tile_ak_proc_U0_ap_start;
wire    dataflow_in_loop_l_ni_1_Loop_l_load_A_tile_ak_proc_U0_ap_done;
wire    dataflow_in_loop_l_ni_1_Loop_l_load_A_tile_ak_proc_U0_ap_continue;
wire    dataflow_in_loop_l_ni_1_Loop_l_load_A_tile_ak_proc_U0_ap_idle;
wire    dataflow_in_loop_l_ni_1_Loop_l_load_A_tile_ak_proc_U0_ap_ready;
wire   [2:0] dataflow_in_loop_l_ni_1_Loop_l_load_A_tile_ak_proc_U0_v217_address0;
wire    dataflow_in_loop_l_ni_1_Loop_l_load_A_tile_ak_proc_U0_v217_ce0;
wire   [2:0] dataflow_in_loop_l_ni_1_Loop_l_load_A_tile_ak_proc_U0_local_A_0_address0;
wire    dataflow_in_loop_l_ni_1_Loop_l_load_A_tile_ak_proc_U0_local_A_0_ce0;
wire    dataflow_in_loop_l_ni_1_Loop_l_load_A_tile_ak_proc_U0_local_A_0_we0;
wire   [31:0] dataflow_in_loop_l_ni_1_Loop_l_load_A_tile_ak_proc_U0_local_A_0_d0;
wire   [4:0] dataflow_in_loop_l_ni_1_Loop_l_load_A_tile_ak_proc_U0_indvars_iv26_c_din;
wire    dataflow_in_loop_l_ni_1_Loop_l_load_A_tile_ak_proc_U0_indvars_iv26_c_write;
wire    dataflow_in_loop_l_ni_1_Loop_l_load_B_tile_bk_proc_U0_ap_start;
wire    dataflow_in_loop_l_ni_1_Loop_l_load_B_tile_bk_proc_U0_ap_done;
wire    dataflow_in_loop_l_ni_1_Loop_l_load_B_tile_bk_proc_U0_ap_continue;
wire    dataflow_in_loop_l_ni_1_Loop_l_load_B_tile_bk_proc_U0_ap_idle;
wire    dataflow_in_loop_l_ni_1_Loop_l_load_B_tile_bk_proc_U0_ap_ready;
wire   [2:0] dataflow_in_loop_l_ni_1_Loop_l_load_B_tile_bk_proc_U0_local_B_address0;
wire    dataflow_in_loop_l_ni_1_Loop_l_load_B_tile_bk_proc_U0_local_B_ce0;
wire    dataflow_in_loop_l_ni_1_Loop_l_load_B_tile_bk_proc_U0_local_B_we0;
wire   [31:0] dataflow_in_loop_l_ni_1_Loop_l_load_B_tile_bk_proc_U0_local_B_d0;
wire   [2:0] dataflow_in_loop_l_ni_1_Loop_l_load_B_tile_bk_proc_U0_local_B_1_address0;
wire    dataflow_in_loop_l_ni_1_Loop_l_load_B_tile_bk_proc_U0_local_B_1_ce0;
wire    dataflow_in_loop_l_ni_1_Loop_l_load_B_tile_bk_proc_U0_local_B_1_we0;
wire   [31:0] dataflow_in_loop_l_ni_1_Loop_l_load_B_tile_bk_proc_U0_local_B_1_d0;
wire   [2:0] dataflow_in_loop_l_ni_1_Loop_l_load_B_tile_bk_proc_U0_local_B_2_address0;
wire    dataflow_in_loop_l_ni_1_Loop_l_load_B_tile_bk_proc_U0_local_B_2_ce0;
wire    dataflow_in_loop_l_ni_1_Loop_l_load_B_tile_bk_proc_U0_local_B_2_we0;
wire   [31:0] dataflow_in_loop_l_ni_1_Loop_l_load_B_tile_bk_proc_U0_local_B_2_d0;
wire   [2:0] dataflow_in_loop_l_ni_1_Loop_l_load_B_tile_bk_proc_U0_local_B_3_address0;
wire    dataflow_in_loop_l_ni_1_Loop_l_load_B_tile_bk_proc_U0_local_B_3_ce0;
wire    dataflow_in_loop_l_ni_1_Loop_l_load_B_tile_bk_proc_U0_local_B_3_we0;
wire   [31:0] dataflow_in_loop_l_ni_1_Loop_l_load_B_tile_bk_proc_U0_local_B_3_d0;
wire   [2:0] dataflow_in_loop_l_ni_1_Loop_l_load_B_tile_bk_proc_U0_local_B_3_19_address0;
wire    dataflow_in_loop_l_ni_1_Loop_l_load_B_tile_bk_proc_U0_local_B_3_19_ce0;
wire    dataflow_in_loop_l_ni_1_Loop_l_load_B_tile_bk_proc_U0_local_B_3_19_we0;
wire   [31:0] dataflow_in_loop_l_ni_1_Loop_l_load_B_tile_bk_proc_U0_local_B_3_19_d0;
wire   [2:0] dataflow_in_loop_l_ni_1_Loop_l_load_B_tile_bk_proc_U0_local_B_2_18_address0;
wire    dataflow_in_loop_l_ni_1_Loop_l_load_B_tile_bk_proc_U0_local_B_2_18_ce0;
wire    dataflow_in_loop_l_ni_1_Loop_l_load_B_tile_bk_proc_U0_local_B_2_18_we0;
wire   [31:0] dataflow_in_loop_l_ni_1_Loop_l_load_B_tile_bk_proc_U0_local_B_2_18_d0;
wire   [2:0] dataflow_in_loop_l_ni_1_Loop_l_load_B_tile_bk_proc_U0_local_B_1_17_address0;
wire    dataflow_in_loop_l_ni_1_Loop_l_load_B_tile_bk_proc_U0_local_B_1_17_ce0;
wire    dataflow_in_loop_l_ni_1_Loop_l_load_B_tile_bk_proc_U0_local_B_1_17_we0;
wire   [31:0] dataflow_in_loop_l_ni_1_Loop_l_load_B_tile_bk_proc_U0_local_B_1_17_d0;
wire   [2:0] dataflow_in_loop_l_ni_1_Loop_l_load_B_tile_bk_proc_U0_local_B_4_address0;
wire    dataflow_in_loop_l_ni_1_Loop_l_load_B_tile_bk_proc_U0_local_B_4_ce0;
wire    dataflow_in_loop_l_ni_1_Loop_l_load_B_tile_bk_proc_U0_local_B_4_we0;
wire   [31:0] dataflow_in_loop_l_ni_1_Loop_l_load_B_tile_bk_proc_U0_local_B_4_d0;
wire   [10:0] dataflow_in_loop_l_ni_1_Loop_l_load_B_tile_bk_proc_U0_v218_address0;
wire    dataflow_in_loop_l_ni_1_Loop_l_load_B_tile_bk_proc_U0_v218_ce0;
wire    ap_channel_done_local_B_4;
wire    dataflow_in_loop_l_ni_1_Loop_l_load_B_tile_bk_proc_U0_local_B_4_full_n;
reg    ap_sync_reg_channel_write_local_B_4;
wire    ap_sync_channel_write_local_B_4;
wire    ap_channel_done_local_B_1;
wire    dataflow_in_loop_l_ni_1_Loop_l_load_B_tile_bk_proc_U0_local_B_1_17_full_n;
reg    ap_sync_reg_channel_write_local_B_1;
wire    ap_sync_channel_write_local_B_1;
wire    ap_channel_done_local_B_2;
wire    dataflow_in_loop_l_ni_1_Loop_l_load_B_tile_bk_proc_U0_local_B_2_18_full_n;
reg    ap_sync_reg_channel_write_local_B_2;
wire    ap_sync_channel_write_local_B_2;
wire    ap_channel_done_local_B_3;
wire    dataflow_in_loop_l_ni_1_Loop_l_load_B_tile_bk_proc_U0_local_B_3_19_full_n;
reg    ap_sync_reg_channel_write_local_B_3;
wire    ap_sync_channel_write_local_B_3;
wire    ap_channel_done_local_B_3_51;
wire    dataflow_in_loop_l_ni_1_Loop_l_load_B_tile_bk_proc_U0_local_B_3_full_n;
reg    ap_sync_reg_channel_write_local_B_3_51;
wire    ap_sync_channel_write_local_B_3_51;
wire    ap_channel_done_local_B_2_50;
wire    dataflow_in_loop_l_ni_1_Loop_l_load_B_tile_bk_proc_U0_local_B_2_full_n;
reg    ap_sync_reg_channel_write_local_B_2_50;
wire    ap_sync_channel_write_local_B_2_50;
wire    ap_channel_done_local_B_1_49;
wire    dataflow_in_loop_l_ni_1_Loop_l_load_B_tile_bk_proc_U0_local_B_1_full_n;
reg    ap_sync_reg_channel_write_local_B_1_49;
wire    ap_sync_channel_write_local_B_1_49;
wire    ap_channel_done_local_B;
wire    dataflow_in_loop_l_ni_1_Loop_l_load_B_tile_bk_proc_U0_local_B_full_n;
reg    ap_sync_reg_channel_write_local_B;
wire    ap_sync_channel_write_local_B;
wire   [2:0] systolic_tile_modulate_U0_v168_0_address0;
wire    systolic_tile_modulate_U0_v168_0_ce0;
wire   [31:0] systolic_tile_modulate_U0_v168_0_d0;
wire    systolic_tile_modulate_U0_v168_0_we0;
wire   [2:0] systolic_tile_modulate_U0_v168_0_address1;
wire    systolic_tile_modulate_U0_v168_0_ce1;
wire   [31:0] systolic_tile_modulate_U0_v168_0_d1;
wire    systolic_tile_modulate_U0_v168_0_we1;
wire   [2:0] systolic_tile_modulate_U0_v169_0_address0;
wire    systolic_tile_modulate_U0_v169_0_ce0;
wire   [31:0] systolic_tile_modulate_U0_v169_0_d0;
wire    systolic_tile_modulate_U0_v169_0_we0;
wire   [2:0] systolic_tile_modulate_U0_v169_0_address1;
wire    systolic_tile_modulate_U0_v169_0_ce1;
wire   [31:0] systolic_tile_modulate_U0_v169_0_d1;
wire    systolic_tile_modulate_U0_v169_0_we1;
wire   [2:0] systolic_tile_modulate_U0_v169_1_address0;
wire    systolic_tile_modulate_U0_v169_1_ce0;
wire   [31:0] systolic_tile_modulate_U0_v169_1_d0;
wire    systolic_tile_modulate_U0_v169_1_we0;
wire   [2:0] systolic_tile_modulate_U0_v169_1_address1;
wire    systolic_tile_modulate_U0_v169_1_ce1;
wire   [31:0] systolic_tile_modulate_U0_v169_1_d1;
wire    systolic_tile_modulate_U0_v169_1_we1;
wire   [2:0] systolic_tile_modulate_U0_v169_2_address0;
wire    systolic_tile_modulate_U0_v169_2_ce0;
wire   [31:0] systolic_tile_modulate_U0_v169_2_d0;
wire    systolic_tile_modulate_U0_v169_2_we0;
wire   [2:0] systolic_tile_modulate_U0_v169_2_address1;
wire    systolic_tile_modulate_U0_v169_2_ce1;
wire   [31:0] systolic_tile_modulate_U0_v169_2_d1;
wire    systolic_tile_modulate_U0_v169_2_we1;
wire   [2:0] systolic_tile_modulate_U0_v169_3_address0;
wire    systolic_tile_modulate_U0_v169_3_ce0;
wire   [31:0] systolic_tile_modulate_U0_v169_3_d0;
wire    systolic_tile_modulate_U0_v169_3_we0;
wire   [2:0] systolic_tile_modulate_U0_v169_3_address1;
wire    systolic_tile_modulate_U0_v169_3_ce1;
wire   [31:0] systolic_tile_modulate_U0_v169_3_d1;
wire    systolic_tile_modulate_U0_v169_3_we1;
wire   [2:0] systolic_tile_modulate_U0_v169_4_address0;
wire    systolic_tile_modulate_U0_v169_4_ce0;
wire   [31:0] systolic_tile_modulate_U0_v169_4_d0;
wire    systolic_tile_modulate_U0_v169_4_we0;
wire   [2:0] systolic_tile_modulate_U0_v169_4_address1;
wire    systolic_tile_modulate_U0_v169_4_ce1;
wire   [31:0] systolic_tile_modulate_U0_v169_4_d1;
wire    systolic_tile_modulate_U0_v169_4_we1;
wire   [2:0] systolic_tile_modulate_U0_v169_5_address0;
wire    systolic_tile_modulate_U0_v169_5_ce0;
wire   [31:0] systolic_tile_modulate_U0_v169_5_d0;
wire    systolic_tile_modulate_U0_v169_5_we0;
wire   [2:0] systolic_tile_modulate_U0_v169_5_address1;
wire    systolic_tile_modulate_U0_v169_5_ce1;
wire   [31:0] systolic_tile_modulate_U0_v169_5_d1;
wire    systolic_tile_modulate_U0_v169_5_we1;
wire   [2:0] systolic_tile_modulate_U0_v169_6_address0;
wire    systolic_tile_modulate_U0_v169_6_ce0;
wire   [31:0] systolic_tile_modulate_U0_v169_6_d0;
wire    systolic_tile_modulate_U0_v169_6_we0;
wire   [2:0] systolic_tile_modulate_U0_v169_6_address1;
wire    systolic_tile_modulate_U0_v169_6_ce1;
wire   [31:0] systolic_tile_modulate_U0_v169_6_d1;
wire    systolic_tile_modulate_U0_v169_6_we1;
wire   [2:0] systolic_tile_modulate_U0_v169_7_address0;
wire    systolic_tile_modulate_U0_v169_7_ce0;
wire   [31:0] systolic_tile_modulate_U0_v169_7_d0;
wire    systolic_tile_modulate_U0_v169_7_we0;
wire   [2:0] systolic_tile_modulate_U0_v169_7_address1;
wire    systolic_tile_modulate_U0_v169_7_ce1;
wire   [31:0] systolic_tile_modulate_U0_v169_7_d1;
wire    systolic_tile_modulate_U0_v169_7_we1;
wire   [31:0] systolic_tile_modulate_U0_v170_0_0;
wire   [31:0] systolic_tile_modulate_U0_v170_1_0;
wire   [31:0] systolic_tile_modulate_U0_v170_2_0;
wire   [31:0] systolic_tile_modulate_U0_v170_3_0;
wire   [31:0] systolic_tile_modulate_U0_v170_4_0;
wire   [31:0] systolic_tile_modulate_U0_v170_5_0;
wire   [31:0] systolic_tile_modulate_U0_v170_6_0;
wire   [31:0] systolic_tile_modulate_U0_v170_7_0;
wire    systolic_tile_modulate_U0_v168_0_read;
wire    systolic_tile_modulate_U0_v169_0_read;
wire    systolic_tile_modulate_U0_v169_1_read;
wire    systolic_tile_modulate_U0_v169_2_read;
wire    systolic_tile_modulate_U0_v169_3_read;
wire    systolic_tile_modulate_U0_v169_4_read;
wire    systolic_tile_modulate_U0_v169_5_read;
wire    systolic_tile_modulate_U0_v169_6_read;
wire    systolic_tile_modulate_U0_v169_7_read;
wire    systolic_tile_modulate_U0_ap_start;
wire    systolic_tile_modulate_U0_v170_0_0_ap_vld;
wire    systolic_tile_modulate_U0_ap_done;
wire    systolic_tile_modulate_U0_v170_1_0_ap_vld;
wire    systolic_tile_modulate_U0_v170_2_0_ap_vld;
wire    systolic_tile_modulate_U0_v170_3_0_ap_vld;
wire    systolic_tile_modulate_U0_v170_4_0_ap_vld;
wire    systolic_tile_modulate_U0_v170_5_0_ap_vld;
wire    systolic_tile_modulate_U0_v170_6_0_ap_vld;
wire    systolic_tile_modulate_U0_v170_7_0_ap_vld;
wire    systolic_tile_modulate_U0_ap_ready;
wire    systolic_tile_modulate_U0_ap_idle;
wire    systolic_tile_modulate_U0_ap_continue;
wire    ap_channel_done_local_C_0;
wire    local_C_0_full_n;
reg    ap_sync_reg_channel_write_local_C_0;
wire    ap_sync_channel_write_local_C_0;
wire    ap_channel_done_local_C_0_1;
wire    local_C_0_1_full_n;
reg    ap_sync_reg_channel_write_local_C_0_1;
wire    ap_sync_channel_write_local_C_0_1;
wire    ap_channel_done_local_C_0_2;
wire    local_C_0_2_full_n;
reg    ap_sync_reg_channel_write_local_C_0_2;
wire    ap_sync_channel_write_local_C_0_2;
wire    ap_channel_done_local_C_0_3;
wire    local_C_0_3_full_n;
reg    ap_sync_reg_channel_write_local_C_0_3;
wire    ap_sync_channel_write_local_C_0_3;
wire    ap_channel_done_local_C_0_4;
wire    local_C_0_4_full_n;
reg    ap_sync_reg_channel_write_local_C_0_4;
wire    ap_sync_channel_write_local_C_0_4;
wire    ap_channel_done_local_C_0_5;
wire    local_C_0_5_full_n;
reg    ap_sync_reg_channel_write_local_C_0_5;
wire    ap_sync_channel_write_local_C_0_5;
wire    ap_channel_done_local_C_0_6;
wire    local_C_0_6_full_n;
reg    ap_sync_reg_channel_write_local_C_0_6;
wire    ap_sync_channel_write_local_C_0_6;
wire    ap_channel_done_local_C_0_7;
wire    local_C_0_7_full_n;
reg    ap_sync_reg_channel_write_local_C_0_7;
wire    ap_sync_channel_write_local_C_0_7;
wire    dataflow_in_loop_l_ni_1_Loop_l_store_C_tile_sj_proc_U0_ap_start;
wire    dataflow_in_loop_l_ni_1_Loop_l_store_C_tile_sj_proc_U0_ap_done;
wire    dataflow_in_loop_l_ni_1_Loop_l_store_C_tile_sj_proc_U0_ap_continue;
wire    dataflow_in_loop_l_ni_1_Loop_l_store_C_tile_sj_proc_U0_ap_idle;
wire    dataflow_in_loop_l_ni_1_Loop_l_store_C_tile_sj_proc_U0_ap_ready;
wire    dataflow_in_loop_l_ni_1_Loop_l_store_C_tile_sj_proc_U0_indvars_iv26_read;
wire   [7:0] dataflow_in_loop_l_ni_1_Loop_l_store_C_tile_sj_proc_U0_v219_address0;
wire    dataflow_in_loop_l_ni_1_Loop_l_store_C_tile_sj_proc_U0_v219_ce0;
wire    dataflow_in_loop_l_ni_1_Loop_l_store_C_tile_sj_proc_U0_v219_we0;
wire   [31:0] dataflow_in_loop_l_ni_1_Loop_l_store_C_tile_sj_proc_U0_v219_d0;
wire    local_A_0_i_full_n;
wire    local_A_0_t_empty_n;
wire    local_B_i_full_n;
wire    local_B_t_empty_n;
wire    local_B_1_49_i_full_n;
wire    local_B_1_49_t_empty_n;
wire    local_B_2_50_i_full_n;
wire    local_B_2_50_t_empty_n;
wire    local_B_3_51_i_full_n;
wire    local_B_3_51_t_empty_n;
wire    local_B_3_i_full_n;
wire    local_B_3_t_empty_n;
wire    local_B_2_i_full_n;
wire    local_B_2_t_empty_n;
wire    local_B_1_i_full_n;
wire    local_B_1_t_empty_n;
wire    local_B_4_i_full_n;
wire    local_B_4_t_empty_n;
wire    indvars_iv26_c_full_n;
wire   [4:0] indvars_iv26_c_dout;
wire   [2:0] indvars_iv26_c_num_data_valid;
wire   [2:0] indvars_iv26_c_fifo_cap;
wire    indvars_iv26_c_empty_n;
wire   [31:0] local_C_0_7_dout;
wire   [2:0] local_C_0_7_num_data_valid;
wire   [2:0] local_C_0_7_fifo_cap;
wire    local_C_0_7_empty_n;
wire   [31:0] local_C_0_6_dout;
wire   [2:0] local_C_0_6_num_data_valid;
wire   [2:0] local_C_0_6_fifo_cap;
wire    local_C_0_6_empty_n;
wire   [31:0] local_C_0_5_dout;
wire   [2:0] local_C_0_5_num_data_valid;
wire   [2:0] local_C_0_5_fifo_cap;
wire    local_C_0_5_empty_n;
wire   [31:0] local_C_0_4_dout;
wire   [2:0] local_C_0_4_num_data_valid;
wire   [2:0] local_C_0_4_fifo_cap;
wire    local_C_0_4_empty_n;
wire   [31:0] local_C_0_3_dout;
wire   [2:0] local_C_0_3_num_data_valid;
wire   [2:0] local_C_0_3_fifo_cap;
wire    local_C_0_3_empty_n;
wire   [31:0] local_C_0_2_dout;
wire   [2:0] local_C_0_2_num_data_valid;
wire   [2:0] local_C_0_2_fifo_cap;
wire    local_C_0_2_empty_n;
wire   [31:0] local_C_0_1_dout;
wire   [2:0] local_C_0_1_num_data_valid;
wire   [2:0] local_C_0_1_fifo_cap;
wire    local_C_0_1_empty_n;
wire   [31:0] local_C_0_dout;
wire   [2:0] local_C_0_num_data_valid;
wire   [2:0] local_C_0_fifo_cap;
wire    local_C_0_empty_n;
wire    ap_sync_ready;
reg    ap_sync_reg_dataflow_in_loop_l_ni_1_Loop_l_load_A_tile_ak_proc_U0_ap_ready;
wire    ap_sync_dataflow_in_loop_l_ni_1_Loop_l_load_A_tile_ak_proc_U0_ap_ready;
reg    ap_sync_reg_dataflow_in_loop_l_ni_1_Loop_l_load_B_tile_bk_proc_U0_ap_ready;
wire    ap_sync_dataflow_in_loop_l_ni_1_Loop_l_load_B_tile_bk_proc_U0_ap_ready;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_sync_reg_channel_write_local_B_4 = 1'b0;
#0 ap_sync_reg_channel_write_local_B_1 = 1'b0;
#0 ap_sync_reg_channel_write_local_B_2 = 1'b0;
#0 ap_sync_reg_channel_write_local_B_3 = 1'b0;
#0 ap_sync_reg_channel_write_local_B_3_51 = 1'b0;
#0 ap_sync_reg_channel_write_local_B_2_50 = 1'b0;
#0 ap_sync_reg_channel_write_local_B_1_49 = 1'b0;
#0 ap_sync_reg_channel_write_local_B = 1'b0;
#0 ap_sync_reg_channel_write_local_C_0 = 1'b0;
#0 ap_sync_reg_channel_write_local_C_0_1 = 1'b0;
#0 ap_sync_reg_channel_write_local_C_0_2 = 1'b0;
#0 ap_sync_reg_channel_write_local_C_0_3 = 1'b0;
#0 ap_sync_reg_channel_write_local_C_0_4 = 1'b0;
#0 ap_sync_reg_channel_write_local_C_0_5 = 1'b0;
#0 ap_sync_reg_channel_write_local_C_0_6 = 1'b0;
#0 ap_sync_reg_channel_write_local_C_0_7 = 1'b0;
#0 ap_sync_reg_dataflow_in_loop_l_ni_1_Loop_l_load_A_tile_ak_proc_U0_ap_ready = 1'b0;
#0 ap_sync_reg_dataflow_in_loop_l_ni_1_Loop_l_load_B_tile_bk_proc_U0_ap_ready = 1'b0;
end

systolic_modulate_dataflow_in_loop_l_ni_1_local_B_RAM_AUTO_1R1W #(
    .DataWidth( 32 ),
    .AddressRange( 8 ),
    .AddressWidth( 3 ))
local_B_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .i_address0(dataflow_in_loop_l_ni_1_Loop_l_load_B_tile_bk_proc_U0_local_B_address0),
    .i_ce0(dataflow_in_loop_l_ni_1_Loop_l_load_B_tile_bk_proc_U0_local_B_ce0),
    .i_we0(dataflow_in_loop_l_ni_1_Loop_l_load_B_tile_bk_proc_U0_local_B_we0),
    .i_d0(dataflow_in_loop_l_ni_1_Loop_l_load_B_tile_bk_proc_U0_local_B_d0),
    .i_q0(local_B_i_q0),
    .t_address0(systolic_tile_modulate_U0_v169_7_address0),
    .t_ce0(systolic_tile_modulate_U0_v169_7_ce0),
    .t_we0(1'b0),
    .t_d0(32'd0),
    .t_q0(local_B_t_q0),
    .i_ce(1'b1),
    .t_ce(1'b1),
    .i_full_n(local_B_i_full_n),
    .i_write(ap_channel_done_local_B),
    .t_empty_n(local_B_t_empty_n),
    .t_read(systolic_tile_modulate_U0_ap_ready)
);

systolic_modulate_dataflow_in_loop_l_ni_1_local_B_RAM_AUTO_1R1W #(
    .DataWidth( 32 ),
    .AddressRange( 8 ),
    .AddressWidth( 3 ))
local_B_1_49_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .i_address0(dataflow_in_loop_l_ni_1_Loop_l_load_B_tile_bk_proc_U0_local_B_1_address0),
    .i_ce0(dataflow_in_loop_l_ni_1_Loop_l_load_B_tile_bk_proc_U0_local_B_1_ce0),
    .i_we0(dataflow_in_loop_l_ni_1_Loop_l_load_B_tile_bk_proc_U0_local_B_1_we0),
    .i_d0(dataflow_in_loop_l_ni_1_Loop_l_load_B_tile_bk_proc_U0_local_B_1_d0),
    .i_q0(local_B_1_49_i_q0),
    .t_address0(systolic_tile_modulate_U0_v169_6_address0),
    .t_ce0(systolic_tile_modulate_U0_v169_6_ce0),
    .t_we0(1'b0),
    .t_d0(32'd0),
    .t_q0(local_B_1_49_t_q0),
    .i_ce(1'b1),
    .t_ce(1'b1),
    .i_full_n(local_B_1_49_i_full_n),
    .i_write(ap_channel_done_local_B_1_49),
    .t_empty_n(local_B_1_49_t_empty_n),
    .t_read(systolic_tile_modulate_U0_ap_ready)
);

systolic_modulate_dataflow_in_loop_l_ni_1_local_B_RAM_AUTO_1R1W #(
    .DataWidth( 32 ),
    .AddressRange( 8 ),
    .AddressWidth( 3 ))
local_B_2_50_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .i_address0(dataflow_in_loop_l_ni_1_Loop_l_load_B_tile_bk_proc_U0_local_B_2_address0),
    .i_ce0(dataflow_in_loop_l_ni_1_Loop_l_load_B_tile_bk_proc_U0_local_B_2_ce0),
    .i_we0(dataflow_in_loop_l_ni_1_Loop_l_load_B_tile_bk_proc_U0_local_B_2_we0),
    .i_d0(dataflow_in_loop_l_ni_1_Loop_l_load_B_tile_bk_proc_U0_local_B_2_d0),
    .i_q0(local_B_2_50_i_q0),
    .t_address0(systolic_tile_modulate_U0_v169_5_address0),
    .t_ce0(systolic_tile_modulate_U0_v169_5_ce0),
    .t_we0(1'b0),
    .t_d0(32'd0),
    .t_q0(local_B_2_50_t_q0),
    .i_ce(1'b1),
    .t_ce(1'b1),
    .i_full_n(local_B_2_50_i_full_n),
    .i_write(ap_channel_done_local_B_2_50),
    .t_empty_n(local_B_2_50_t_empty_n),
    .t_read(systolic_tile_modulate_U0_ap_ready)
);

systolic_modulate_dataflow_in_loop_l_ni_1_local_B_RAM_AUTO_1R1W #(
    .DataWidth( 32 ),
    .AddressRange( 8 ),
    .AddressWidth( 3 ))
local_B_3_51_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .i_address0(dataflow_in_loop_l_ni_1_Loop_l_load_B_tile_bk_proc_U0_local_B_3_address0),
    .i_ce0(dataflow_in_loop_l_ni_1_Loop_l_load_B_tile_bk_proc_U0_local_B_3_ce0),
    .i_we0(dataflow_in_loop_l_ni_1_Loop_l_load_B_tile_bk_proc_U0_local_B_3_we0),
    .i_d0(dataflow_in_loop_l_ni_1_Loop_l_load_B_tile_bk_proc_U0_local_B_3_d0),
    .i_q0(local_B_3_51_i_q0),
    .t_address0(systolic_tile_modulate_U0_v169_4_address0),
    .t_ce0(systolic_tile_modulate_U0_v169_4_ce0),
    .t_we0(1'b0),
    .t_d0(32'd0),
    .t_q0(local_B_3_51_t_q0),
    .i_ce(1'b1),
    .t_ce(1'b1),
    .i_full_n(local_B_3_51_i_full_n),
    .i_write(ap_channel_done_local_B_3_51),
    .t_empty_n(local_B_3_51_t_empty_n),
    .t_read(systolic_tile_modulate_U0_ap_ready)
);

systolic_modulate_dataflow_in_loop_l_ni_1_local_B_RAM_AUTO_1R1W #(
    .DataWidth( 32 ),
    .AddressRange( 8 ),
    .AddressWidth( 3 ))
local_B_3_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .i_address0(dataflow_in_loop_l_ni_1_Loop_l_load_B_tile_bk_proc_U0_local_B_3_19_address0),
    .i_ce0(dataflow_in_loop_l_ni_1_Loop_l_load_B_tile_bk_proc_U0_local_B_3_19_ce0),
    .i_we0(dataflow_in_loop_l_ni_1_Loop_l_load_B_tile_bk_proc_U0_local_B_3_19_we0),
    .i_d0(dataflow_in_loop_l_ni_1_Loop_l_load_B_tile_bk_proc_U0_local_B_3_19_d0),
    .i_q0(local_B_3_i_q0),
    .t_address0(systolic_tile_modulate_U0_v169_3_address0),
    .t_ce0(systolic_tile_modulate_U0_v169_3_ce0),
    .t_we0(1'b0),
    .t_d0(32'd0),
    .t_q0(local_B_3_t_q0),
    .i_ce(1'b1),
    .t_ce(1'b1),
    .i_full_n(local_B_3_i_full_n),
    .i_write(ap_channel_done_local_B_3),
    .t_empty_n(local_B_3_t_empty_n),
    .t_read(systolic_tile_modulate_U0_ap_ready)
);

systolic_modulate_dataflow_in_loop_l_ni_1_local_B_RAM_AUTO_1R1W #(
    .DataWidth( 32 ),
    .AddressRange( 8 ),
    .AddressWidth( 3 ))
local_B_2_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .i_address0(dataflow_in_loop_l_ni_1_Loop_l_load_B_tile_bk_proc_U0_local_B_2_18_address0),
    .i_ce0(dataflow_in_loop_l_ni_1_Loop_l_load_B_tile_bk_proc_U0_local_B_2_18_ce0),
    .i_we0(dataflow_in_loop_l_ni_1_Loop_l_load_B_tile_bk_proc_U0_local_B_2_18_we0),
    .i_d0(dataflow_in_loop_l_ni_1_Loop_l_load_B_tile_bk_proc_U0_local_B_2_18_d0),
    .i_q0(local_B_2_i_q0),
    .t_address0(systolic_tile_modulate_U0_v169_2_address0),
    .t_ce0(systolic_tile_modulate_U0_v169_2_ce0),
    .t_we0(1'b0),
    .t_d0(32'd0),
    .t_q0(local_B_2_t_q0),
    .i_ce(1'b1),
    .t_ce(1'b1),
    .i_full_n(local_B_2_i_full_n),
    .i_write(ap_channel_done_local_B_2),
    .t_empty_n(local_B_2_t_empty_n),
    .t_read(systolic_tile_modulate_U0_ap_ready)
);

systolic_modulate_dataflow_in_loop_l_ni_1_local_B_RAM_AUTO_1R1W #(
    .DataWidth( 32 ),
    .AddressRange( 8 ),
    .AddressWidth( 3 ))
local_B_1_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .i_address0(dataflow_in_loop_l_ni_1_Loop_l_load_B_tile_bk_proc_U0_local_B_1_17_address0),
    .i_ce0(dataflow_in_loop_l_ni_1_Loop_l_load_B_tile_bk_proc_U0_local_B_1_17_ce0),
    .i_we0(dataflow_in_loop_l_ni_1_Loop_l_load_B_tile_bk_proc_U0_local_B_1_17_we0),
    .i_d0(dataflow_in_loop_l_ni_1_Loop_l_load_B_tile_bk_proc_U0_local_B_1_17_d0),
    .i_q0(local_B_1_i_q0),
    .t_address0(systolic_tile_modulate_U0_v169_1_address0),
    .t_ce0(systolic_tile_modulate_U0_v169_1_ce0),
    .t_we0(1'b0),
    .t_d0(32'd0),
    .t_q0(local_B_1_t_q0),
    .i_ce(1'b1),
    .t_ce(1'b1),
    .i_full_n(local_B_1_i_full_n),
    .i_write(ap_channel_done_local_B_1),
    .t_empty_n(local_B_1_t_empty_n),
    .t_read(systolic_tile_modulate_U0_ap_ready)
);

systolic_modulate_dataflow_in_loop_l_ni_1_local_B_RAM_AUTO_1R1W #(
    .DataWidth( 32 ),
    .AddressRange( 8 ),
    .AddressWidth( 3 ))
local_B_4_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .i_address0(dataflow_in_loop_l_ni_1_Loop_l_load_B_tile_bk_proc_U0_local_B_4_address0),
    .i_ce0(dataflow_in_loop_l_ni_1_Loop_l_load_B_tile_bk_proc_U0_local_B_4_ce0),
    .i_we0(dataflow_in_loop_l_ni_1_Loop_l_load_B_tile_bk_proc_U0_local_B_4_we0),
    .i_d0(dataflow_in_loop_l_ni_1_Loop_l_load_B_tile_bk_proc_U0_local_B_4_d0),
    .i_q0(local_B_4_i_q0),
    .t_address0(systolic_tile_modulate_U0_v169_0_address0),
    .t_ce0(systolic_tile_modulate_U0_v169_0_ce0),
    .t_we0(1'b0),
    .t_d0(32'd0),
    .t_q0(local_B_4_t_q0),
    .i_ce(1'b1),
    .t_ce(1'b1),
    .i_full_n(local_B_4_i_full_n),
    .i_write(ap_channel_done_local_B_4),
    .t_empty_n(local_B_4_t_empty_n),
    .t_read(systolic_tile_modulate_U0_ap_ready)
);

systolic_modulate_dataflow_in_loop_l_ni_1_local_B_RAM_AUTO_1R1W #(
    .DataWidth( 32 ),
    .AddressRange( 8 ),
    .AddressWidth( 3 ))
local_A_0_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .i_address0(dataflow_in_loop_l_ni_1_Loop_l_load_A_tile_ak_proc_U0_local_A_0_address0),
    .i_ce0(dataflow_in_loop_l_ni_1_Loop_l_load_A_tile_ak_proc_U0_local_A_0_ce0),
    .i_we0(dataflow_in_loop_l_ni_1_Loop_l_load_A_tile_ak_proc_U0_local_A_0_we0),
    .i_d0(dataflow_in_loop_l_ni_1_Loop_l_load_A_tile_ak_proc_U0_local_A_0_d0),
    .i_q0(local_A_0_i_q0),
    .t_address0(systolic_tile_modulate_U0_v168_0_address0),
    .t_ce0(systolic_tile_modulate_U0_v168_0_ce0),
    .t_we0(1'b0),
    .t_d0(32'd0),
    .t_q0(local_A_0_t_q0),
    .i_ce(1'b1),
    .t_ce(1'b1),
    .i_full_n(local_A_0_i_full_n),
    .i_write(dataflow_in_loop_l_ni_1_Loop_l_load_A_tile_ak_proc_U0_ap_done),
    .t_empty_n(local_A_0_t_empty_n),
    .t_read(systolic_tile_modulate_U0_ap_ready)
);

systolic_modulate_dataflow_in_loop_l_ni_1_Loop_l_load_A_tile_ak_proc dataflow_in_loop_l_ni_1_Loop_l_load_A_tile_ak_proc_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(dataflow_in_loop_l_ni_1_Loop_l_load_A_tile_ak_proc_U0_ap_start),
    .ap_done(dataflow_in_loop_l_ni_1_Loop_l_load_A_tile_ak_proc_U0_ap_done),
    .ap_continue(dataflow_in_loop_l_ni_1_Loop_l_load_A_tile_ak_proc_U0_ap_continue),
    .ap_idle(dataflow_in_loop_l_ni_1_Loop_l_load_A_tile_ak_proc_U0_ap_idle),
    .ap_ready(dataflow_in_loop_l_ni_1_Loop_l_load_A_tile_ak_proc_U0_ap_ready),
    .indvars_iv26(indvars_iv26),
    .v217_address0(dataflow_in_loop_l_ni_1_Loop_l_load_A_tile_ak_proc_U0_v217_address0),
    .v217_ce0(dataflow_in_loop_l_ni_1_Loop_l_load_A_tile_ak_proc_U0_v217_ce0),
    .v217_q0(v217_q0),
    .local_A_0_address0(dataflow_in_loop_l_ni_1_Loop_l_load_A_tile_ak_proc_U0_local_A_0_address0),
    .local_A_0_ce0(dataflow_in_loop_l_ni_1_Loop_l_load_A_tile_ak_proc_U0_local_A_0_ce0),
    .local_A_0_we0(dataflow_in_loop_l_ni_1_Loop_l_load_A_tile_ak_proc_U0_local_A_0_we0),
    .local_A_0_d0(dataflow_in_loop_l_ni_1_Loop_l_load_A_tile_ak_proc_U0_local_A_0_d0),
    .indvars_iv26_c_din(dataflow_in_loop_l_ni_1_Loop_l_load_A_tile_ak_proc_U0_indvars_iv26_c_din),
    .indvars_iv26_c_num_data_valid(indvars_iv26_c_num_data_valid),
    .indvars_iv26_c_fifo_cap(indvars_iv26_c_fifo_cap),
    .indvars_iv26_c_full_n(indvars_iv26_c_full_n),
    .indvars_iv26_c_write(dataflow_in_loop_l_ni_1_Loop_l_load_A_tile_ak_proc_U0_indvars_iv26_c_write)
);

systolic_modulate_dataflow_in_loop_l_ni_1_Loop_l_load_B_tile_bk_proc dataflow_in_loop_l_ni_1_Loop_l_load_B_tile_bk_proc_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(dataflow_in_loop_l_ni_1_Loop_l_load_B_tile_bk_proc_U0_ap_start),
    .ap_done(dataflow_in_loop_l_ni_1_Loop_l_load_B_tile_bk_proc_U0_ap_done),
    .ap_continue(dataflow_in_loop_l_ni_1_Loop_l_load_B_tile_bk_proc_U0_ap_continue),
    .ap_idle(dataflow_in_loop_l_ni_1_Loop_l_load_B_tile_bk_proc_U0_ap_idle),
    .ap_ready(dataflow_in_loop_l_ni_1_Loop_l_load_B_tile_bk_proc_U0_ap_ready),
    .local_B_address0(dataflow_in_loop_l_ni_1_Loop_l_load_B_tile_bk_proc_U0_local_B_address0),
    .local_B_ce0(dataflow_in_loop_l_ni_1_Loop_l_load_B_tile_bk_proc_U0_local_B_ce0),
    .local_B_we0(dataflow_in_loop_l_ni_1_Loop_l_load_B_tile_bk_proc_U0_local_B_we0),
    .local_B_d0(dataflow_in_loop_l_ni_1_Loop_l_load_B_tile_bk_proc_U0_local_B_d0),
    .local_B_1_address0(dataflow_in_loop_l_ni_1_Loop_l_load_B_tile_bk_proc_U0_local_B_1_address0),
    .local_B_1_ce0(dataflow_in_loop_l_ni_1_Loop_l_load_B_tile_bk_proc_U0_local_B_1_ce0),
    .local_B_1_we0(dataflow_in_loop_l_ni_1_Loop_l_load_B_tile_bk_proc_U0_local_B_1_we0),
    .local_B_1_d0(dataflow_in_loop_l_ni_1_Loop_l_load_B_tile_bk_proc_U0_local_B_1_d0),
    .local_B_2_address0(dataflow_in_loop_l_ni_1_Loop_l_load_B_tile_bk_proc_U0_local_B_2_address0),
    .local_B_2_ce0(dataflow_in_loop_l_ni_1_Loop_l_load_B_tile_bk_proc_U0_local_B_2_ce0),
    .local_B_2_we0(dataflow_in_loop_l_ni_1_Loop_l_load_B_tile_bk_proc_U0_local_B_2_we0),
    .local_B_2_d0(dataflow_in_loop_l_ni_1_Loop_l_load_B_tile_bk_proc_U0_local_B_2_d0),
    .local_B_3_address0(dataflow_in_loop_l_ni_1_Loop_l_load_B_tile_bk_proc_U0_local_B_3_address0),
    .local_B_3_ce0(dataflow_in_loop_l_ni_1_Loop_l_load_B_tile_bk_proc_U0_local_B_3_ce0),
    .local_B_3_we0(dataflow_in_loop_l_ni_1_Loop_l_load_B_tile_bk_proc_U0_local_B_3_we0),
    .local_B_3_d0(dataflow_in_loop_l_ni_1_Loop_l_load_B_tile_bk_proc_U0_local_B_3_d0),
    .local_B_3_19_address0(dataflow_in_loop_l_ni_1_Loop_l_load_B_tile_bk_proc_U0_local_B_3_19_address0),
    .local_B_3_19_ce0(dataflow_in_loop_l_ni_1_Loop_l_load_B_tile_bk_proc_U0_local_B_3_19_ce0),
    .local_B_3_19_we0(dataflow_in_loop_l_ni_1_Loop_l_load_B_tile_bk_proc_U0_local_B_3_19_we0),
    .local_B_3_19_d0(dataflow_in_loop_l_ni_1_Loop_l_load_B_tile_bk_proc_U0_local_B_3_19_d0),
    .local_B_2_18_address0(dataflow_in_loop_l_ni_1_Loop_l_load_B_tile_bk_proc_U0_local_B_2_18_address0),
    .local_B_2_18_ce0(dataflow_in_loop_l_ni_1_Loop_l_load_B_tile_bk_proc_U0_local_B_2_18_ce0),
    .local_B_2_18_we0(dataflow_in_loop_l_ni_1_Loop_l_load_B_tile_bk_proc_U0_local_B_2_18_we0),
    .local_B_2_18_d0(dataflow_in_loop_l_ni_1_Loop_l_load_B_tile_bk_proc_U0_local_B_2_18_d0),
    .local_B_1_17_address0(dataflow_in_loop_l_ni_1_Loop_l_load_B_tile_bk_proc_U0_local_B_1_17_address0),
    .local_B_1_17_ce0(dataflow_in_loop_l_ni_1_Loop_l_load_B_tile_bk_proc_U0_local_B_1_17_ce0),
    .local_B_1_17_we0(dataflow_in_loop_l_ni_1_Loop_l_load_B_tile_bk_proc_U0_local_B_1_17_we0),
    .local_B_1_17_d0(dataflow_in_loop_l_ni_1_Loop_l_load_B_tile_bk_proc_U0_local_B_1_17_d0),
    .local_B_4_address0(dataflow_in_loop_l_ni_1_Loop_l_load_B_tile_bk_proc_U0_local_B_4_address0),
    .local_B_4_ce0(dataflow_in_loop_l_ni_1_Loop_l_load_B_tile_bk_proc_U0_local_B_4_ce0),
    .local_B_4_we0(dataflow_in_loop_l_ni_1_Loop_l_load_B_tile_bk_proc_U0_local_B_4_we0),
    .local_B_4_d0(dataflow_in_loop_l_ni_1_Loop_l_load_B_tile_bk_proc_U0_local_B_4_d0),
    .indvars_iv26(indvars_iv26),
    .v218_address0(dataflow_in_loop_l_ni_1_Loop_l_load_B_tile_bk_proc_U0_v218_address0),
    .v218_ce0(dataflow_in_loop_l_ni_1_Loop_l_load_B_tile_bk_proc_U0_v218_ce0),
    .v218_q0(v218_q0)
);

systolic_modulate_systolic_tile_modulate systolic_tile_modulate_U0(
    .v168_0_address0(systolic_tile_modulate_U0_v168_0_address0),
    .v168_0_ce0(systolic_tile_modulate_U0_v168_0_ce0),
    .v168_0_d0(systolic_tile_modulate_U0_v168_0_d0),
    .v168_0_q0(local_A_0_t_q0),
    .v168_0_we0(systolic_tile_modulate_U0_v168_0_we0),
    .v168_0_address1(systolic_tile_modulate_U0_v168_0_address1),
    .v168_0_ce1(systolic_tile_modulate_U0_v168_0_ce1),
    .v168_0_d1(systolic_tile_modulate_U0_v168_0_d1),
    .v168_0_q1(32'd0),
    .v168_0_we1(systolic_tile_modulate_U0_v168_0_we1),
    .v169_0_address0(systolic_tile_modulate_U0_v169_0_address0),
    .v169_0_ce0(systolic_tile_modulate_U0_v169_0_ce0),
    .v169_0_d0(systolic_tile_modulate_U0_v169_0_d0),
    .v169_0_q0(local_B_4_t_q0),
    .v169_0_we0(systolic_tile_modulate_U0_v169_0_we0),
    .v169_0_address1(systolic_tile_modulate_U0_v169_0_address1),
    .v169_0_ce1(systolic_tile_modulate_U0_v169_0_ce1),
    .v169_0_d1(systolic_tile_modulate_U0_v169_0_d1),
    .v169_0_q1(32'd0),
    .v169_0_we1(systolic_tile_modulate_U0_v169_0_we1),
    .v169_1_address0(systolic_tile_modulate_U0_v169_1_address0),
    .v169_1_ce0(systolic_tile_modulate_U0_v169_1_ce0),
    .v169_1_d0(systolic_tile_modulate_U0_v169_1_d0),
    .v169_1_q0(local_B_1_t_q0),
    .v169_1_we0(systolic_tile_modulate_U0_v169_1_we0),
    .v169_1_address1(systolic_tile_modulate_U0_v169_1_address1),
    .v169_1_ce1(systolic_tile_modulate_U0_v169_1_ce1),
    .v169_1_d1(systolic_tile_modulate_U0_v169_1_d1),
    .v169_1_q1(32'd0),
    .v169_1_we1(systolic_tile_modulate_U0_v169_1_we1),
    .v169_2_address0(systolic_tile_modulate_U0_v169_2_address0),
    .v169_2_ce0(systolic_tile_modulate_U0_v169_2_ce0),
    .v169_2_d0(systolic_tile_modulate_U0_v169_2_d0),
    .v169_2_q0(local_B_2_t_q0),
    .v169_2_we0(systolic_tile_modulate_U0_v169_2_we0),
    .v169_2_address1(systolic_tile_modulate_U0_v169_2_address1),
    .v169_2_ce1(systolic_tile_modulate_U0_v169_2_ce1),
    .v169_2_d1(systolic_tile_modulate_U0_v169_2_d1),
    .v169_2_q1(32'd0),
    .v169_2_we1(systolic_tile_modulate_U0_v169_2_we1),
    .v169_3_address0(systolic_tile_modulate_U0_v169_3_address0),
    .v169_3_ce0(systolic_tile_modulate_U0_v169_3_ce0),
    .v169_3_d0(systolic_tile_modulate_U0_v169_3_d0),
    .v169_3_q0(local_B_3_t_q0),
    .v169_3_we0(systolic_tile_modulate_U0_v169_3_we0),
    .v169_3_address1(systolic_tile_modulate_U0_v169_3_address1),
    .v169_3_ce1(systolic_tile_modulate_U0_v169_3_ce1),
    .v169_3_d1(systolic_tile_modulate_U0_v169_3_d1),
    .v169_3_q1(32'd0),
    .v169_3_we1(systolic_tile_modulate_U0_v169_3_we1),
    .v169_4_address0(systolic_tile_modulate_U0_v169_4_address0),
    .v169_4_ce0(systolic_tile_modulate_U0_v169_4_ce0),
    .v169_4_d0(systolic_tile_modulate_U0_v169_4_d0),
    .v169_4_q0(local_B_3_51_t_q0),
    .v169_4_we0(systolic_tile_modulate_U0_v169_4_we0),
    .v169_4_address1(systolic_tile_modulate_U0_v169_4_address1),
    .v169_4_ce1(systolic_tile_modulate_U0_v169_4_ce1),
    .v169_4_d1(systolic_tile_modulate_U0_v169_4_d1),
    .v169_4_q1(32'd0),
    .v169_4_we1(systolic_tile_modulate_U0_v169_4_we1),
    .v169_5_address0(systolic_tile_modulate_U0_v169_5_address0),
    .v169_5_ce0(systolic_tile_modulate_U0_v169_5_ce0),
    .v169_5_d0(systolic_tile_modulate_U0_v169_5_d0),
    .v169_5_q0(local_B_2_50_t_q0),
    .v169_5_we0(systolic_tile_modulate_U0_v169_5_we0),
    .v169_5_address1(systolic_tile_modulate_U0_v169_5_address1),
    .v169_5_ce1(systolic_tile_modulate_U0_v169_5_ce1),
    .v169_5_d1(systolic_tile_modulate_U0_v169_5_d1),
    .v169_5_q1(32'd0),
    .v169_5_we1(systolic_tile_modulate_U0_v169_5_we1),
    .v169_6_address0(systolic_tile_modulate_U0_v169_6_address0),
    .v169_6_ce0(systolic_tile_modulate_U0_v169_6_ce0),
    .v169_6_d0(systolic_tile_modulate_U0_v169_6_d0),
    .v169_6_q0(local_B_1_49_t_q0),
    .v169_6_we0(systolic_tile_modulate_U0_v169_6_we0),
    .v169_6_address1(systolic_tile_modulate_U0_v169_6_address1),
    .v169_6_ce1(systolic_tile_modulate_U0_v169_6_ce1),
    .v169_6_d1(systolic_tile_modulate_U0_v169_6_d1),
    .v169_6_q1(32'd0),
    .v169_6_we1(systolic_tile_modulate_U0_v169_6_we1),
    .v169_7_address0(systolic_tile_modulate_U0_v169_7_address0),
    .v169_7_ce0(systolic_tile_modulate_U0_v169_7_ce0),
    .v169_7_d0(systolic_tile_modulate_U0_v169_7_d0),
    .v169_7_q0(local_B_t_q0),
    .v169_7_we0(systolic_tile_modulate_U0_v169_7_we0),
    .v169_7_address1(systolic_tile_modulate_U0_v169_7_address1),
    .v169_7_ce1(systolic_tile_modulate_U0_v169_7_ce1),
    .v169_7_d1(systolic_tile_modulate_U0_v169_7_d1),
    .v169_7_q1(32'd0),
    .v169_7_we1(systolic_tile_modulate_U0_v169_7_we1),
    .v170_0_0(systolic_tile_modulate_U0_v170_0_0),
    .v170_1_0(systolic_tile_modulate_U0_v170_1_0),
    .v170_2_0(systolic_tile_modulate_U0_v170_2_0),
    .v170_3_0(systolic_tile_modulate_U0_v170_3_0),
    .v170_4_0(systolic_tile_modulate_U0_v170_4_0),
    .v170_5_0(systolic_tile_modulate_U0_v170_5_0),
    .v170_6_0(systolic_tile_modulate_U0_v170_6_0),
    .v170_7_0(systolic_tile_modulate_U0_v170_7_0),
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .v168_0_empty_n(1'b0),
    .v168_0_read(systolic_tile_modulate_U0_v168_0_read),
    .v169_0_empty_n(1'b0),
    .v169_0_read(systolic_tile_modulate_U0_v169_0_read),
    .v169_1_empty_n(1'b0),
    .v169_1_read(systolic_tile_modulate_U0_v169_1_read),
    .v169_2_empty_n(1'b0),
    .v169_2_read(systolic_tile_modulate_U0_v169_2_read),
    .v169_3_empty_n(1'b0),
    .v169_3_read(systolic_tile_modulate_U0_v169_3_read),
    .v169_4_empty_n(1'b0),
    .v169_4_read(systolic_tile_modulate_U0_v169_4_read),
    .v169_5_empty_n(1'b0),
    .v169_5_read(systolic_tile_modulate_U0_v169_5_read),
    .v169_6_empty_n(1'b0),
    .v169_6_read(systolic_tile_modulate_U0_v169_6_read),
    .v169_7_empty_n(1'b0),
    .v169_7_read(systolic_tile_modulate_U0_v169_7_read),
    .ap_start(systolic_tile_modulate_U0_ap_start),
    .v170_0_0_ap_vld(systolic_tile_modulate_U0_v170_0_0_ap_vld),
    .ap_done(systolic_tile_modulate_U0_ap_done),
    .v170_1_0_ap_vld(systolic_tile_modulate_U0_v170_1_0_ap_vld),
    .v170_2_0_ap_vld(systolic_tile_modulate_U0_v170_2_0_ap_vld),
    .v170_3_0_ap_vld(systolic_tile_modulate_U0_v170_3_0_ap_vld),
    .v170_4_0_ap_vld(systolic_tile_modulate_U0_v170_4_0_ap_vld),
    .v170_5_0_ap_vld(systolic_tile_modulate_U0_v170_5_0_ap_vld),
    .v170_6_0_ap_vld(systolic_tile_modulate_U0_v170_6_0_ap_vld),
    .v170_7_0_ap_vld(systolic_tile_modulate_U0_v170_7_0_ap_vld),
    .ap_ready(systolic_tile_modulate_U0_ap_ready),
    .ap_idle(systolic_tile_modulate_U0_ap_idle),
    .ap_continue(systolic_tile_modulate_U0_ap_continue)
);

systolic_modulate_dataflow_in_loop_l_ni_1_Loop_l_store_C_tile_sj_proc dataflow_in_loop_l_ni_1_Loop_l_store_C_tile_sj_proc_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(dataflow_in_loop_l_ni_1_Loop_l_store_C_tile_sj_proc_U0_ap_start),
    .ap_done(dataflow_in_loop_l_ni_1_Loop_l_store_C_tile_sj_proc_U0_ap_done),
    .ap_continue(dataflow_in_loop_l_ni_1_Loop_l_store_C_tile_sj_proc_U0_ap_continue),
    .ap_idle(dataflow_in_loop_l_ni_1_Loop_l_store_C_tile_sj_proc_U0_ap_idle),
    .ap_ready(dataflow_in_loop_l_ni_1_Loop_l_store_C_tile_sj_proc_U0_ap_ready),
    .local_C_0_7(local_C_0_7_dout),
    .local_C_0_6(local_C_0_6_dout),
    .local_C_0_5(local_C_0_5_dout),
    .local_C_0_4(local_C_0_4_dout),
    .local_C_0_3(local_C_0_3_dout),
    .local_C_0_2(local_C_0_2_dout),
    .local_C_0_1(local_C_0_1_dout),
    .local_C_0(local_C_0_dout),
    .indvars_iv26_dout(indvars_iv26_c_dout),
    .indvars_iv26_num_data_valid(indvars_iv26_c_num_data_valid),
    .indvars_iv26_fifo_cap(indvars_iv26_c_fifo_cap),
    .indvars_iv26_empty_n(indvars_iv26_c_empty_n),
    .indvars_iv26_read(dataflow_in_loop_l_ni_1_Loop_l_store_C_tile_sj_proc_U0_indvars_iv26_read),
    .v219_address0(dataflow_in_loop_l_ni_1_Loop_l_store_C_tile_sj_proc_U0_v219_address0),
    .v219_ce0(dataflow_in_loop_l_ni_1_Loop_l_store_C_tile_sj_proc_U0_v219_ce0),
    .v219_we0(dataflow_in_loop_l_ni_1_Loop_l_store_C_tile_sj_proc_U0_v219_we0),
    .v219_d0(dataflow_in_loop_l_ni_1_Loop_l_store_C_tile_sj_proc_U0_v219_d0)
);

systolic_modulate_fifo_w5_d3_S indvars_iv26_c_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(dataflow_in_loop_l_ni_1_Loop_l_load_A_tile_ak_proc_U0_indvars_iv26_c_din),
    .if_full_n(indvars_iv26_c_full_n),
    .if_write(dataflow_in_loop_l_ni_1_Loop_l_load_A_tile_ak_proc_U0_indvars_iv26_c_write),
    .if_dout(indvars_iv26_c_dout),
    .if_num_data_valid(indvars_iv26_c_num_data_valid),
    .if_fifo_cap(indvars_iv26_c_fifo_cap),
    .if_empty_n(indvars_iv26_c_empty_n),
    .if_read(dataflow_in_loop_l_ni_1_Loop_l_store_C_tile_sj_proc_U0_indvars_iv26_read)
);

systolic_modulate_fifo_w32_d2_S_x local_C_0_7_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(systolic_tile_modulate_U0_v170_0_0),
    .if_full_n(local_C_0_7_full_n),
    .if_write(ap_channel_done_local_C_0_7),
    .if_dout(local_C_0_7_dout),
    .if_num_data_valid(local_C_0_7_num_data_valid),
    .if_fifo_cap(local_C_0_7_fifo_cap),
    .if_empty_n(local_C_0_7_empty_n),
    .if_read(dataflow_in_loop_l_ni_1_Loop_l_store_C_tile_sj_proc_U0_ap_ready)
);

systolic_modulate_fifo_w32_d2_S_x local_C_0_6_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(systolic_tile_modulate_U0_v170_1_0),
    .if_full_n(local_C_0_6_full_n),
    .if_write(ap_channel_done_local_C_0_6),
    .if_dout(local_C_0_6_dout),
    .if_num_data_valid(local_C_0_6_num_data_valid),
    .if_fifo_cap(local_C_0_6_fifo_cap),
    .if_empty_n(local_C_0_6_empty_n),
    .if_read(dataflow_in_loop_l_ni_1_Loop_l_store_C_tile_sj_proc_U0_ap_ready)
);

systolic_modulate_fifo_w32_d2_S_x local_C_0_5_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(systolic_tile_modulate_U0_v170_2_0),
    .if_full_n(local_C_0_5_full_n),
    .if_write(ap_channel_done_local_C_0_5),
    .if_dout(local_C_0_5_dout),
    .if_num_data_valid(local_C_0_5_num_data_valid),
    .if_fifo_cap(local_C_0_5_fifo_cap),
    .if_empty_n(local_C_0_5_empty_n),
    .if_read(dataflow_in_loop_l_ni_1_Loop_l_store_C_tile_sj_proc_U0_ap_ready)
);

systolic_modulate_fifo_w32_d2_S_x local_C_0_4_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(systolic_tile_modulate_U0_v170_3_0),
    .if_full_n(local_C_0_4_full_n),
    .if_write(ap_channel_done_local_C_0_4),
    .if_dout(local_C_0_4_dout),
    .if_num_data_valid(local_C_0_4_num_data_valid),
    .if_fifo_cap(local_C_0_4_fifo_cap),
    .if_empty_n(local_C_0_4_empty_n),
    .if_read(dataflow_in_loop_l_ni_1_Loop_l_store_C_tile_sj_proc_U0_ap_ready)
);

systolic_modulate_fifo_w32_d2_S_x local_C_0_3_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(systolic_tile_modulate_U0_v170_4_0),
    .if_full_n(local_C_0_3_full_n),
    .if_write(ap_channel_done_local_C_0_3),
    .if_dout(local_C_0_3_dout),
    .if_num_data_valid(local_C_0_3_num_data_valid),
    .if_fifo_cap(local_C_0_3_fifo_cap),
    .if_empty_n(local_C_0_3_empty_n),
    .if_read(dataflow_in_loop_l_ni_1_Loop_l_store_C_tile_sj_proc_U0_ap_ready)
);

systolic_modulate_fifo_w32_d2_S_x local_C_0_2_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(systolic_tile_modulate_U0_v170_5_0),
    .if_full_n(local_C_0_2_full_n),
    .if_write(ap_channel_done_local_C_0_2),
    .if_dout(local_C_0_2_dout),
    .if_num_data_valid(local_C_0_2_num_data_valid),
    .if_fifo_cap(local_C_0_2_fifo_cap),
    .if_empty_n(local_C_0_2_empty_n),
    .if_read(dataflow_in_loop_l_ni_1_Loop_l_store_C_tile_sj_proc_U0_ap_ready)
);

systolic_modulate_fifo_w32_d2_S_x local_C_0_1_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(systolic_tile_modulate_U0_v170_6_0),
    .if_full_n(local_C_0_1_full_n),
    .if_write(ap_channel_done_local_C_0_1),
    .if_dout(local_C_0_1_dout),
    .if_num_data_valid(local_C_0_1_num_data_valid),
    .if_fifo_cap(local_C_0_1_fifo_cap),
    .if_empty_n(local_C_0_1_empty_n),
    .if_read(dataflow_in_loop_l_ni_1_Loop_l_store_C_tile_sj_proc_U0_ap_ready)
);

systolic_modulate_fifo_w32_d2_S_x local_C_0_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(systolic_tile_modulate_U0_v170_7_0),
    .if_full_n(local_C_0_full_n),
    .if_write(ap_channel_done_local_C_0),
    .if_dout(local_C_0_dout),
    .if_num_data_valid(local_C_0_num_data_valid),
    .if_fifo_cap(local_C_0_fifo_cap),
    .if_empty_n(local_C_0_empty_n),
    .if_read(dataflow_in_loop_l_ni_1_Loop_l_store_C_tile_sj_proc_U0_ap_ready)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_sync_reg_channel_write_local_B <= 1'b0;
    end else begin
        if (((dataflow_in_loop_l_ni_1_Loop_l_load_B_tile_bk_proc_U0_ap_done & dataflow_in_loop_l_ni_1_Loop_l_load_B_tile_bk_proc_U0_ap_continue) == 1'b1)) begin
            ap_sync_reg_channel_write_local_B <= 1'b0;
        end else begin
            ap_sync_reg_channel_write_local_B <= ap_sync_channel_write_local_B;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_sync_reg_channel_write_local_B_1 <= 1'b0;
    end else begin
        if (((dataflow_in_loop_l_ni_1_Loop_l_load_B_tile_bk_proc_U0_ap_done & dataflow_in_loop_l_ni_1_Loop_l_load_B_tile_bk_proc_U0_ap_continue) == 1'b1)) begin
            ap_sync_reg_channel_write_local_B_1 <= 1'b0;
        end else begin
            ap_sync_reg_channel_write_local_B_1 <= ap_sync_channel_write_local_B_1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_sync_reg_channel_write_local_B_1_49 <= 1'b0;
    end else begin
        if (((dataflow_in_loop_l_ni_1_Loop_l_load_B_tile_bk_proc_U0_ap_done & dataflow_in_loop_l_ni_1_Loop_l_load_B_tile_bk_proc_U0_ap_continue) == 1'b1)) begin
            ap_sync_reg_channel_write_local_B_1_49 <= 1'b0;
        end else begin
            ap_sync_reg_channel_write_local_B_1_49 <= ap_sync_channel_write_local_B_1_49;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_sync_reg_channel_write_local_B_2 <= 1'b0;
    end else begin
        if (((dataflow_in_loop_l_ni_1_Loop_l_load_B_tile_bk_proc_U0_ap_done & dataflow_in_loop_l_ni_1_Loop_l_load_B_tile_bk_proc_U0_ap_continue) == 1'b1)) begin
            ap_sync_reg_channel_write_local_B_2 <= 1'b0;
        end else begin
            ap_sync_reg_channel_write_local_B_2 <= ap_sync_channel_write_local_B_2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_sync_reg_channel_write_local_B_2_50 <= 1'b0;
    end else begin
        if (((dataflow_in_loop_l_ni_1_Loop_l_load_B_tile_bk_proc_U0_ap_done & dataflow_in_loop_l_ni_1_Loop_l_load_B_tile_bk_proc_U0_ap_continue) == 1'b1)) begin
            ap_sync_reg_channel_write_local_B_2_50 <= 1'b0;
        end else begin
            ap_sync_reg_channel_write_local_B_2_50 <= ap_sync_channel_write_local_B_2_50;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_sync_reg_channel_write_local_B_3 <= 1'b0;
    end else begin
        if (((dataflow_in_loop_l_ni_1_Loop_l_load_B_tile_bk_proc_U0_ap_done & dataflow_in_loop_l_ni_1_Loop_l_load_B_tile_bk_proc_U0_ap_continue) == 1'b1)) begin
            ap_sync_reg_channel_write_local_B_3 <= 1'b0;
        end else begin
            ap_sync_reg_channel_write_local_B_3 <= ap_sync_channel_write_local_B_3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_sync_reg_channel_write_local_B_3_51 <= 1'b0;
    end else begin
        if (((dataflow_in_loop_l_ni_1_Loop_l_load_B_tile_bk_proc_U0_ap_done & dataflow_in_loop_l_ni_1_Loop_l_load_B_tile_bk_proc_U0_ap_continue) == 1'b1)) begin
            ap_sync_reg_channel_write_local_B_3_51 <= 1'b0;
        end else begin
            ap_sync_reg_channel_write_local_B_3_51 <= ap_sync_channel_write_local_B_3_51;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_sync_reg_channel_write_local_B_4 <= 1'b0;
    end else begin
        if (((dataflow_in_loop_l_ni_1_Loop_l_load_B_tile_bk_proc_U0_ap_done & dataflow_in_loop_l_ni_1_Loop_l_load_B_tile_bk_proc_U0_ap_continue) == 1'b1)) begin
            ap_sync_reg_channel_write_local_B_4 <= 1'b0;
        end else begin
            ap_sync_reg_channel_write_local_B_4 <= ap_sync_channel_write_local_B_4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_sync_reg_channel_write_local_C_0 <= 1'b0;
    end else begin
        if (((systolic_tile_modulate_U0_ap_done & systolic_tile_modulate_U0_ap_continue) == 1'b1)) begin
            ap_sync_reg_channel_write_local_C_0 <= 1'b0;
        end else begin
            ap_sync_reg_channel_write_local_C_0 <= ap_sync_channel_write_local_C_0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_sync_reg_channel_write_local_C_0_1 <= 1'b0;
    end else begin
        if (((systolic_tile_modulate_U0_ap_done & systolic_tile_modulate_U0_ap_continue) == 1'b1)) begin
            ap_sync_reg_channel_write_local_C_0_1 <= 1'b0;
        end else begin
            ap_sync_reg_channel_write_local_C_0_1 <= ap_sync_channel_write_local_C_0_1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_sync_reg_channel_write_local_C_0_2 <= 1'b0;
    end else begin
        if (((systolic_tile_modulate_U0_ap_done & systolic_tile_modulate_U0_ap_continue) == 1'b1)) begin
            ap_sync_reg_channel_write_local_C_0_2 <= 1'b0;
        end else begin
            ap_sync_reg_channel_write_local_C_0_2 <= ap_sync_channel_write_local_C_0_2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_sync_reg_channel_write_local_C_0_3 <= 1'b0;
    end else begin
        if (((systolic_tile_modulate_U0_ap_done & systolic_tile_modulate_U0_ap_continue) == 1'b1)) begin
            ap_sync_reg_channel_write_local_C_0_3 <= 1'b0;
        end else begin
            ap_sync_reg_channel_write_local_C_0_3 <= ap_sync_channel_write_local_C_0_3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_sync_reg_channel_write_local_C_0_4 <= 1'b0;
    end else begin
        if (((systolic_tile_modulate_U0_ap_done & systolic_tile_modulate_U0_ap_continue) == 1'b1)) begin
            ap_sync_reg_channel_write_local_C_0_4 <= 1'b0;
        end else begin
            ap_sync_reg_channel_write_local_C_0_4 <= ap_sync_channel_write_local_C_0_4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_sync_reg_channel_write_local_C_0_5 <= 1'b0;
    end else begin
        if (((systolic_tile_modulate_U0_ap_done & systolic_tile_modulate_U0_ap_continue) == 1'b1)) begin
            ap_sync_reg_channel_write_local_C_0_5 <= 1'b0;
        end else begin
            ap_sync_reg_channel_write_local_C_0_5 <= ap_sync_channel_write_local_C_0_5;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_sync_reg_channel_write_local_C_0_6 <= 1'b0;
    end else begin
        if (((systolic_tile_modulate_U0_ap_done & systolic_tile_modulate_U0_ap_continue) == 1'b1)) begin
            ap_sync_reg_channel_write_local_C_0_6 <= 1'b0;
        end else begin
            ap_sync_reg_channel_write_local_C_0_6 <= ap_sync_channel_write_local_C_0_6;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_sync_reg_channel_write_local_C_0_7 <= 1'b0;
    end else begin
        if (((systolic_tile_modulate_U0_ap_done & systolic_tile_modulate_U0_ap_continue) == 1'b1)) begin
            ap_sync_reg_channel_write_local_C_0_7 <= 1'b0;
        end else begin
            ap_sync_reg_channel_write_local_C_0_7 <= ap_sync_channel_write_local_C_0_7;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_sync_reg_dataflow_in_loop_l_ni_1_Loop_l_load_A_tile_ak_proc_U0_ap_ready <= 1'b0;
    end else begin
        if (((ap_sync_ready & ap_start) == 1'b1)) begin
            ap_sync_reg_dataflow_in_loop_l_ni_1_Loop_l_load_A_tile_ak_proc_U0_ap_ready <= 1'b0;
        end else begin
            ap_sync_reg_dataflow_in_loop_l_ni_1_Loop_l_load_A_tile_ak_proc_U0_ap_ready <= ap_sync_dataflow_in_loop_l_ni_1_Loop_l_load_A_tile_ak_proc_U0_ap_ready;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_sync_reg_dataflow_in_loop_l_ni_1_Loop_l_load_B_tile_bk_proc_U0_ap_ready <= 1'b0;
    end else begin
        if (((ap_sync_ready & ap_start) == 1'b1)) begin
            ap_sync_reg_dataflow_in_loop_l_ni_1_Loop_l_load_B_tile_bk_proc_U0_ap_ready <= 1'b0;
        end else begin
            ap_sync_reg_dataflow_in_loop_l_ni_1_Loop_l_load_B_tile_bk_proc_U0_ap_ready <= ap_sync_dataflow_in_loop_l_ni_1_Loop_l_load_B_tile_bk_proc_U0_ap_ready;
        end
    end
end

assign ap_channel_done_local_B = ((ap_sync_reg_channel_write_local_B ^ 1'b1) & dataflow_in_loop_l_ni_1_Loop_l_load_B_tile_bk_proc_U0_ap_done);

assign ap_channel_done_local_B_1 = ((ap_sync_reg_channel_write_local_B_1 ^ 1'b1) & dataflow_in_loop_l_ni_1_Loop_l_load_B_tile_bk_proc_U0_ap_done);

assign ap_channel_done_local_B_1_49 = ((ap_sync_reg_channel_write_local_B_1_49 ^ 1'b1) & dataflow_in_loop_l_ni_1_Loop_l_load_B_tile_bk_proc_U0_ap_done);

assign ap_channel_done_local_B_2 = ((ap_sync_reg_channel_write_local_B_2 ^ 1'b1) & dataflow_in_loop_l_ni_1_Loop_l_load_B_tile_bk_proc_U0_ap_done);

assign ap_channel_done_local_B_2_50 = ((ap_sync_reg_channel_write_local_B_2_50 ^ 1'b1) & dataflow_in_loop_l_ni_1_Loop_l_load_B_tile_bk_proc_U0_ap_done);

assign ap_channel_done_local_B_3 = ((ap_sync_reg_channel_write_local_B_3 ^ 1'b1) & dataflow_in_loop_l_ni_1_Loop_l_load_B_tile_bk_proc_U0_ap_done);

assign ap_channel_done_local_B_3_51 = ((ap_sync_reg_channel_write_local_B_3_51 ^ 1'b1) & dataflow_in_loop_l_ni_1_Loop_l_load_B_tile_bk_proc_U0_ap_done);

assign ap_channel_done_local_B_4 = ((ap_sync_reg_channel_write_local_B_4 ^ 1'b1) & dataflow_in_loop_l_ni_1_Loop_l_load_B_tile_bk_proc_U0_ap_done);

assign ap_channel_done_local_C_0 = (systolic_tile_modulate_U0_ap_done & (ap_sync_reg_channel_write_local_C_0 ^ 1'b1));

assign ap_channel_done_local_C_0_1 = (systolic_tile_modulate_U0_ap_done & (ap_sync_reg_channel_write_local_C_0_1 ^ 1'b1));

assign ap_channel_done_local_C_0_2 = (systolic_tile_modulate_U0_ap_done & (ap_sync_reg_channel_write_local_C_0_2 ^ 1'b1));

assign ap_channel_done_local_C_0_3 = (systolic_tile_modulate_U0_ap_done & (ap_sync_reg_channel_write_local_C_0_3 ^ 1'b1));

assign ap_channel_done_local_C_0_4 = (systolic_tile_modulate_U0_ap_done & (ap_sync_reg_channel_write_local_C_0_4 ^ 1'b1));

assign ap_channel_done_local_C_0_5 = (systolic_tile_modulate_U0_ap_done & (ap_sync_reg_channel_write_local_C_0_5 ^ 1'b1));

assign ap_channel_done_local_C_0_6 = (systolic_tile_modulate_U0_ap_done & (ap_sync_reg_channel_write_local_C_0_6 ^ 1'b1));

assign ap_channel_done_local_C_0_7 = (systolic_tile_modulate_U0_ap_done & (ap_sync_reg_channel_write_local_C_0_7 ^ 1'b1));

assign ap_done = dataflow_in_loop_l_ni_1_Loop_l_store_C_tile_sj_proc_U0_ap_done;

assign ap_idle = (systolic_tile_modulate_U0_ap_idle & (local_C_0_empty_n ^ 1'b1) & (local_C_0_1_empty_n ^ 1'b1) & (local_C_0_2_empty_n ^ 1'b1) & (local_C_0_3_empty_n ^ 1'b1) & (local_C_0_4_empty_n ^ 1'b1) & (local_C_0_5_empty_n ^ 1'b1) & (local_C_0_6_empty_n ^ 1'b1) & (local_C_0_7_empty_n ^ 1'b1) & (local_B_4_t_empty_n ^ 1'b1) & (local_B_1_t_empty_n ^ 1'b1) & (local_B_2_t_empty_n ^ 1'b1) & (local_B_3_t_empty_n ^ 1'b1) & (local_B_3_51_t_empty_n ^ 1'b1) & (local_B_2_50_t_empty_n ^ 1'b1) & (local_B_1_49_t_empty_n ^ 1'b1) & (local_B_t_empty_n ^ 1'b1) & (local_A_0_t_empty_n ^ 1'b1) & dataflow_in_loop_l_ni_1_Loop_l_store_C_tile_sj_proc_U0_ap_idle & dataflow_in_loop_l_ni_1_Loop_l_load_B_tile_bk_proc_U0_ap_idle & dataflow_in_loop_l_ni_1_Loop_l_load_A_tile_ak_proc_U0_ap_idle);

assign ap_ready = ap_sync_ready;

assign ap_sync_channel_write_local_B = ((dataflow_in_loop_l_ni_1_Loop_l_load_B_tile_bk_proc_U0_local_B_full_n & ap_channel_done_local_B) | ap_sync_reg_channel_write_local_B);

assign ap_sync_channel_write_local_B_1 = ((dataflow_in_loop_l_ni_1_Loop_l_load_B_tile_bk_proc_U0_local_B_1_17_full_n & ap_channel_done_local_B_1) | ap_sync_reg_channel_write_local_B_1);

assign ap_sync_channel_write_local_B_1_49 = ((dataflow_in_loop_l_ni_1_Loop_l_load_B_tile_bk_proc_U0_local_B_1_full_n & ap_channel_done_local_B_1_49) | ap_sync_reg_channel_write_local_B_1_49);

assign ap_sync_channel_write_local_B_2 = ((dataflow_in_loop_l_ni_1_Loop_l_load_B_tile_bk_proc_U0_local_B_2_18_full_n & ap_channel_done_local_B_2) | ap_sync_reg_channel_write_local_B_2);

assign ap_sync_channel_write_local_B_2_50 = ((dataflow_in_loop_l_ni_1_Loop_l_load_B_tile_bk_proc_U0_local_B_2_full_n & ap_channel_done_local_B_2_50) | ap_sync_reg_channel_write_local_B_2_50);

assign ap_sync_channel_write_local_B_3 = ((dataflow_in_loop_l_ni_1_Loop_l_load_B_tile_bk_proc_U0_local_B_3_19_full_n & ap_channel_done_local_B_3) | ap_sync_reg_channel_write_local_B_3);

assign ap_sync_channel_write_local_B_3_51 = ((dataflow_in_loop_l_ni_1_Loop_l_load_B_tile_bk_proc_U0_local_B_3_full_n & ap_channel_done_local_B_3_51) | ap_sync_reg_channel_write_local_B_3_51);

assign ap_sync_channel_write_local_B_4 = ((dataflow_in_loop_l_ni_1_Loop_l_load_B_tile_bk_proc_U0_local_B_4_full_n & ap_channel_done_local_B_4) | ap_sync_reg_channel_write_local_B_4);

assign ap_sync_channel_write_local_C_0 = ((local_C_0_full_n & ap_channel_done_local_C_0) | ap_sync_reg_channel_write_local_C_0);

assign ap_sync_channel_write_local_C_0_1 = ((local_C_0_1_full_n & ap_channel_done_local_C_0_1) | ap_sync_reg_channel_write_local_C_0_1);

assign ap_sync_channel_write_local_C_0_2 = ((local_C_0_2_full_n & ap_channel_done_local_C_0_2) | ap_sync_reg_channel_write_local_C_0_2);

assign ap_sync_channel_write_local_C_0_3 = ((local_C_0_3_full_n & ap_channel_done_local_C_0_3) | ap_sync_reg_channel_write_local_C_0_3);

assign ap_sync_channel_write_local_C_0_4 = ((local_C_0_4_full_n & ap_channel_done_local_C_0_4) | ap_sync_reg_channel_write_local_C_0_4);

assign ap_sync_channel_write_local_C_0_5 = ((local_C_0_5_full_n & ap_channel_done_local_C_0_5) | ap_sync_reg_channel_write_local_C_0_5);

assign ap_sync_channel_write_local_C_0_6 = ((local_C_0_6_full_n & ap_channel_done_local_C_0_6) | ap_sync_reg_channel_write_local_C_0_6);

assign ap_sync_channel_write_local_C_0_7 = ((local_C_0_7_full_n & ap_channel_done_local_C_0_7) | ap_sync_reg_channel_write_local_C_0_7);

assign ap_sync_dataflow_in_loop_l_ni_1_Loop_l_load_A_tile_ak_proc_U0_ap_ready = (dataflow_in_loop_l_ni_1_Loop_l_load_A_tile_ak_proc_U0_ap_ready | ap_sync_reg_dataflow_in_loop_l_ni_1_Loop_l_load_A_tile_ak_proc_U0_ap_ready);

assign ap_sync_dataflow_in_loop_l_ni_1_Loop_l_load_B_tile_bk_proc_U0_ap_ready = (dataflow_in_loop_l_ni_1_Loop_l_load_B_tile_bk_proc_U0_ap_ready | ap_sync_reg_dataflow_in_loop_l_ni_1_Loop_l_load_B_tile_bk_proc_U0_ap_ready);

assign ap_sync_ready = (ap_sync_dataflow_in_loop_l_ni_1_Loop_l_load_B_tile_bk_proc_U0_ap_ready & ap_sync_dataflow_in_loop_l_ni_1_Loop_l_load_A_tile_ak_proc_U0_ap_ready);

assign dataflow_in_loop_l_ni_1_Loop_l_load_A_tile_ak_proc_U0_ap_continue = local_A_0_i_full_n;

assign dataflow_in_loop_l_ni_1_Loop_l_load_A_tile_ak_proc_U0_ap_start = ((ap_sync_reg_dataflow_in_loop_l_ni_1_Loop_l_load_A_tile_ak_proc_U0_ap_ready ^ 1'b1) & ap_start);

assign dataflow_in_loop_l_ni_1_Loop_l_load_B_tile_bk_proc_U0_ap_continue = (ap_sync_channel_write_local_B_4 & ap_sync_channel_write_local_B_3_51 & ap_sync_channel_write_local_B_3 & ap_sync_channel_write_local_B_2_50 & ap_sync_channel_write_local_B_2 & ap_sync_channel_write_local_B_1_49 & ap_sync_channel_write_local_B_1 & ap_sync_channel_write_local_B);

assign dataflow_in_loop_l_ni_1_Loop_l_load_B_tile_bk_proc_U0_ap_start = ((ap_sync_reg_dataflow_in_loop_l_ni_1_Loop_l_load_B_tile_bk_proc_U0_ap_ready ^ 1'b1) & ap_start);

assign dataflow_in_loop_l_ni_1_Loop_l_load_B_tile_bk_proc_U0_local_B_1_17_full_n = local_B_1_i_full_n;

assign dataflow_in_loop_l_ni_1_Loop_l_load_B_tile_bk_proc_U0_local_B_1_full_n = local_B_1_49_i_full_n;

assign dataflow_in_loop_l_ni_1_Loop_l_load_B_tile_bk_proc_U0_local_B_2_18_full_n = local_B_2_i_full_n;

assign dataflow_in_loop_l_ni_1_Loop_l_load_B_tile_bk_proc_U0_local_B_2_full_n = local_B_2_50_i_full_n;

assign dataflow_in_loop_l_ni_1_Loop_l_load_B_tile_bk_proc_U0_local_B_3_19_full_n = local_B_3_i_full_n;

assign dataflow_in_loop_l_ni_1_Loop_l_load_B_tile_bk_proc_U0_local_B_3_full_n = local_B_3_51_i_full_n;

assign dataflow_in_loop_l_ni_1_Loop_l_load_B_tile_bk_proc_U0_local_B_4_full_n = local_B_4_i_full_n;

assign dataflow_in_loop_l_ni_1_Loop_l_load_B_tile_bk_proc_U0_local_B_full_n = local_B_i_full_n;

assign dataflow_in_loop_l_ni_1_Loop_l_store_C_tile_sj_proc_U0_ap_continue = ap_continue;

assign dataflow_in_loop_l_ni_1_Loop_l_store_C_tile_sj_proc_U0_ap_start = (local_C_0_empty_n & local_C_0_7_empty_n & local_C_0_6_empty_n & local_C_0_5_empty_n & local_C_0_4_empty_n & local_C_0_3_empty_n & local_C_0_2_empty_n & local_C_0_1_empty_n);

assign systolic_tile_modulate_U0_ap_continue = (ap_sync_channel_write_local_C_0_7 & ap_sync_channel_write_local_C_0_6 & ap_sync_channel_write_local_C_0_5 & ap_sync_channel_write_local_C_0_4 & ap_sync_channel_write_local_C_0_3 & ap_sync_channel_write_local_C_0_2 & ap_sync_channel_write_local_C_0_1 & ap_sync_channel_write_local_C_0);

assign systolic_tile_modulate_U0_ap_start = (local_B_t_empty_n & local_B_4_t_empty_n & local_B_3_t_empty_n & local_B_3_51_t_empty_n & local_B_2_t_empty_n & local_B_2_50_t_empty_n & local_B_1_t_empty_n & local_B_1_49_t_empty_n & local_A_0_t_empty_n);

assign v217_address0 = dataflow_in_loop_l_ni_1_Loop_l_load_A_tile_ak_proc_U0_v217_address0;

assign v217_address1 = 3'd0;

assign v217_ce0 = dataflow_in_loop_l_ni_1_Loop_l_load_A_tile_ak_proc_U0_v217_ce0;

assign v217_ce1 = 1'b0;

assign v217_d0 = 32'd0;

assign v217_d1 = 32'd0;

assign v217_we0 = 1'b0;

assign v217_we1 = 1'b0;

assign v218_address0 = dataflow_in_loop_l_ni_1_Loop_l_load_B_tile_bk_proc_U0_v218_address0;

assign v218_address1 = 11'd0;

assign v218_ce0 = dataflow_in_loop_l_ni_1_Loop_l_load_B_tile_bk_proc_U0_v218_ce0;

assign v218_ce1 = 1'b0;

assign v218_d0 = 32'd0;

assign v218_d1 = 32'd0;

assign v218_we0 = 1'b0;

assign v218_we1 = 1'b0;

assign v219_address0 = dataflow_in_loop_l_ni_1_Loop_l_store_C_tile_sj_proc_U0_v219_address0;

assign v219_address1 = 8'd0;

assign v219_ce0 = dataflow_in_loop_l_ni_1_Loop_l_store_C_tile_sj_proc_U0_v219_ce0;

assign v219_ce1 = 1'b0;

assign v219_d0 = dataflow_in_loop_l_ni_1_Loop_l_store_C_tile_sj_proc_U0_v219_d0;

assign v219_d1 = 32'd0;

assign v219_we0 = dataflow_in_loop_l_ni_1_Loop_l_store_C_tile_sj_proc_U0_v219_we0;

assign v219_we1 = 1'b0;

endmodule //systolic_modulate_dataflow_in_loop_l_ni_1
