-- ==============================================================
-- Generated by Vitis HLS v2023.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity systolic_modulate_dataflow_in_loop_l_ni_1 is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    indvars_iv26 : IN STD_LOGIC_VECTOR (4 downto 0);
    v219_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    v219_ce0 : OUT STD_LOGIC;
    v219_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    v219_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    v219_we0 : OUT STD_LOGIC;
    v219_address1 : OUT STD_LOGIC_VECTOR (7 downto 0);
    v219_ce1 : OUT STD_LOGIC;
    v219_d1 : OUT STD_LOGIC_VECTOR (31 downto 0);
    v219_q1 : IN STD_LOGIC_VECTOR (31 downto 0);
    v219_we1 : OUT STD_LOGIC;
    v218_address0 : OUT STD_LOGIC_VECTOR (10 downto 0);
    v218_ce0 : OUT STD_LOGIC;
    v218_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    v218_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    v218_we0 : OUT STD_LOGIC;
    v218_address1 : OUT STD_LOGIC_VECTOR (10 downto 0);
    v218_ce1 : OUT STD_LOGIC;
    v218_d1 : OUT STD_LOGIC_VECTOR (31 downto 0);
    v218_q1 : IN STD_LOGIC_VECTOR (31 downto 0);
    v218_we1 : OUT STD_LOGIC;
    v217_address0 : OUT STD_LOGIC_VECTOR (2 downto 0);
    v217_ce0 : OUT STD_LOGIC;
    v217_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    v217_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    v217_we0 : OUT STD_LOGIC;
    v217_address1 : OUT STD_LOGIC_VECTOR (2 downto 0);
    v217_ce1 : OUT STD_LOGIC;
    v217_d1 : OUT STD_LOGIC_VECTOR (31 downto 0);
    v217_q1 : IN STD_LOGIC_VECTOR (31 downto 0);
    v217_we1 : OUT STD_LOGIC;
    indvars_iv26_ap_vld : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_continue : IN STD_LOGIC );
end;


architecture behav of systolic_modulate_dataflow_in_loop_l_ni_1 is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_lv8_0 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv11_0 : STD_LOGIC_VECTOR (10 downto 0) := "00000000000";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_boolean_1 : BOOLEAN := true;

attribute shreg_extract : string;
    signal local_B_i_q0 : STD_LOGIC_VECTOR (31 downto 0);
    signal local_B_t_q0 : STD_LOGIC_VECTOR (31 downto 0);
    signal local_B_1_49_i_q0 : STD_LOGIC_VECTOR (31 downto 0);
    signal local_B_1_49_t_q0 : STD_LOGIC_VECTOR (31 downto 0);
    signal local_B_2_50_i_q0 : STD_LOGIC_VECTOR (31 downto 0);
    signal local_B_2_50_t_q0 : STD_LOGIC_VECTOR (31 downto 0);
    signal local_B_3_51_i_q0 : STD_LOGIC_VECTOR (31 downto 0);
    signal local_B_3_51_t_q0 : STD_LOGIC_VECTOR (31 downto 0);
    signal local_B_3_i_q0 : STD_LOGIC_VECTOR (31 downto 0);
    signal local_B_3_t_q0 : STD_LOGIC_VECTOR (31 downto 0);
    signal local_B_2_i_q0 : STD_LOGIC_VECTOR (31 downto 0);
    signal local_B_2_t_q0 : STD_LOGIC_VECTOR (31 downto 0);
    signal local_B_1_i_q0 : STD_LOGIC_VECTOR (31 downto 0);
    signal local_B_1_t_q0 : STD_LOGIC_VECTOR (31 downto 0);
    signal local_B_4_i_q0 : STD_LOGIC_VECTOR (31 downto 0);
    signal local_B_4_t_q0 : STD_LOGIC_VECTOR (31 downto 0);
    signal local_A_0_i_q0 : STD_LOGIC_VECTOR (31 downto 0);
    signal local_A_0_t_q0 : STD_LOGIC_VECTOR (31 downto 0);
    signal dataflow_in_loop_l_ni_1_Loop_l_load_A_tile_ak_proc_U0_ap_start : STD_LOGIC;
    signal dataflow_in_loop_l_ni_1_Loop_l_load_A_tile_ak_proc_U0_ap_done : STD_LOGIC;
    signal dataflow_in_loop_l_ni_1_Loop_l_load_A_tile_ak_proc_U0_ap_continue : STD_LOGIC;
    signal dataflow_in_loop_l_ni_1_Loop_l_load_A_tile_ak_proc_U0_ap_idle : STD_LOGIC;
    signal dataflow_in_loop_l_ni_1_Loop_l_load_A_tile_ak_proc_U0_ap_ready : STD_LOGIC;
    signal dataflow_in_loop_l_ni_1_Loop_l_load_A_tile_ak_proc_U0_v217_address0 : STD_LOGIC_VECTOR (2 downto 0);
    signal dataflow_in_loop_l_ni_1_Loop_l_load_A_tile_ak_proc_U0_v217_ce0 : STD_LOGIC;
    signal dataflow_in_loop_l_ni_1_Loop_l_load_A_tile_ak_proc_U0_local_A_0_address0 : STD_LOGIC_VECTOR (2 downto 0);
    signal dataflow_in_loop_l_ni_1_Loop_l_load_A_tile_ak_proc_U0_local_A_0_ce0 : STD_LOGIC;
    signal dataflow_in_loop_l_ni_1_Loop_l_load_A_tile_ak_proc_U0_local_A_0_we0 : STD_LOGIC;
    signal dataflow_in_loop_l_ni_1_Loop_l_load_A_tile_ak_proc_U0_local_A_0_d0 : STD_LOGIC_VECTOR (31 downto 0);
    signal dataflow_in_loop_l_ni_1_Loop_l_load_A_tile_ak_proc_U0_indvars_iv26_c_din : STD_LOGIC_VECTOR (4 downto 0);
    signal dataflow_in_loop_l_ni_1_Loop_l_load_A_tile_ak_proc_U0_indvars_iv26_c_write : STD_LOGIC;
    signal dataflow_in_loop_l_ni_1_Loop_l_load_B_tile_bk_proc_U0_ap_start : STD_LOGIC;
    signal dataflow_in_loop_l_ni_1_Loop_l_load_B_tile_bk_proc_U0_ap_done : STD_LOGIC;
    signal dataflow_in_loop_l_ni_1_Loop_l_load_B_tile_bk_proc_U0_ap_continue : STD_LOGIC;
    signal dataflow_in_loop_l_ni_1_Loop_l_load_B_tile_bk_proc_U0_ap_idle : STD_LOGIC;
    signal dataflow_in_loop_l_ni_1_Loop_l_load_B_tile_bk_proc_U0_ap_ready : STD_LOGIC;
    signal dataflow_in_loop_l_ni_1_Loop_l_load_B_tile_bk_proc_U0_local_B_address0 : STD_LOGIC_VECTOR (2 downto 0);
    signal dataflow_in_loop_l_ni_1_Loop_l_load_B_tile_bk_proc_U0_local_B_ce0 : STD_LOGIC;
    signal dataflow_in_loop_l_ni_1_Loop_l_load_B_tile_bk_proc_U0_local_B_we0 : STD_LOGIC;
    signal dataflow_in_loop_l_ni_1_Loop_l_load_B_tile_bk_proc_U0_local_B_d0 : STD_LOGIC_VECTOR (31 downto 0);
    signal dataflow_in_loop_l_ni_1_Loop_l_load_B_tile_bk_proc_U0_local_B_1_address0 : STD_LOGIC_VECTOR (2 downto 0);
    signal dataflow_in_loop_l_ni_1_Loop_l_load_B_tile_bk_proc_U0_local_B_1_ce0 : STD_LOGIC;
    signal dataflow_in_loop_l_ni_1_Loop_l_load_B_tile_bk_proc_U0_local_B_1_we0 : STD_LOGIC;
    signal dataflow_in_loop_l_ni_1_Loop_l_load_B_tile_bk_proc_U0_local_B_1_d0 : STD_LOGIC_VECTOR (31 downto 0);
    signal dataflow_in_loop_l_ni_1_Loop_l_load_B_tile_bk_proc_U0_local_B_2_address0 : STD_LOGIC_VECTOR (2 downto 0);
    signal dataflow_in_loop_l_ni_1_Loop_l_load_B_tile_bk_proc_U0_local_B_2_ce0 : STD_LOGIC;
    signal dataflow_in_loop_l_ni_1_Loop_l_load_B_tile_bk_proc_U0_local_B_2_we0 : STD_LOGIC;
    signal dataflow_in_loop_l_ni_1_Loop_l_load_B_tile_bk_proc_U0_local_B_2_d0 : STD_LOGIC_VECTOR (31 downto 0);
    signal dataflow_in_loop_l_ni_1_Loop_l_load_B_tile_bk_proc_U0_local_B_3_address0 : STD_LOGIC_VECTOR (2 downto 0);
    signal dataflow_in_loop_l_ni_1_Loop_l_load_B_tile_bk_proc_U0_local_B_3_ce0 : STD_LOGIC;
    signal dataflow_in_loop_l_ni_1_Loop_l_load_B_tile_bk_proc_U0_local_B_3_we0 : STD_LOGIC;
    signal dataflow_in_loop_l_ni_1_Loop_l_load_B_tile_bk_proc_U0_local_B_3_d0 : STD_LOGIC_VECTOR (31 downto 0);
    signal dataflow_in_loop_l_ni_1_Loop_l_load_B_tile_bk_proc_U0_local_B_3_19_address0 : STD_LOGIC_VECTOR (2 downto 0);
    signal dataflow_in_loop_l_ni_1_Loop_l_load_B_tile_bk_proc_U0_local_B_3_19_ce0 : STD_LOGIC;
    signal dataflow_in_loop_l_ni_1_Loop_l_load_B_tile_bk_proc_U0_local_B_3_19_we0 : STD_LOGIC;
    signal dataflow_in_loop_l_ni_1_Loop_l_load_B_tile_bk_proc_U0_local_B_3_19_d0 : STD_LOGIC_VECTOR (31 downto 0);
    signal dataflow_in_loop_l_ni_1_Loop_l_load_B_tile_bk_proc_U0_local_B_2_18_address0 : STD_LOGIC_VECTOR (2 downto 0);
    signal dataflow_in_loop_l_ni_1_Loop_l_load_B_tile_bk_proc_U0_local_B_2_18_ce0 : STD_LOGIC;
    signal dataflow_in_loop_l_ni_1_Loop_l_load_B_tile_bk_proc_U0_local_B_2_18_we0 : STD_LOGIC;
    signal dataflow_in_loop_l_ni_1_Loop_l_load_B_tile_bk_proc_U0_local_B_2_18_d0 : STD_LOGIC_VECTOR (31 downto 0);
    signal dataflow_in_loop_l_ni_1_Loop_l_load_B_tile_bk_proc_U0_local_B_1_17_address0 : STD_LOGIC_VECTOR (2 downto 0);
    signal dataflow_in_loop_l_ni_1_Loop_l_load_B_tile_bk_proc_U0_local_B_1_17_ce0 : STD_LOGIC;
    signal dataflow_in_loop_l_ni_1_Loop_l_load_B_tile_bk_proc_U0_local_B_1_17_we0 : STD_LOGIC;
    signal dataflow_in_loop_l_ni_1_Loop_l_load_B_tile_bk_proc_U0_local_B_1_17_d0 : STD_LOGIC_VECTOR (31 downto 0);
    signal dataflow_in_loop_l_ni_1_Loop_l_load_B_tile_bk_proc_U0_local_B_4_address0 : STD_LOGIC_VECTOR (2 downto 0);
    signal dataflow_in_loop_l_ni_1_Loop_l_load_B_tile_bk_proc_U0_local_B_4_ce0 : STD_LOGIC;
    signal dataflow_in_loop_l_ni_1_Loop_l_load_B_tile_bk_proc_U0_local_B_4_we0 : STD_LOGIC;
    signal dataflow_in_loop_l_ni_1_Loop_l_load_B_tile_bk_proc_U0_local_B_4_d0 : STD_LOGIC_VECTOR (31 downto 0);
    signal dataflow_in_loop_l_ni_1_Loop_l_load_B_tile_bk_proc_U0_v218_address0 : STD_LOGIC_VECTOR (10 downto 0);
    signal dataflow_in_loop_l_ni_1_Loop_l_load_B_tile_bk_proc_U0_v218_ce0 : STD_LOGIC;
    signal ap_channel_done_local_B_4 : STD_LOGIC;
    signal dataflow_in_loop_l_ni_1_Loop_l_load_B_tile_bk_proc_U0_local_B_4_full_n : STD_LOGIC;
    signal ap_sync_reg_channel_write_local_B_4 : STD_LOGIC := '0';
    signal ap_sync_channel_write_local_B_4 : STD_LOGIC;
    signal ap_channel_done_local_B_1 : STD_LOGIC;
    signal dataflow_in_loop_l_ni_1_Loop_l_load_B_tile_bk_proc_U0_local_B_1_17_full_n : STD_LOGIC;
    signal ap_sync_reg_channel_write_local_B_1 : STD_LOGIC := '0';
    signal ap_sync_channel_write_local_B_1 : STD_LOGIC;
    signal ap_channel_done_local_B_2 : STD_LOGIC;
    signal dataflow_in_loop_l_ni_1_Loop_l_load_B_tile_bk_proc_U0_local_B_2_18_full_n : STD_LOGIC;
    signal ap_sync_reg_channel_write_local_B_2 : STD_LOGIC := '0';
    signal ap_sync_channel_write_local_B_2 : STD_LOGIC;
    signal ap_channel_done_local_B_3 : STD_LOGIC;
    signal dataflow_in_loop_l_ni_1_Loop_l_load_B_tile_bk_proc_U0_local_B_3_19_full_n : STD_LOGIC;
    signal ap_sync_reg_channel_write_local_B_3 : STD_LOGIC := '0';
    signal ap_sync_channel_write_local_B_3 : STD_LOGIC;
    signal ap_channel_done_local_B_3_51 : STD_LOGIC;
    signal dataflow_in_loop_l_ni_1_Loop_l_load_B_tile_bk_proc_U0_local_B_3_full_n : STD_LOGIC;
    signal ap_sync_reg_channel_write_local_B_3_51 : STD_LOGIC := '0';
    signal ap_sync_channel_write_local_B_3_51 : STD_LOGIC;
    signal ap_channel_done_local_B_2_50 : STD_LOGIC;
    signal dataflow_in_loop_l_ni_1_Loop_l_load_B_tile_bk_proc_U0_local_B_2_full_n : STD_LOGIC;
    signal ap_sync_reg_channel_write_local_B_2_50 : STD_LOGIC := '0';
    signal ap_sync_channel_write_local_B_2_50 : STD_LOGIC;
    signal ap_channel_done_local_B_1_49 : STD_LOGIC;
    signal dataflow_in_loop_l_ni_1_Loop_l_load_B_tile_bk_proc_U0_local_B_1_full_n : STD_LOGIC;
    signal ap_sync_reg_channel_write_local_B_1_49 : STD_LOGIC := '0';
    signal ap_sync_channel_write_local_B_1_49 : STD_LOGIC;
    signal ap_channel_done_local_B : STD_LOGIC;
    signal dataflow_in_loop_l_ni_1_Loop_l_load_B_tile_bk_proc_U0_local_B_full_n : STD_LOGIC;
    signal ap_sync_reg_channel_write_local_B : STD_LOGIC := '0';
    signal ap_sync_channel_write_local_B : STD_LOGIC;
    signal systolic_tile_modulate_U0_v168_0_address0 : STD_LOGIC_VECTOR (2 downto 0);
    signal systolic_tile_modulate_U0_v168_0_ce0 : STD_LOGIC;
    signal systolic_tile_modulate_U0_v168_0_d0 : STD_LOGIC_VECTOR (31 downto 0);
    signal systolic_tile_modulate_U0_v168_0_we0 : STD_LOGIC;
    signal systolic_tile_modulate_U0_v168_0_address1 : STD_LOGIC_VECTOR (2 downto 0);
    signal systolic_tile_modulate_U0_v168_0_ce1 : STD_LOGIC;
    signal systolic_tile_modulate_U0_v168_0_d1 : STD_LOGIC_VECTOR (31 downto 0);
    signal systolic_tile_modulate_U0_v168_0_we1 : STD_LOGIC;
    signal systolic_tile_modulate_U0_v169_0_address0 : STD_LOGIC_VECTOR (2 downto 0);
    signal systolic_tile_modulate_U0_v169_0_ce0 : STD_LOGIC;
    signal systolic_tile_modulate_U0_v169_0_d0 : STD_LOGIC_VECTOR (31 downto 0);
    signal systolic_tile_modulate_U0_v169_0_we0 : STD_LOGIC;
    signal systolic_tile_modulate_U0_v169_0_address1 : STD_LOGIC_VECTOR (2 downto 0);
    signal systolic_tile_modulate_U0_v169_0_ce1 : STD_LOGIC;
    signal systolic_tile_modulate_U0_v169_0_d1 : STD_LOGIC_VECTOR (31 downto 0);
    signal systolic_tile_modulate_U0_v169_0_we1 : STD_LOGIC;
    signal systolic_tile_modulate_U0_v169_1_address0 : STD_LOGIC_VECTOR (2 downto 0);
    signal systolic_tile_modulate_U0_v169_1_ce0 : STD_LOGIC;
    signal systolic_tile_modulate_U0_v169_1_d0 : STD_LOGIC_VECTOR (31 downto 0);
    signal systolic_tile_modulate_U0_v169_1_we0 : STD_LOGIC;
    signal systolic_tile_modulate_U0_v169_1_address1 : STD_LOGIC_VECTOR (2 downto 0);
    signal systolic_tile_modulate_U0_v169_1_ce1 : STD_LOGIC;
    signal systolic_tile_modulate_U0_v169_1_d1 : STD_LOGIC_VECTOR (31 downto 0);
    signal systolic_tile_modulate_U0_v169_1_we1 : STD_LOGIC;
    signal systolic_tile_modulate_U0_v169_2_address0 : STD_LOGIC_VECTOR (2 downto 0);
    signal systolic_tile_modulate_U0_v169_2_ce0 : STD_LOGIC;
    signal systolic_tile_modulate_U0_v169_2_d0 : STD_LOGIC_VECTOR (31 downto 0);
    signal systolic_tile_modulate_U0_v169_2_we0 : STD_LOGIC;
    signal systolic_tile_modulate_U0_v169_2_address1 : STD_LOGIC_VECTOR (2 downto 0);
    signal systolic_tile_modulate_U0_v169_2_ce1 : STD_LOGIC;
    signal systolic_tile_modulate_U0_v169_2_d1 : STD_LOGIC_VECTOR (31 downto 0);
    signal systolic_tile_modulate_U0_v169_2_we1 : STD_LOGIC;
    signal systolic_tile_modulate_U0_v169_3_address0 : STD_LOGIC_VECTOR (2 downto 0);
    signal systolic_tile_modulate_U0_v169_3_ce0 : STD_LOGIC;
    signal systolic_tile_modulate_U0_v169_3_d0 : STD_LOGIC_VECTOR (31 downto 0);
    signal systolic_tile_modulate_U0_v169_3_we0 : STD_LOGIC;
    signal systolic_tile_modulate_U0_v169_3_address1 : STD_LOGIC_VECTOR (2 downto 0);
    signal systolic_tile_modulate_U0_v169_3_ce1 : STD_LOGIC;
    signal systolic_tile_modulate_U0_v169_3_d1 : STD_LOGIC_VECTOR (31 downto 0);
    signal systolic_tile_modulate_U0_v169_3_we1 : STD_LOGIC;
    signal systolic_tile_modulate_U0_v169_4_address0 : STD_LOGIC_VECTOR (2 downto 0);
    signal systolic_tile_modulate_U0_v169_4_ce0 : STD_LOGIC;
    signal systolic_tile_modulate_U0_v169_4_d0 : STD_LOGIC_VECTOR (31 downto 0);
    signal systolic_tile_modulate_U0_v169_4_we0 : STD_LOGIC;
    signal systolic_tile_modulate_U0_v169_4_address1 : STD_LOGIC_VECTOR (2 downto 0);
    signal systolic_tile_modulate_U0_v169_4_ce1 : STD_LOGIC;
    signal systolic_tile_modulate_U0_v169_4_d1 : STD_LOGIC_VECTOR (31 downto 0);
    signal systolic_tile_modulate_U0_v169_4_we1 : STD_LOGIC;
    signal systolic_tile_modulate_U0_v169_5_address0 : STD_LOGIC_VECTOR (2 downto 0);
    signal systolic_tile_modulate_U0_v169_5_ce0 : STD_LOGIC;
    signal systolic_tile_modulate_U0_v169_5_d0 : STD_LOGIC_VECTOR (31 downto 0);
    signal systolic_tile_modulate_U0_v169_5_we0 : STD_LOGIC;
    signal systolic_tile_modulate_U0_v169_5_address1 : STD_LOGIC_VECTOR (2 downto 0);
    signal systolic_tile_modulate_U0_v169_5_ce1 : STD_LOGIC;
    signal systolic_tile_modulate_U0_v169_5_d1 : STD_LOGIC_VECTOR (31 downto 0);
    signal systolic_tile_modulate_U0_v169_5_we1 : STD_LOGIC;
    signal systolic_tile_modulate_U0_v169_6_address0 : STD_LOGIC_VECTOR (2 downto 0);
    signal systolic_tile_modulate_U0_v169_6_ce0 : STD_LOGIC;
    signal systolic_tile_modulate_U0_v169_6_d0 : STD_LOGIC_VECTOR (31 downto 0);
    signal systolic_tile_modulate_U0_v169_6_we0 : STD_LOGIC;
    signal systolic_tile_modulate_U0_v169_6_address1 : STD_LOGIC_VECTOR (2 downto 0);
    signal systolic_tile_modulate_U0_v169_6_ce1 : STD_LOGIC;
    signal systolic_tile_modulate_U0_v169_6_d1 : STD_LOGIC_VECTOR (31 downto 0);
    signal systolic_tile_modulate_U0_v169_6_we1 : STD_LOGIC;
    signal systolic_tile_modulate_U0_v169_7_address0 : STD_LOGIC_VECTOR (2 downto 0);
    signal systolic_tile_modulate_U0_v169_7_ce0 : STD_LOGIC;
    signal systolic_tile_modulate_U0_v169_7_d0 : STD_LOGIC_VECTOR (31 downto 0);
    signal systolic_tile_modulate_U0_v169_7_we0 : STD_LOGIC;
    signal systolic_tile_modulate_U0_v169_7_address1 : STD_LOGIC_VECTOR (2 downto 0);
    signal systolic_tile_modulate_U0_v169_7_ce1 : STD_LOGIC;
    signal systolic_tile_modulate_U0_v169_7_d1 : STD_LOGIC_VECTOR (31 downto 0);
    signal systolic_tile_modulate_U0_v169_7_we1 : STD_LOGIC;
    signal systolic_tile_modulate_U0_v170_0_0 : STD_LOGIC_VECTOR (31 downto 0);
    signal systolic_tile_modulate_U0_v170_1_0 : STD_LOGIC_VECTOR (31 downto 0);
    signal systolic_tile_modulate_U0_v170_2_0 : STD_LOGIC_VECTOR (31 downto 0);
    signal systolic_tile_modulate_U0_v170_3_0 : STD_LOGIC_VECTOR (31 downto 0);
    signal systolic_tile_modulate_U0_v170_4_0 : STD_LOGIC_VECTOR (31 downto 0);
    signal systolic_tile_modulate_U0_v170_5_0 : STD_LOGIC_VECTOR (31 downto 0);
    signal systolic_tile_modulate_U0_v170_6_0 : STD_LOGIC_VECTOR (31 downto 0);
    signal systolic_tile_modulate_U0_v170_7_0 : STD_LOGIC_VECTOR (31 downto 0);
    signal systolic_tile_modulate_U0_v168_0_read : STD_LOGIC;
    signal systolic_tile_modulate_U0_v169_0_read : STD_LOGIC;
    signal systolic_tile_modulate_U0_v169_1_read : STD_LOGIC;
    signal systolic_tile_modulate_U0_v169_2_read : STD_LOGIC;
    signal systolic_tile_modulate_U0_v169_3_read : STD_LOGIC;
    signal systolic_tile_modulate_U0_v169_4_read : STD_LOGIC;
    signal systolic_tile_modulate_U0_v169_5_read : STD_LOGIC;
    signal systolic_tile_modulate_U0_v169_6_read : STD_LOGIC;
    signal systolic_tile_modulate_U0_v169_7_read : STD_LOGIC;
    signal systolic_tile_modulate_U0_ap_start : STD_LOGIC;
    signal systolic_tile_modulate_U0_v170_0_0_ap_vld : STD_LOGIC;
    signal systolic_tile_modulate_U0_ap_done : STD_LOGIC;
    signal systolic_tile_modulate_U0_v170_1_0_ap_vld : STD_LOGIC;
    signal systolic_tile_modulate_U0_v170_2_0_ap_vld : STD_LOGIC;
    signal systolic_tile_modulate_U0_v170_3_0_ap_vld : STD_LOGIC;
    signal systolic_tile_modulate_U0_v170_4_0_ap_vld : STD_LOGIC;
    signal systolic_tile_modulate_U0_v170_5_0_ap_vld : STD_LOGIC;
    signal systolic_tile_modulate_U0_v170_6_0_ap_vld : STD_LOGIC;
    signal systolic_tile_modulate_U0_v170_7_0_ap_vld : STD_LOGIC;
    signal systolic_tile_modulate_U0_ap_ready : STD_LOGIC;
    signal systolic_tile_modulate_U0_ap_idle : STD_LOGIC;
    signal systolic_tile_modulate_U0_ap_continue : STD_LOGIC;
    signal ap_channel_done_local_C_0 : STD_LOGIC;
    signal local_C_0_full_n : STD_LOGIC;
    signal ap_sync_reg_channel_write_local_C_0 : STD_LOGIC := '0';
    signal ap_sync_channel_write_local_C_0 : STD_LOGIC;
    signal ap_channel_done_local_C_0_1 : STD_LOGIC;
    signal local_C_0_1_full_n : STD_LOGIC;
    signal ap_sync_reg_channel_write_local_C_0_1 : STD_LOGIC := '0';
    signal ap_sync_channel_write_local_C_0_1 : STD_LOGIC;
    signal ap_channel_done_local_C_0_2 : STD_LOGIC;
    signal local_C_0_2_full_n : STD_LOGIC;
    signal ap_sync_reg_channel_write_local_C_0_2 : STD_LOGIC := '0';
    signal ap_sync_channel_write_local_C_0_2 : STD_LOGIC;
    signal ap_channel_done_local_C_0_3 : STD_LOGIC;
    signal local_C_0_3_full_n : STD_LOGIC;
    signal ap_sync_reg_channel_write_local_C_0_3 : STD_LOGIC := '0';
    signal ap_sync_channel_write_local_C_0_3 : STD_LOGIC;
    signal ap_channel_done_local_C_0_4 : STD_LOGIC;
    signal local_C_0_4_full_n : STD_LOGIC;
    signal ap_sync_reg_channel_write_local_C_0_4 : STD_LOGIC := '0';
    signal ap_sync_channel_write_local_C_0_4 : STD_LOGIC;
    signal ap_channel_done_local_C_0_5 : STD_LOGIC;
    signal local_C_0_5_full_n : STD_LOGIC;
    signal ap_sync_reg_channel_write_local_C_0_5 : STD_LOGIC := '0';
    signal ap_sync_channel_write_local_C_0_5 : STD_LOGIC;
    signal ap_channel_done_local_C_0_6 : STD_LOGIC;
    signal local_C_0_6_full_n : STD_LOGIC;
    signal ap_sync_reg_channel_write_local_C_0_6 : STD_LOGIC := '0';
    signal ap_sync_channel_write_local_C_0_6 : STD_LOGIC;
    signal ap_channel_done_local_C_0_7 : STD_LOGIC;
    signal local_C_0_7_full_n : STD_LOGIC;
    signal ap_sync_reg_channel_write_local_C_0_7 : STD_LOGIC := '0';
    signal ap_sync_channel_write_local_C_0_7 : STD_LOGIC;
    signal dataflow_in_loop_l_ni_1_Loop_l_store_C_tile_sj_proc_U0_ap_start : STD_LOGIC;
    signal dataflow_in_loop_l_ni_1_Loop_l_store_C_tile_sj_proc_U0_ap_done : STD_LOGIC;
    signal dataflow_in_loop_l_ni_1_Loop_l_store_C_tile_sj_proc_U0_ap_continue : STD_LOGIC;
    signal dataflow_in_loop_l_ni_1_Loop_l_store_C_tile_sj_proc_U0_ap_idle : STD_LOGIC;
    signal dataflow_in_loop_l_ni_1_Loop_l_store_C_tile_sj_proc_U0_ap_ready : STD_LOGIC;
    signal dataflow_in_loop_l_ni_1_Loop_l_store_C_tile_sj_proc_U0_indvars_iv26_read : STD_LOGIC;
    signal dataflow_in_loop_l_ni_1_Loop_l_store_C_tile_sj_proc_U0_v219_address0 : STD_LOGIC_VECTOR (7 downto 0);
    signal dataflow_in_loop_l_ni_1_Loop_l_store_C_tile_sj_proc_U0_v219_ce0 : STD_LOGIC;
    signal dataflow_in_loop_l_ni_1_Loop_l_store_C_tile_sj_proc_U0_v219_we0 : STD_LOGIC;
    signal dataflow_in_loop_l_ni_1_Loop_l_store_C_tile_sj_proc_U0_v219_d0 : STD_LOGIC_VECTOR (31 downto 0);
    signal local_A_0_i_full_n : STD_LOGIC;
    signal local_A_0_t_empty_n : STD_LOGIC;
    signal local_B_i_full_n : STD_LOGIC;
    signal local_B_t_empty_n : STD_LOGIC;
    signal local_B_1_49_i_full_n : STD_LOGIC;
    signal local_B_1_49_t_empty_n : STD_LOGIC;
    signal local_B_2_50_i_full_n : STD_LOGIC;
    signal local_B_2_50_t_empty_n : STD_LOGIC;
    signal local_B_3_51_i_full_n : STD_LOGIC;
    signal local_B_3_51_t_empty_n : STD_LOGIC;
    signal local_B_3_i_full_n : STD_LOGIC;
    signal local_B_3_t_empty_n : STD_LOGIC;
    signal local_B_2_i_full_n : STD_LOGIC;
    signal local_B_2_t_empty_n : STD_LOGIC;
    signal local_B_1_i_full_n : STD_LOGIC;
    signal local_B_1_t_empty_n : STD_LOGIC;
    signal local_B_4_i_full_n : STD_LOGIC;
    signal local_B_4_t_empty_n : STD_LOGIC;
    signal indvars_iv26_c_full_n : STD_LOGIC;
    signal indvars_iv26_c_dout : STD_LOGIC_VECTOR (4 downto 0);
    signal indvars_iv26_c_num_data_valid : STD_LOGIC_VECTOR (2 downto 0);
    signal indvars_iv26_c_fifo_cap : STD_LOGIC_VECTOR (2 downto 0);
    signal indvars_iv26_c_empty_n : STD_LOGIC;
    signal local_C_0_7_dout : STD_LOGIC_VECTOR (31 downto 0);
    signal local_C_0_7_num_data_valid : STD_LOGIC_VECTOR (2 downto 0);
    signal local_C_0_7_fifo_cap : STD_LOGIC_VECTOR (2 downto 0);
    signal local_C_0_7_empty_n : STD_LOGIC;
    signal local_C_0_6_dout : STD_LOGIC_VECTOR (31 downto 0);
    signal local_C_0_6_num_data_valid : STD_LOGIC_VECTOR (2 downto 0);
    signal local_C_0_6_fifo_cap : STD_LOGIC_VECTOR (2 downto 0);
    signal local_C_0_6_empty_n : STD_LOGIC;
    signal local_C_0_5_dout : STD_LOGIC_VECTOR (31 downto 0);
    signal local_C_0_5_num_data_valid : STD_LOGIC_VECTOR (2 downto 0);
    signal local_C_0_5_fifo_cap : STD_LOGIC_VECTOR (2 downto 0);
    signal local_C_0_5_empty_n : STD_LOGIC;
    signal local_C_0_4_dout : STD_LOGIC_VECTOR (31 downto 0);
    signal local_C_0_4_num_data_valid : STD_LOGIC_VECTOR (2 downto 0);
    signal local_C_0_4_fifo_cap : STD_LOGIC_VECTOR (2 downto 0);
    signal local_C_0_4_empty_n : STD_LOGIC;
    signal local_C_0_3_dout : STD_LOGIC_VECTOR (31 downto 0);
    signal local_C_0_3_num_data_valid : STD_LOGIC_VECTOR (2 downto 0);
    signal local_C_0_3_fifo_cap : STD_LOGIC_VECTOR (2 downto 0);
    signal local_C_0_3_empty_n : STD_LOGIC;
    signal local_C_0_2_dout : STD_LOGIC_VECTOR (31 downto 0);
    signal local_C_0_2_num_data_valid : STD_LOGIC_VECTOR (2 downto 0);
    signal local_C_0_2_fifo_cap : STD_LOGIC_VECTOR (2 downto 0);
    signal local_C_0_2_empty_n : STD_LOGIC;
    signal local_C_0_1_dout : STD_LOGIC_VECTOR (31 downto 0);
    signal local_C_0_1_num_data_valid : STD_LOGIC_VECTOR (2 downto 0);
    signal local_C_0_1_fifo_cap : STD_LOGIC_VECTOR (2 downto 0);
    signal local_C_0_1_empty_n : STD_LOGIC;
    signal local_C_0_dout : STD_LOGIC_VECTOR (31 downto 0);
    signal local_C_0_num_data_valid : STD_LOGIC_VECTOR (2 downto 0);
    signal local_C_0_fifo_cap : STD_LOGIC_VECTOR (2 downto 0);
    signal local_C_0_empty_n : STD_LOGIC;
    signal ap_sync_ready : STD_LOGIC;
    signal ap_sync_reg_dataflow_in_loop_l_ni_1_Loop_l_load_A_tile_ak_proc_U0_ap_ready : STD_LOGIC := '0';
    signal ap_sync_dataflow_in_loop_l_ni_1_Loop_l_load_A_tile_ak_proc_U0_ap_ready : STD_LOGIC;
    signal ap_sync_reg_dataflow_in_loop_l_ni_1_Loop_l_load_B_tile_bk_proc_U0_ap_ready : STD_LOGIC := '0';
    signal ap_sync_dataflow_in_loop_l_ni_1_Loop_l_load_B_tile_bk_proc_U0_ap_ready : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component systolic_modulate_dataflow_in_loop_l_ni_1_Loop_l_load_A_tile_ak_proc IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_continue : IN STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        indvars_iv26 : IN STD_LOGIC_VECTOR (4 downto 0);
        v217_address0 : OUT STD_LOGIC_VECTOR (2 downto 0);
        v217_ce0 : OUT STD_LOGIC;
        v217_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
        local_A_0_address0 : OUT STD_LOGIC_VECTOR (2 downto 0);
        local_A_0_ce0 : OUT STD_LOGIC;
        local_A_0_we0 : OUT STD_LOGIC;
        local_A_0_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        indvars_iv26_c_din : OUT STD_LOGIC_VECTOR (4 downto 0);
        indvars_iv26_c_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
        indvars_iv26_c_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
        indvars_iv26_c_full_n : IN STD_LOGIC;
        indvars_iv26_c_write : OUT STD_LOGIC );
    end component;


    component systolic_modulate_dataflow_in_loop_l_ni_1_Loop_l_load_B_tile_bk_proc IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_continue : IN STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        local_B_address0 : OUT STD_LOGIC_VECTOR (2 downto 0);
        local_B_ce0 : OUT STD_LOGIC;
        local_B_we0 : OUT STD_LOGIC;
        local_B_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        local_B_1_address0 : OUT STD_LOGIC_VECTOR (2 downto 0);
        local_B_1_ce0 : OUT STD_LOGIC;
        local_B_1_we0 : OUT STD_LOGIC;
        local_B_1_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        local_B_2_address0 : OUT STD_LOGIC_VECTOR (2 downto 0);
        local_B_2_ce0 : OUT STD_LOGIC;
        local_B_2_we0 : OUT STD_LOGIC;
        local_B_2_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        local_B_3_address0 : OUT STD_LOGIC_VECTOR (2 downto 0);
        local_B_3_ce0 : OUT STD_LOGIC;
        local_B_3_we0 : OUT STD_LOGIC;
        local_B_3_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        local_B_3_19_address0 : OUT STD_LOGIC_VECTOR (2 downto 0);
        local_B_3_19_ce0 : OUT STD_LOGIC;
        local_B_3_19_we0 : OUT STD_LOGIC;
        local_B_3_19_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        local_B_2_18_address0 : OUT STD_LOGIC_VECTOR (2 downto 0);
        local_B_2_18_ce0 : OUT STD_LOGIC;
        local_B_2_18_we0 : OUT STD_LOGIC;
        local_B_2_18_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        local_B_1_17_address0 : OUT STD_LOGIC_VECTOR (2 downto 0);
        local_B_1_17_ce0 : OUT STD_LOGIC;
        local_B_1_17_we0 : OUT STD_LOGIC;
        local_B_1_17_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        local_B_4_address0 : OUT STD_LOGIC_VECTOR (2 downto 0);
        local_B_4_ce0 : OUT STD_LOGIC;
        local_B_4_we0 : OUT STD_LOGIC;
        local_B_4_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        indvars_iv26 : IN STD_LOGIC_VECTOR (4 downto 0);
        v218_address0 : OUT STD_LOGIC_VECTOR (10 downto 0);
        v218_ce0 : OUT STD_LOGIC;
        v218_q0 : IN STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component systolic_modulate_systolic_tile_modulate IS
    port (
        v168_0_address0 : OUT STD_LOGIC_VECTOR (2 downto 0);
        v168_0_ce0 : OUT STD_LOGIC;
        v168_0_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        v168_0_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
        v168_0_we0 : OUT STD_LOGIC;
        v168_0_address1 : OUT STD_LOGIC_VECTOR (2 downto 0);
        v168_0_ce1 : OUT STD_LOGIC;
        v168_0_d1 : OUT STD_LOGIC_VECTOR (31 downto 0);
        v168_0_q1 : IN STD_LOGIC_VECTOR (31 downto 0);
        v168_0_we1 : OUT STD_LOGIC;
        v169_0_address0 : OUT STD_LOGIC_VECTOR (2 downto 0);
        v169_0_ce0 : OUT STD_LOGIC;
        v169_0_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        v169_0_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
        v169_0_we0 : OUT STD_LOGIC;
        v169_0_address1 : OUT STD_LOGIC_VECTOR (2 downto 0);
        v169_0_ce1 : OUT STD_LOGIC;
        v169_0_d1 : OUT STD_LOGIC_VECTOR (31 downto 0);
        v169_0_q1 : IN STD_LOGIC_VECTOR (31 downto 0);
        v169_0_we1 : OUT STD_LOGIC;
        v169_1_address0 : OUT STD_LOGIC_VECTOR (2 downto 0);
        v169_1_ce0 : OUT STD_LOGIC;
        v169_1_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        v169_1_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
        v169_1_we0 : OUT STD_LOGIC;
        v169_1_address1 : OUT STD_LOGIC_VECTOR (2 downto 0);
        v169_1_ce1 : OUT STD_LOGIC;
        v169_1_d1 : OUT STD_LOGIC_VECTOR (31 downto 0);
        v169_1_q1 : IN STD_LOGIC_VECTOR (31 downto 0);
        v169_1_we1 : OUT STD_LOGIC;
        v169_2_address0 : OUT STD_LOGIC_VECTOR (2 downto 0);
        v169_2_ce0 : OUT STD_LOGIC;
        v169_2_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        v169_2_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
        v169_2_we0 : OUT STD_LOGIC;
        v169_2_address1 : OUT STD_LOGIC_VECTOR (2 downto 0);
        v169_2_ce1 : OUT STD_LOGIC;
        v169_2_d1 : OUT STD_LOGIC_VECTOR (31 downto 0);
        v169_2_q1 : IN STD_LOGIC_VECTOR (31 downto 0);
        v169_2_we1 : OUT STD_LOGIC;
        v169_3_address0 : OUT STD_LOGIC_VECTOR (2 downto 0);
        v169_3_ce0 : OUT STD_LOGIC;
        v169_3_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        v169_3_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
        v169_3_we0 : OUT STD_LOGIC;
        v169_3_address1 : OUT STD_LOGIC_VECTOR (2 downto 0);
        v169_3_ce1 : OUT STD_LOGIC;
        v169_3_d1 : OUT STD_LOGIC_VECTOR (31 downto 0);
        v169_3_q1 : IN STD_LOGIC_VECTOR (31 downto 0);
        v169_3_we1 : OUT STD_LOGIC;
        v169_4_address0 : OUT STD_LOGIC_VECTOR (2 downto 0);
        v169_4_ce0 : OUT STD_LOGIC;
        v169_4_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        v169_4_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
        v169_4_we0 : OUT STD_LOGIC;
        v169_4_address1 : OUT STD_LOGIC_VECTOR (2 downto 0);
        v169_4_ce1 : OUT STD_LOGIC;
        v169_4_d1 : OUT STD_LOGIC_VECTOR (31 downto 0);
        v169_4_q1 : IN STD_LOGIC_VECTOR (31 downto 0);
        v169_4_we1 : OUT STD_LOGIC;
        v169_5_address0 : OUT STD_LOGIC_VECTOR (2 downto 0);
        v169_5_ce0 : OUT STD_LOGIC;
        v169_5_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        v169_5_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
        v169_5_we0 : OUT STD_LOGIC;
        v169_5_address1 : OUT STD_LOGIC_VECTOR (2 downto 0);
        v169_5_ce1 : OUT STD_LOGIC;
        v169_5_d1 : OUT STD_LOGIC_VECTOR (31 downto 0);
        v169_5_q1 : IN STD_LOGIC_VECTOR (31 downto 0);
        v169_5_we1 : OUT STD_LOGIC;
        v169_6_address0 : OUT STD_LOGIC_VECTOR (2 downto 0);
        v169_6_ce0 : OUT STD_LOGIC;
        v169_6_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        v169_6_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
        v169_6_we0 : OUT STD_LOGIC;
        v169_6_address1 : OUT STD_LOGIC_VECTOR (2 downto 0);
        v169_6_ce1 : OUT STD_LOGIC;
        v169_6_d1 : OUT STD_LOGIC_VECTOR (31 downto 0);
        v169_6_q1 : IN STD_LOGIC_VECTOR (31 downto 0);
        v169_6_we1 : OUT STD_LOGIC;
        v169_7_address0 : OUT STD_LOGIC_VECTOR (2 downto 0);
        v169_7_ce0 : OUT STD_LOGIC;
        v169_7_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        v169_7_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
        v169_7_we0 : OUT STD_LOGIC;
        v169_7_address1 : OUT STD_LOGIC_VECTOR (2 downto 0);
        v169_7_ce1 : OUT STD_LOGIC;
        v169_7_d1 : OUT STD_LOGIC_VECTOR (31 downto 0);
        v169_7_q1 : IN STD_LOGIC_VECTOR (31 downto 0);
        v169_7_we1 : OUT STD_LOGIC;
        v170_0_0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        v170_1_0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        v170_2_0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        v170_3_0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        v170_4_0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        v170_5_0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        v170_6_0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        v170_7_0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        v168_0_empty_n : IN STD_LOGIC;
        v168_0_read : OUT STD_LOGIC;
        v169_0_empty_n : IN STD_LOGIC;
        v169_0_read : OUT STD_LOGIC;
        v169_1_empty_n : IN STD_LOGIC;
        v169_1_read : OUT STD_LOGIC;
        v169_2_empty_n : IN STD_LOGIC;
        v169_2_read : OUT STD_LOGIC;
        v169_3_empty_n : IN STD_LOGIC;
        v169_3_read : OUT STD_LOGIC;
        v169_4_empty_n : IN STD_LOGIC;
        v169_4_read : OUT STD_LOGIC;
        v169_5_empty_n : IN STD_LOGIC;
        v169_5_read : OUT STD_LOGIC;
        v169_6_empty_n : IN STD_LOGIC;
        v169_6_read : OUT STD_LOGIC;
        v169_7_empty_n : IN STD_LOGIC;
        v169_7_read : OUT STD_LOGIC;
        ap_start : IN STD_LOGIC;
        v170_0_0_ap_vld : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        v170_1_0_ap_vld : OUT STD_LOGIC;
        v170_2_0_ap_vld : OUT STD_LOGIC;
        v170_3_0_ap_vld : OUT STD_LOGIC;
        v170_4_0_ap_vld : OUT STD_LOGIC;
        v170_5_0_ap_vld : OUT STD_LOGIC;
        v170_6_0_ap_vld : OUT STD_LOGIC;
        v170_7_0_ap_vld : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_continue : IN STD_LOGIC );
    end component;


    component systolic_modulate_dataflow_in_loop_l_ni_1_Loop_l_store_C_tile_sj_proc IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_continue : IN STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        local_C_0_7 : IN STD_LOGIC_VECTOR (31 downto 0);
        local_C_0_6 : IN STD_LOGIC_VECTOR (31 downto 0);
        local_C_0_5 : IN STD_LOGIC_VECTOR (31 downto 0);
        local_C_0_4 : IN STD_LOGIC_VECTOR (31 downto 0);
        local_C_0_3 : IN STD_LOGIC_VECTOR (31 downto 0);
        local_C_0_2 : IN STD_LOGIC_VECTOR (31 downto 0);
        local_C_0_1 : IN STD_LOGIC_VECTOR (31 downto 0);
        local_C_0 : IN STD_LOGIC_VECTOR (31 downto 0);
        indvars_iv26_dout : IN STD_LOGIC_VECTOR (4 downto 0);
        indvars_iv26_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
        indvars_iv26_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
        indvars_iv26_empty_n : IN STD_LOGIC;
        indvars_iv26_read : OUT STD_LOGIC;
        v219_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
        v219_ce0 : OUT STD_LOGIC;
        v219_we0 : OUT STD_LOGIC;
        v219_d0 : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component systolic_modulate_dataflow_in_loop_l_ni_1_local_B_RAM_AUTO_1R1W IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        i_address0 : IN STD_LOGIC_VECTOR (2 downto 0);
        i_ce0 : IN STD_LOGIC;
        i_we0 : IN STD_LOGIC;
        i_d0 : IN STD_LOGIC_VECTOR (31 downto 0);
        i_q0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        t_address0 : IN STD_LOGIC_VECTOR (2 downto 0);
        t_ce0 : IN STD_LOGIC;
        t_we0 : IN STD_LOGIC;
        t_d0 : IN STD_LOGIC_VECTOR (31 downto 0);
        t_q0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        i_ce : IN STD_LOGIC;
        t_ce : IN STD_LOGIC;
        i_full_n : OUT STD_LOGIC;
        i_write : IN STD_LOGIC;
        t_empty_n : OUT STD_LOGIC;
        t_read : IN STD_LOGIC );
    end component;


    component systolic_modulate_fifo_w5_d3_S IS
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        if_read_ce : IN STD_LOGIC;
        if_write_ce : IN STD_LOGIC;
        if_din : IN STD_LOGIC_VECTOR (4 downto 0);
        if_full_n : OUT STD_LOGIC;
        if_write : IN STD_LOGIC;
        if_dout : OUT STD_LOGIC_VECTOR (4 downto 0);
        if_num_data_valid : OUT STD_LOGIC_VECTOR (2 downto 0);
        if_fifo_cap : OUT STD_LOGIC_VECTOR (2 downto 0);
        if_empty_n : OUT STD_LOGIC;
        if_read : IN STD_LOGIC );
    end component;


    component systolic_modulate_fifo_w32_d2_S_x IS
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        if_read_ce : IN STD_LOGIC;
        if_write_ce : IN STD_LOGIC;
        if_din : IN STD_LOGIC_VECTOR (31 downto 0);
        if_full_n : OUT STD_LOGIC;
        if_write : IN STD_LOGIC;
        if_dout : OUT STD_LOGIC_VECTOR (31 downto 0);
        if_num_data_valid : OUT STD_LOGIC_VECTOR (2 downto 0);
        if_fifo_cap : OUT STD_LOGIC_VECTOR (2 downto 0);
        if_empty_n : OUT STD_LOGIC;
        if_read : IN STD_LOGIC );
    end component;



begin
    local_B_U : component systolic_modulate_dataflow_in_loop_l_ni_1_local_B_RAM_AUTO_1R1W
    generic map (
        DataWidth => 32,
        AddressRange => 8,
        AddressWidth => 3)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        i_address0 => dataflow_in_loop_l_ni_1_Loop_l_load_B_tile_bk_proc_U0_local_B_address0,
        i_ce0 => dataflow_in_loop_l_ni_1_Loop_l_load_B_tile_bk_proc_U0_local_B_ce0,
        i_we0 => dataflow_in_loop_l_ni_1_Loop_l_load_B_tile_bk_proc_U0_local_B_we0,
        i_d0 => dataflow_in_loop_l_ni_1_Loop_l_load_B_tile_bk_proc_U0_local_B_d0,
        i_q0 => local_B_i_q0,
        t_address0 => systolic_tile_modulate_U0_v169_7_address0,
        t_ce0 => systolic_tile_modulate_U0_v169_7_ce0,
        t_we0 => ap_const_logic_0,
        t_d0 => ap_const_lv32_0,
        t_q0 => local_B_t_q0,
        i_ce => ap_const_logic_1,
        t_ce => ap_const_logic_1,
        i_full_n => local_B_i_full_n,
        i_write => ap_channel_done_local_B,
        t_empty_n => local_B_t_empty_n,
        t_read => systolic_tile_modulate_U0_ap_ready);

    local_B_1_49_U : component systolic_modulate_dataflow_in_loop_l_ni_1_local_B_RAM_AUTO_1R1W
    generic map (
        DataWidth => 32,
        AddressRange => 8,
        AddressWidth => 3)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        i_address0 => dataflow_in_loop_l_ni_1_Loop_l_load_B_tile_bk_proc_U0_local_B_1_address0,
        i_ce0 => dataflow_in_loop_l_ni_1_Loop_l_load_B_tile_bk_proc_U0_local_B_1_ce0,
        i_we0 => dataflow_in_loop_l_ni_1_Loop_l_load_B_tile_bk_proc_U0_local_B_1_we0,
        i_d0 => dataflow_in_loop_l_ni_1_Loop_l_load_B_tile_bk_proc_U0_local_B_1_d0,
        i_q0 => local_B_1_49_i_q0,
        t_address0 => systolic_tile_modulate_U0_v169_6_address0,
        t_ce0 => systolic_tile_modulate_U0_v169_6_ce0,
        t_we0 => ap_const_logic_0,
        t_d0 => ap_const_lv32_0,
        t_q0 => local_B_1_49_t_q0,
        i_ce => ap_const_logic_1,
        t_ce => ap_const_logic_1,
        i_full_n => local_B_1_49_i_full_n,
        i_write => ap_channel_done_local_B_1_49,
        t_empty_n => local_B_1_49_t_empty_n,
        t_read => systolic_tile_modulate_U0_ap_ready);

    local_B_2_50_U : component systolic_modulate_dataflow_in_loop_l_ni_1_local_B_RAM_AUTO_1R1W
    generic map (
        DataWidth => 32,
        AddressRange => 8,
        AddressWidth => 3)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        i_address0 => dataflow_in_loop_l_ni_1_Loop_l_load_B_tile_bk_proc_U0_local_B_2_address0,
        i_ce0 => dataflow_in_loop_l_ni_1_Loop_l_load_B_tile_bk_proc_U0_local_B_2_ce0,
        i_we0 => dataflow_in_loop_l_ni_1_Loop_l_load_B_tile_bk_proc_U0_local_B_2_we0,
        i_d0 => dataflow_in_loop_l_ni_1_Loop_l_load_B_tile_bk_proc_U0_local_B_2_d0,
        i_q0 => local_B_2_50_i_q0,
        t_address0 => systolic_tile_modulate_U0_v169_5_address0,
        t_ce0 => systolic_tile_modulate_U0_v169_5_ce0,
        t_we0 => ap_const_logic_0,
        t_d0 => ap_const_lv32_0,
        t_q0 => local_B_2_50_t_q0,
        i_ce => ap_const_logic_1,
        t_ce => ap_const_logic_1,
        i_full_n => local_B_2_50_i_full_n,
        i_write => ap_channel_done_local_B_2_50,
        t_empty_n => local_B_2_50_t_empty_n,
        t_read => systolic_tile_modulate_U0_ap_ready);

    local_B_3_51_U : component systolic_modulate_dataflow_in_loop_l_ni_1_local_B_RAM_AUTO_1R1W
    generic map (
        DataWidth => 32,
        AddressRange => 8,
        AddressWidth => 3)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        i_address0 => dataflow_in_loop_l_ni_1_Loop_l_load_B_tile_bk_proc_U0_local_B_3_address0,
        i_ce0 => dataflow_in_loop_l_ni_1_Loop_l_load_B_tile_bk_proc_U0_local_B_3_ce0,
        i_we0 => dataflow_in_loop_l_ni_1_Loop_l_load_B_tile_bk_proc_U0_local_B_3_we0,
        i_d0 => dataflow_in_loop_l_ni_1_Loop_l_load_B_tile_bk_proc_U0_local_B_3_d0,
        i_q0 => local_B_3_51_i_q0,
        t_address0 => systolic_tile_modulate_U0_v169_4_address0,
        t_ce0 => systolic_tile_modulate_U0_v169_4_ce0,
        t_we0 => ap_const_logic_0,
        t_d0 => ap_const_lv32_0,
        t_q0 => local_B_3_51_t_q0,
        i_ce => ap_const_logic_1,
        t_ce => ap_const_logic_1,
        i_full_n => local_B_3_51_i_full_n,
        i_write => ap_channel_done_local_B_3_51,
        t_empty_n => local_B_3_51_t_empty_n,
        t_read => systolic_tile_modulate_U0_ap_ready);

    local_B_3_U : component systolic_modulate_dataflow_in_loop_l_ni_1_local_B_RAM_AUTO_1R1W
    generic map (
        DataWidth => 32,
        AddressRange => 8,
        AddressWidth => 3)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        i_address0 => dataflow_in_loop_l_ni_1_Loop_l_load_B_tile_bk_proc_U0_local_B_3_19_address0,
        i_ce0 => dataflow_in_loop_l_ni_1_Loop_l_load_B_tile_bk_proc_U0_local_B_3_19_ce0,
        i_we0 => dataflow_in_loop_l_ni_1_Loop_l_load_B_tile_bk_proc_U0_local_B_3_19_we0,
        i_d0 => dataflow_in_loop_l_ni_1_Loop_l_load_B_tile_bk_proc_U0_local_B_3_19_d0,
        i_q0 => local_B_3_i_q0,
        t_address0 => systolic_tile_modulate_U0_v169_3_address0,
        t_ce0 => systolic_tile_modulate_U0_v169_3_ce0,
        t_we0 => ap_const_logic_0,
        t_d0 => ap_const_lv32_0,
        t_q0 => local_B_3_t_q0,
        i_ce => ap_const_logic_1,
        t_ce => ap_const_logic_1,
        i_full_n => local_B_3_i_full_n,
        i_write => ap_channel_done_local_B_3,
        t_empty_n => local_B_3_t_empty_n,
        t_read => systolic_tile_modulate_U0_ap_ready);

    local_B_2_U : component systolic_modulate_dataflow_in_loop_l_ni_1_local_B_RAM_AUTO_1R1W
    generic map (
        DataWidth => 32,
        AddressRange => 8,
        AddressWidth => 3)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        i_address0 => dataflow_in_loop_l_ni_1_Loop_l_load_B_tile_bk_proc_U0_local_B_2_18_address0,
        i_ce0 => dataflow_in_loop_l_ni_1_Loop_l_load_B_tile_bk_proc_U0_local_B_2_18_ce0,
        i_we0 => dataflow_in_loop_l_ni_1_Loop_l_load_B_tile_bk_proc_U0_local_B_2_18_we0,
        i_d0 => dataflow_in_loop_l_ni_1_Loop_l_load_B_tile_bk_proc_U0_local_B_2_18_d0,
        i_q0 => local_B_2_i_q0,
        t_address0 => systolic_tile_modulate_U0_v169_2_address0,
        t_ce0 => systolic_tile_modulate_U0_v169_2_ce0,
        t_we0 => ap_const_logic_0,
        t_d0 => ap_const_lv32_0,
        t_q0 => local_B_2_t_q0,
        i_ce => ap_const_logic_1,
        t_ce => ap_const_logic_1,
        i_full_n => local_B_2_i_full_n,
        i_write => ap_channel_done_local_B_2,
        t_empty_n => local_B_2_t_empty_n,
        t_read => systolic_tile_modulate_U0_ap_ready);

    local_B_1_U : component systolic_modulate_dataflow_in_loop_l_ni_1_local_B_RAM_AUTO_1R1W
    generic map (
        DataWidth => 32,
        AddressRange => 8,
        AddressWidth => 3)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        i_address0 => dataflow_in_loop_l_ni_1_Loop_l_load_B_tile_bk_proc_U0_local_B_1_17_address0,
        i_ce0 => dataflow_in_loop_l_ni_1_Loop_l_load_B_tile_bk_proc_U0_local_B_1_17_ce0,
        i_we0 => dataflow_in_loop_l_ni_1_Loop_l_load_B_tile_bk_proc_U0_local_B_1_17_we0,
        i_d0 => dataflow_in_loop_l_ni_1_Loop_l_load_B_tile_bk_proc_U0_local_B_1_17_d0,
        i_q0 => local_B_1_i_q0,
        t_address0 => systolic_tile_modulate_U0_v169_1_address0,
        t_ce0 => systolic_tile_modulate_U0_v169_1_ce0,
        t_we0 => ap_const_logic_0,
        t_d0 => ap_const_lv32_0,
        t_q0 => local_B_1_t_q0,
        i_ce => ap_const_logic_1,
        t_ce => ap_const_logic_1,
        i_full_n => local_B_1_i_full_n,
        i_write => ap_channel_done_local_B_1,
        t_empty_n => local_B_1_t_empty_n,
        t_read => systolic_tile_modulate_U0_ap_ready);

    local_B_4_U : component systolic_modulate_dataflow_in_loop_l_ni_1_local_B_RAM_AUTO_1R1W
    generic map (
        DataWidth => 32,
        AddressRange => 8,
        AddressWidth => 3)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        i_address0 => dataflow_in_loop_l_ni_1_Loop_l_load_B_tile_bk_proc_U0_local_B_4_address0,
        i_ce0 => dataflow_in_loop_l_ni_1_Loop_l_load_B_tile_bk_proc_U0_local_B_4_ce0,
        i_we0 => dataflow_in_loop_l_ni_1_Loop_l_load_B_tile_bk_proc_U0_local_B_4_we0,
        i_d0 => dataflow_in_loop_l_ni_1_Loop_l_load_B_tile_bk_proc_U0_local_B_4_d0,
        i_q0 => local_B_4_i_q0,
        t_address0 => systolic_tile_modulate_U0_v169_0_address0,
        t_ce0 => systolic_tile_modulate_U0_v169_0_ce0,
        t_we0 => ap_const_logic_0,
        t_d0 => ap_const_lv32_0,
        t_q0 => local_B_4_t_q0,
        i_ce => ap_const_logic_1,
        t_ce => ap_const_logic_1,
        i_full_n => local_B_4_i_full_n,
        i_write => ap_channel_done_local_B_4,
        t_empty_n => local_B_4_t_empty_n,
        t_read => systolic_tile_modulate_U0_ap_ready);

    local_A_0_U : component systolic_modulate_dataflow_in_loop_l_ni_1_local_B_RAM_AUTO_1R1W
    generic map (
        DataWidth => 32,
        AddressRange => 8,
        AddressWidth => 3)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        i_address0 => dataflow_in_loop_l_ni_1_Loop_l_load_A_tile_ak_proc_U0_local_A_0_address0,
        i_ce0 => dataflow_in_loop_l_ni_1_Loop_l_load_A_tile_ak_proc_U0_local_A_0_ce0,
        i_we0 => dataflow_in_loop_l_ni_1_Loop_l_load_A_tile_ak_proc_U0_local_A_0_we0,
        i_d0 => dataflow_in_loop_l_ni_1_Loop_l_load_A_tile_ak_proc_U0_local_A_0_d0,
        i_q0 => local_A_0_i_q0,
        t_address0 => systolic_tile_modulate_U0_v168_0_address0,
        t_ce0 => systolic_tile_modulate_U0_v168_0_ce0,
        t_we0 => ap_const_logic_0,
        t_d0 => ap_const_lv32_0,
        t_q0 => local_A_0_t_q0,
        i_ce => ap_const_logic_1,
        t_ce => ap_const_logic_1,
        i_full_n => local_A_0_i_full_n,
        i_write => dataflow_in_loop_l_ni_1_Loop_l_load_A_tile_ak_proc_U0_ap_done,
        t_empty_n => local_A_0_t_empty_n,
        t_read => systolic_tile_modulate_U0_ap_ready);

    dataflow_in_loop_l_ni_1_Loop_l_load_A_tile_ak_proc_U0 : component systolic_modulate_dataflow_in_loop_l_ni_1_Loop_l_load_A_tile_ak_proc
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => dataflow_in_loop_l_ni_1_Loop_l_load_A_tile_ak_proc_U0_ap_start,
        ap_done => dataflow_in_loop_l_ni_1_Loop_l_load_A_tile_ak_proc_U0_ap_done,
        ap_continue => dataflow_in_loop_l_ni_1_Loop_l_load_A_tile_ak_proc_U0_ap_continue,
        ap_idle => dataflow_in_loop_l_ni_1_Loop_l_load_A_tile_ak_proc_U0_ap_idle,
        ap_ready => dataflow_in_loop_l_ni_1_Loop_l_load_A_tile_ak_proc_U0_ap_ready,
        indvars_iv26 => indvars_iv26,
        v217_address0 => dataflow_in_loop_l_ni_1_Loop_l_load_A_tile_ak_proc_U0_v217_address0,
        v217_ce0 => dataflow_in_loop_l_ni_1_Loop_l_load_A_tile_ak_proc_U0_v217_ce0,
        v217_q0 => v217_q0,
        local_A_0_address0 => dataflow_in_loop_l_ni_1_Loop_l_load_A_tile_ak_proc_U0_local_A_0_address0,
        local_A_0_ce0 => dataflow_in_loop_l_ni_1_Loop_l_load_A_tile_ak_proc_U0_local_A_0_ce0,
        local_A_0_we0 => dataflow_in_loop_l_ni_1_Loop_l_load_A_tile_ak_proc_U0_local_A_0_we0,
        local_A_0_d0 => dataflow_in_loop_l_ni_1_Loop_l_load_A_tile_ak_proc_U0_local_A_0_d0,
        indvars_iv26_c_din => dataflow_in_loop_l_ni_1_Loop_l_load_A_tile_ak_proc_U0_indvars_iv26_c_din,
        indvars_iv26_c_num_data_valid => indvars_iv26_c_num_data_valid,
        indvars_iv26_c_fifo_cap => indvars_iv26_c_fifo_cap,
        indvars_iv26_c_full_n => indvars_iv26_c_full_n,
        indvars_iv26_c_write => dataflow_in_loop_l_ni_1_Loop_l_load_A_tile_ak_proc_U0_indvars_iv26_c_write);

    dataflow_in_loop_l_ni_1_Loop_l_load_B_tile_bk_proc_U0 : component systolic_modulate_dataflow_in_loop_l_ni_1_Loop_l_load_B_tile_bk_proc
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => dataflow_in_loop_l_ni_1_Loop_l_load_B_tile_bk_proc_U0_ap_start,
        ap_done => dataflow_in_loop_l_ni_1_Loop_l_load_B_tile_bk_proc_U0_ap_done,
        ap_continue => dataflow_in_loop_l_ni_1_Loop_l_load_B_tile_bk_proc_U0_ap_continue,
        ap_idle => dataflow_in_loop_l_ni_1_Loop_l_load_B_tile_bk_proc_U0_ap_idle,
        ap_ready => dataflow_in_loop_l_ni_1_Loop_l_load_B_tile_bk_proc_U0_ap_ready,
        local_B_address0 => dataflow_in_loop_l_ni_1_Loop_l_load_B_tile_bk_proc_U0_local_B_address0,
        local_B_ce0 => dataflow_in_loop_l_ni_1_Loop_l_load_B_tile_bk_proc_U0_local_B_ce0,
        local_B_we0 => dataflow_in_loop_l_ni_1_Loop_l_load_B_tile_bk_proc_U0_local_B_we0,
        local_B_d0 => dataflow_in_loop_l_ni_1_Loop_l_load_B_tile_bk_proc_U0_local_B_d0,
        local_B_1_address0 => dataflow_in_loop_l_ni_1_Loop_l_load_B_tile_bk_proc_U0_local_B_1_address0,
        local_B_1_ce0 => dataflow_in_loop_l_ni_1_Loop_l_load_B_tile_bk_proc_U0_local_B_1_ce0,
        local_B_1_we0 => dataflow_in_loop_l_ni_1_Loop_l_load_B_tile_bk_proc_U0_local_B_1_we0,
        local_B_1_d0 => dataflow_in_loop_l_ni_1_Loop_l_load_B_tile_bk_proc_U0_local_B_1_d0,
        local_B_2_address0 => dataflow_in_loop_l_ni_1_Loop_l_load_B_tile_bk_proc_U0_local_B_2_address0,
        local_B_2_ce0 => dataflow_in_loop_l_ni_1_Loop_l_load_B_tile_bk_proc_U0_local_B_2_ce0,
        local_B_2_we0 => dataflow_in_loop_l_ni_1_Loop_l_load_B_tile_bk_proc_U0_local_B_2_we0,
        local_B_2_d0 => dataflow_in_loop_l_ni_1_Loop_l_load_B_tile_bk_proc_U0_local_B_2_d0,
        local_B_3_address0 => dataflow_in_loop_l_ni_1_Loop_l_load_B_tile_bk_proc_U0_local_B_3_address0,
        local_B_3_ce0 => dataflow_in_loop_l_ni_1_Loop_l_load_B_tile_bk_proc_U0_local_B_3_ce0,
        local_B_3_we0 => dataflow_in_loop_l_ni_1_Loop_l_load_B_tile_bk_proc_U0_local_B_3_we0,
        local_B_3_d0 => dataflow_in_loop_l_ni_1_Loop_l_load_B_tile_bk_proc_U0_local_B_3_d0,
        local_B_3_19_address0 => dataflow_in_loop_l_ni_1_Loop_l_load_B_tile_bk_proc_U0_local_B_3_19_address0,
        local_B_3_19_ce0 => dataflow_in_loop_l_ni_1_Loop_l_load_B_tile_bk_proc_U0_local_B_3_19_ce0,
        local_B_3_19_we0 => dataflow_in_loop_l_ni_1_Loop_l_load_B_tile_bk_proc_U0_local_B_3_19_we0,
        local_B_3_19_d0 => dataflow_in_loop_l_ni_1_Loop_l_load_B_tile_bk_proc_U0_local_B_3_19_d0,
        local_B_2_18_address0 => dataflow_in_loop_l_ni_1_Loop_l_load_B_tile_bk_proc_U0_local_B_2_18_address0,
        local_B_2_18_ce0 => dataflow_in_loop_l_ni_1_Loop_l_load_B_tile_bk_proc_U0_local_B_2_18_ce0,
        local_B_2_18_we0 => dataflow_in_loop_l_ni_1_Loop_l_load_B_tile_bk_proc_U0_local_B_2_18_we0,
        local_B_2_18_d0 => dataflow_in_loop_l_ni_1_Loop_l_load_B_tile_bk_proc_U0_local_B_2_18_d0,
        local_B_1_17_address0 => dataflow_in_loop_l_ni_1_Loop_l_load_B_tile_bk_proc_U0_local_B_1_17_address0,
        local_B_1_17_ce0 => dataflow_in_loop_l_ni_1_Loop_l_load_B_tile_bk_proc_U0_local_B_1_17_ce0,
        local_B_1_17_we0 => dataflow_in_loop_l_ni_1_Loop_l_load_B_tile_bk_proc_U0_local_B_1_17_we0,
        local_B_1_17_d0 => dataflow_in_loop_l_ni_1_Loop_l_load_B_tile_bk_proc_U0_local_B_1_17_d0,
        local_B_4_address0 => dataflow_in_loop_l_ni_1_Loop_l_load_B_tile_bk_proc_U0_local_B_4_address0,
        local_B_4_ce0 => dataflow_in_loop_l_ni_1_Loop_l_load_B_tile_bk_proc_U0_local_B_4_ce0,
        local_B_4_we0 => dataflow_in_loop_l_ni_1_Loop_l_load_B_tile_bk_proc_U0_local_B_4_we0,
        local_B_4_d0 => dataflow_in_loop_l_ni_1_Loop_l_load_B_tile_bk_proc_U0_local_B_4_d0,
        indvars_iv26 => indvars_iv26,
        v218_address0 => dataflow_in_loop_l_ni_1_Loop_l_load_B_tile_bk_proc_U0_v218_address0,
        v218_ce0 => dataflow_in_loop_l_ni_1_Loop_l_load_B_tile_bk_proc_U0_v218_ce0,
        v218_q0 => v218_q0);

    systolic_tile_modulate_U0 : component systolic_modulate_systolic_tile_modulate
    port map (
        v168_0_address0 => systolic_tile_modulate_U0_v168_0_address0,
        v168_0_ce0 => systolic_tile_modulate_U0_v168_0_ce0,
        v168_0_d0 => systolic_tile_modulate_U0_v168_0_d0,
        v168_0_q0 => local_A_0_t_q0,
        v168_0_we0 => systolic_tile_modulate_U0_v168_0_we0,
        v168_0_address1 => systolic_tile_modulate_U0_v168_0_address1,
        v168_0_ce1 => systolic_tile_modulate_U0_v168_0_ce1,
        v168_0_d1 => systolic_tile_modulate_U0_v168_0_d1,
        v168_0_q1 => ap_const_lv32_0,
        v168_0_we1 => systolic_tile_modulate_U0_v168_0_we1,
        v169_0_address0 => systolic_tile_modulate_U0_v169_0_address0,
        v169_0_ce0 => systolic_tile_modulate_U0_v169_0_ce0,
        v169_0_d0 => systolic_tile_modulate_U0_v169_0_d0,
        v169_0_q0 => local_B_4_t_q0,
        v169_0_we0 => systolic_tile_modulate_U0_v169_0_we0,
        v169_0_address1 => systolic_tile_modulate_U0_v169_0_address1,
        v169_0_ce1 => systolic_tile_modulate_U0_v169_0_ce1,
        v169_0_d1 => systolic_tile_modulate_U0_v169_0_d1,
        v169_0_q1 => ap_const_lv32_0,
        v169_0_we1 => systolic_tile_modulate_U0_v169_0_we1,
        v169_1_address0 => systolic_tile_modulate_U0_v169_1_address0,
        v169_1_ce0 => systolic_tile_modulate_U0_v169_1_ce0,
        v169_1_d0 => systolic_tile_modulate_U0_v169_1_d0,
        v169_1_q0 => local_B_1_t_q0,
        v169_1_we0 => systolic_tile_modulate_U0_v169_1_we0,
        v169_1_address1 => systolic_tile_modulate_U0_v169_1_address1,
        v169_1_ce1 => systolic_tile_modulate_U0_v169_1_ce1,
        v169_1_d1 => systolic_tile_modulate_U0_v169_1_d1,
        v169_1_q1 => ap_const_lv32_0,
        v169_1_we1 => systolic_tile_modulate_U0_v169_1_we1,
        v169_2_address0 => systolic_tile_modulate_U0_v169_2_address0,
        v169_2_ce0 => systolic_tile_modulate_U0_v169_2_ce0,
        v169_2_d0 => systolic_tile_modulate_U0_v169_2_d0,
        v169_2_q0 => local_B_2_t_q0,
        v169_2_we0 => systolic_tile_modulate_U0_v169_2_we0,
        v169_2_address1 => systolic_tile_modulate_U0_v169_2_address1,
        v169_2_ce1 => systolic_tile_modulate_U0_v169_2_ce1,
        v169_2_d1 => systolic_tile_modulate_U0_v169_2_d1,
        v169_2_q1 => ap_const_lv32_0,
        v169_2_we1 => systolic_tile_modulate_U0_v169_2_we1,
        v169_3_address0 => systolic_tile_modulate_U0_v169_3_address0,
        v169_3_ce0 => systolic_tile_modulate_U0_v169_3_ce0,
        v169_3_d0 => systolic_tile_modulate_U0_v169_3_d0,
        v169_3_q0 => local_B_3_t_q0,
        v169_3_we0 => systolic_tile_modulate_U0_v169_3_we0,
        v169_3_address1 => systolic_tile_modulate_U0_v169_3_address1,
        v169_3_ce1 => systolic_tile_modulate_U0_v169_3_ce1,
        v169_3_d1 => systolic_tile_modulate_U0_v169_3_d1,
        v169_3_q1 => ap_const_lv32_0,
        v169_3_we1 => systolic_tile_modulate_U0_v169_3_we1,
        v169_4_address0 => systolic_tile_modulate_U0_v169_4_address0,
        v169_4_ce0 => systolic_tile_modulate_U0_v169_4_ce0,
        v169_4_d0 => systolic_tile_modulate_U0_v169_4_d0,
        v169_4_q0 => local_B_3_51_t_q0,
        v169_4_we0 => systolic_tile_modulate_U0_v169_4_we0,
        v169_4_address1 => systolic_tile_modulate_U0_v169_4_address1,
        v169_4_ce1 => systolic_tile_modulate_U0_v169_4_ce1,
        v169_4_d1 => systolic_tile_modulate_U0_v169_4_d1,
        v169_4_q1 => ap_const_lv32_0,
        v169_4_we1 => systolic_tile_modulate_U0_v169_4_we1,
        v169_5_address0 => systolic_tile_modulate_U0_v169_5_address0,
        v169_5_ce0 => systolic_tile_modulate_U0_v169_5_ce0,
        v169_5_d0 => systolic_tile_modulate_U0_v169_5_d0,
        v169_5_q0 => local_B_2_50_t_q0,
        v169_5_we0 => systolic_tile_modulate_U0_v169_5_we0,
        v169_5_address1 => systolic_tile_modulate_U0_v169_5_address1,
        v169_5_ce1 => systolic_tile_modulate_U0_v169_5_ce1,
        v169_5_d1 => systolic_tile_modulate_U0_v169_5_d1,
        v169_5_q1 => ap_const_lv32_0,
        v169_5_we1 => systolic_tile_modulate_U0_v169_5_we1,
        v169_6_address0 => systolic_tile_modulate_U0_v169_6_address0,
        v169_6_ce0 => systolic_tile_modulate_U0_v169_6_ce0,
        v169_6_d0 => systolic_tile_modulate_U0_v169_6_d0,
        v169_6_q0 => local_B_1_49_t_q0,
        v169_6_we0 => systolic_tile_modulate_U0_v169_6_we0,
        v169_6_address1 => systolic_tile_modulate_U0_v169_6_address1,
        v169_6_ce1 => systolic_tile_modulate_U0_v169_6_ce1,
        v169_6_d1 => systolic_tile_modulate_U0_v169_6_d1,
        v169_6_q1 => ap_const_lv32_0,
        v169_6_we1 => systolic_tile_modulate_U0_v169_6_we1,
        v169_7_address0 => systolic_tile_modulate_U0_v169_7_address0,
        v169_7_ce0 => systolic_tile_modulate_U0_v169_7_ce0,
        v169_7_d0 => systolic_tile_modulate_U0_v169_7_d0,
        v169_7_q0 => local_B_t_q0,
        v169_7_we0 => systolic_tile_modulate_U0_v169_7_we0,
        v169_7_address1 => systolic_tile_modulate_U0_v169_7_address1,
        v169_7_ce1 => systolic_tile_modulate_U0_v169_7_ce1,
        v169_7_d1 => systolic_tile_modulate_U0_v169_7_d1,
        v169_7_q1 => ap_const_lv32_0,
        v169_7_we1 => systolic_tile_modulate_U0_v169_7_we1,
        v170_0_0 => systolic_tile_modulate_U0_v170_0_0,
        v170_1_0 => systolic_tile_modulate_U0_v170_1_0,
        v170_2_0 => systolic_tile_modulate_U0_v170_2_0,
        v170_3_0 => systolic_tile_modulate_U0_v170_3_0,
        v170_4_0 => systolic_tile_modulate_U0_v170_4_0,
        v170_5_0 => systolic_tile_modulate_U0_v170_5_0,
        v170_6_0 => systolic_tile_modulate_U0_v170_6_0,
        v170_7_0 => systolic_tile_modulate_U0_v170_7_0,
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        v168_0_empty_n => ap_const_logic_0,
        v168_0_read => systolic_tile_modulate_U0_v168_0_read,
        v169_0_empty_n => ap_const_logic_0,
        v169_0_read => systolic_tile_modulate_U0_v169_0_read,
        v169_1_empty_n => ap_const_logic_0,
        v169_1_read => systolic_tile_modulate_U0_v169_1_read,
        v169_2_empty_n => ap_const_logic_0,
        v169_2_read => systolic_tile_modulate_U0_v169_2_read,
        v169_3_empty_n => ap_const_logic_0,
        v169_3_read => systolic_tile_modulate_U0_v169_3_read,
        v169_4_empty_n => ap_const_logic_0,
        v169_4_read => systolic_tile_modulate_U0_v169_4_read,
        v169_5_empty_n => ap_const_logic_0,
        v169_5_read => systolic_tile_modulate_U0_v169_5_read,
        v169_6_empty_n => ap_const_logic_0,
        v169_6_read => systolic_tile_modulate_U0_v169_6_read,
        v169_7_empty_n => ap_const_logic_0,
        v169_7_read => systolic_tile_modulate_U0_v169_7_read,
        ap_start => systolic_tile_modulate_U0_ap_start,
        v170_0_0_ap_vld => systolic_tile_modulate_U0_v170_0_0_ap_vld,
        ap_done => systolic_tile_modulate_U0_ap_done,
        v170_1_0_ap_vld => systolic_tile_modulate_U0_v170_1_0_ap_vld,
        v170_2_0_ap_vld => systolic_tile_modulate_U0_v170_2_0_ap_vld,
        v170_3_0_ap_vld => systolic_tile_modulate_U0_v170_3_0_ap_vld,
        v170_4_0_ap_vld => systolic_tile_modulate_U0_v170_4_0_ap_vld,
        v170_5_0_ap_vld => systolic_tile_modulate_U0_v170_5_0_ap_vld,
        v170_6_0_ap_vld => systolic_tile_modulate_U0_v170_6_0_ap_vld,
        v170_7_0_ap_vld => systolic_tile_modulate_U0_v170_7_0_ap_vld,
        ap_ready => systolic_tile_modulate_U0_ap_ready,
        ap_idle => systolic_tile_modulate_U0_ap_idle,
        ap_continue => systolic_tile_modulate_U0_ap_continue);

    dataflow_in_loop_l_ni_1_Loop_l_store_C_tile_sj_proc_U0 : component systolic_modulate_dataflow_in_loop_l_ni_1_Loop_l_store_C_tile_sj_proc
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => dataflow_in_loop_l_ni_1_Loop_l_store_C_tile_sj_proc_U0_ap_start,
        ap_done => dataflow_in_loop_l_ni_1_Loop_l_store_C_tile_sj_proc_U0_ap_done,
        ap_continue => dataflow_in_loop_l_ni_1_Loop_l_store_C_tile_sj_proc_U0_ap_continue,
        ap_idle => dataflow_in_loop_l_ni_1_Loop_l_store_C_tile_sj_proc_U0_ap_idle,
        ap_ready => dataflow_in_loop_l_ni_1_Loop_l_store_C_tile_sj_proc_U0_ap_ready,
        local_C_0_7 => local_C_0_7_dout,
        local_C_0_6 => local_C_0_6_dout,
        local_C_0_5 => local_C_0_5_dout,
        local_C_0_4 => local_C_0_4_dout,
        local_C_0_3 => local_C_0_3_dout,
        local_C_0_2 => local_C_0_2_dout,
        local_C_0_1 => local_C_0_1_dout,
        local_C_0 => local_C_0_dout,
        indvars_iv26_dout => indvars_iv26_c_dout,
        indvars_iv26_num_data_valid => indvars_iv26_c_num_data_valid,
        indvars_iv26_fifo_cap => indvars_iv26_c_fifo_cap,
        indvars_iv26_empty_n => indvars_iv26_c_empty_n,
        indvars_iv26_read => dataflow_in_loop_l_ni_1_Loop_l_store_C_tile_sj_proc_U0_indvars_iv26_read,
        v219_address0 => dataflow_in_loop_l_ni_1_Loop_l_store_C_tile_sj_proc_U0_v219_address0,
        v219_ce0 => dataflow_in_loop_l_ni_1_Loop_l_store_C_tile_sj_proc_U0_v219_ce0,
        v219_we0 => dataflow_in_loop_l_ni_1_Loop_l_store_C_tile_sj_proc_U0_v219_we0,
        v219_d0 => dataflow_in_loop_l_ni_1_Loop_l_store_C_tile_sj_proc_U0_v219_d0);

    indvars_iv26_c_U : component systolic_modulate_fifo_w5_d3_S
    port map (
        clk => ap_clk,
        reset => ap_rst,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => dataflow_in_loop_l_ni_1_Loop_l_load_A_tile_ak_proc_U0_indvars_iv26_c_din,
        if_full_n => indvars_iv26_c_full_n,
        if_write => dataflow_in_loop_l_ni_1_Loop_l_load_A_tile_ak_proc_U0_indvars_iv26_c_write,
        if_dout => indvars_iv26_c_dout,
        if_num_data_valid => indvars_iv26_c_num_data_valid,
        if_fifo_cap => indvars_iv26_c_fifo_cap,
        if_empty_n => indvars_iv26_c_empty_n,
        if_read => dataflow_in_loop_l_ni_1_Loop_l_store_C_tile_sj_proc_U0_indvars_iv26_read);

    local_C_0_7_U : component systolic_modulate_fifo_w32_d2_S_x
    port map (
        clk => ap_clk,
        reset => ap_rst,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => systolic_tile_modulate_U0_v170_0_0,
        if_full_n => local_C_0_7_full_n,
        if_write => ap_channel_done_local_C_0_7,
        if_dout => local_C_0_7_dout,
        if_num_data_valid => local_C_0_7_num_data_valid,
        if_fifo_cap => local_C_0_7_fifo_cap,
        if_empty_n => local_C_0_7_empty_n,
        if_read => dataflow_in_loop_l_ni_1_Loop_l_store_C_tile_sj_proc_U0_ap_ready);

    local_C_0_6_U : component systolic_modulate_fifo_w32_d2_S_x
    port map (
        clk => ap_clk,
        reset => ap_rst,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => systolic_tile_modulate_U0_v170_1_0,
        if_full_n => local_C_0_6_full_n,
        if_write => ap_channel_done_local_C_0_6,
        if_dout => local_C_0_6_dout,
        if_num_data_valid => local_C_0_6_num_data_valid,
        if_fifo_cap => local_C_0_6_fifo_cap,
        if_empty_n => local_C_0_6_empty_n,
        if_read => dataflow_in_loop_l_ni_1_Loop_l_store_C_tile_sj_proc_U0_ap_ready);

    local_C_0_5_U : component systolic_modulate_fifo_w32_d2_S_x
    port map (
        clk => ap_clk,
        reset => ap_rst,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => systolic_tile_modulate_U0_v170_2_0,
        if_full_n => local_C_0_5_full_n,
        if_write => ap_channel_done_local_C_0_5,
        if_dout => local_C_0_5_dout,
        if_num_data_valid => local_C_0_5_num_data_valid,
        if_fifo_cap => local_C_0_5_fifo_cap,
        if_empty_n => local_C_0_5_empty_n,
        if_read => dataflow_in_loop_l_ni_1_Loop_l_store_C_tile_sj_proc_U0_ap_ready);

    local_C_0_4_U : component systolic_modulate_fifo_w32_d2_S_x
    port map (
        clk => ap_clk,
        reset => ap_rst,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => systolic_tile_modulate_U0_v170_3_0,
        if_full_n => local_C_0_4_full_n,
        if_write => ap_channel_done_local_C_0_4,
        if_dout => local_C_0_4_dout,
        if_num_data_valid => local_C_0_4_num_data_valid,
        if_fifo_cap => local_C_0_4_fifo_cap,
        if_empty_n => local_C_0_4_empty_n,
        if_read => dataflow_in_loop_l_ni_1_Loop_l_store_C_tile_sj_proc_U0_ap_ready);

    local_C_0_3_U : component systolic_modulate_fifo_w32_d2_S_x
    port map (
        clk => ap_clk,
        reset => ap_rst,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => systolic_tile_modulate_U0_v170_4_0,
        if_full_n => local_C_0_3_full_n,
        if_write => ap_channel_done_local_C_0_3,
        if_dout => local_C_0_3_dout,
        if_num_data_valid => local_C_0_3_num_data_valid,
        if_fifo_cap => local_C_0_3_fifo_cap,
        if_empty_n => local_C_0_3_empty_n,
        if_read => dataflow_in_loop_l_ni_1_Loop_l_store_C_tile_sj_proc_U0_ap_ready);

    local_C_0_2_U : component systolic_modulate_fifo_w32_d2_S_x
    port map (
        clk => ap_clk,
        reset => ap_rst,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => systolic_tile_modulate_U0_v170_5_0,
        if_full_n => local_C_0_2_full_n,
        if_write => ap_channel_done_local_C_0_2,
        if_dout => local_C_0_2_dout,
        if_num_data_valid => local_C_0_2_num_data_valid,
        if_fifo_cap => local_C_0_2_fifo_cap,
        if_empty_n => local_C_0_2_empty_n,
        if_read => dataflow_in_loop_l_ni_1_Loop_l_store_C_tile_sj_proc_U0_ap_ready);

    local_C_0_1_U : component systolic_modulate_fifo_w32_d2_S_x
    port map (
        clk => ap_clk,
        reset => ap_rst,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => systolic_tile_modulate_U0_v170_6_0,
        if_full_n => local_C_0_1_full_n,
        if_write => ap_channel_done_local_C_0_1,
        if_dout => local_C_0_1_dout,
        if_num_data_valid => local_C_0_1_num_data_valid,
        if_fifo_cap => local_C_0_1_fifo_cap,
        if_empty_n => local_C_0_1_empty_n,
        if_read => dataflow_in_loop_l_ni_1_Loop_l_store_C_tile_sj_proc_U0_ap_ready);

    local_C_0_U : component systolic_modulate_fifo_w32_d2_S_x
    port map (
        clk => ap_clk,
        reset => ap_rst,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => systolic_tile_modulate_U0_v170_7_0,
        if_full_n => local_C_0_full_n,
        if_write => ap_channel_done_local_C_0,
        if_dout => local_C_0_dout,
        if_num_data_valid => local_C_0_num_data_valid,
        if_fifo_cap => local_C_0_fifo_cap,
        if_empty_n => local_C_0_empty_n,
        if_read => dataflow_in_loop_l_ni_1_Loop_l_store_C_tile_sj_proc_U0_ap_ready);





    ap_sync_reg_channel_write_local_B_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_sync_reg_channel_write_local_B <= ap_const_logic_0;
            else
                if (((dataflow_in_loop_l_ni_1_Loop_l_load_B_tile_bk_proc_U0_ap_done and dataflow_in_loop_l_ni_1_Loop_l_load_B_tile_bk_proc_U0_ap_continue) = ap_const_logic_1)) then 
                    ap_sync_reg_channel_write_local_B <= ap_const_logic_0;
                else 
                    ap_sync_reg_channel_write_local_B <= ap_sync_channel_write_local_B;
                end if; 
            end if;
        end if;
    end process;


    ap_sync_reg_channel_write_local_B_1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_sync_reg_channel_write_local_B_1 <= ap_const_logic_0;
            else
                if (((dataflow_in_loop_l_ni_1_Loop_l_load_B_tile_bk_proc_U0_ap_done and dataflow_in_loop_l_ni_1_Loop_l_load_B_tile_bk_proc_U0_ap_continue) = ap_const_logic_1)) then 
                    ap_sync_reg_channel_write_local_B_1 <= ap_const_logic_0;
                else 
                    ap_sync_reg_channel_write_local_B_1 <= ap_sync_channel_write_local_B_1;
                end if; 
            end if;
        end if;
    end process;


    ap_sync_reg_channel_write_local_B_1_49_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_sync_reg_channel_write_local_B_1_49 <= ap_const_logic_0;
            else
                if (((dataflow_in_loop_l_ni_1_Loop_l_load_B_tile_bk_proc_U0_ap_done and dataflow_in_loop_l_ni_1_Loop_l_load_B_tile_bk_proc_U0_ap_continue) = ap_const_logic_1)) then 
                    ap_sync_reg_channel_write_local_B_1_49 <= ap_const_logic_0;
                else 
                    ap_sync_reg_channel_write_local_B_1_49 <= ap_sync_channel_write_local_B_1_49;
                end if; 
            end if;
        end if;
    end process;


    ap_sync_reg_channel_write_local_B_2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_sync_reg_channel_write_local_B_2 <= ap_const_logic_0;
            else
                if (((dataflow_in_loop_l_ni_1_Loop_l_load_B_tile_bk_proc_U0_ap_done and dataflow_in_loop_l_ni_1_Loop_l_load_B_tile_bk_proc_U0_ap_continue) = ap_const_logic_1)) then 
                    ap_sync_reg_channel_write_local_B_2 <= ap_const_logic_0;
                else 
                    ap_sync_reg_channel_write_local_B_2 <= ap_sync_channel_write_local_B_2;
                end if; 
            end if;
        end if;
    end process;


    ap_sync_reg_channel_write_local_B_2_50_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_sync_reg_channel_write_local_B_2_50 <= ap_const_logic_0;
            else
                if (((dataflow_in_loop_l_ni_1_Loop_l_load_B_tile_bk_proc_U0_ap_done and dataflow_in_loop_l_ni_1_Loop_l_load_B_tile_bk_proc_U0_ap_continue) = ap_const_logic_1)) then 
                    ap_sync_reg_channel_write_local_B_2_50 <= ap_const_logic_0;
                else 
                    ap_sync_reg_channel_write_local_B_2_50 <= ap_sync_channel_write_local_B_2_50;
                end if; 
            end if;
        end if;
    end process;


    ap_sync_reg_channel_write_local_B_3_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_sync_reg_channel_write_local_B_3 <= ap_const_logic_0;
            else
                if (((dataflow_in_loop_l_ni_1_Loop_l_load_B_tile_bk_proc_U0_ap_done and dataflow_in_loop_l_ni_1_Loop_l_load_B_tile_bk_proc_U0_ap_continue) = ap_const_logic_1)) then 
                    ap_sync_reg_channel_write_local_B_3 <= ap_const_logic_0;
                else 
                    ap_sync_reg_channel_write_local_B_3 <= ap_sync_channel_write_local_B_3;
                end if; 
            end if;
        end if;
    end process;


    ap_sync_reg_channel_write_local_B_3_51_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_sync_reg_channel_write_local_B_3_51 <= ap_const_logic_0;
            else
                if (((dataflow_in_loop_l_ni_1_Loop_l_load_B_tile_bk_proc_U0_ap_done and dataflow_in_loop_l_ni_1_Loop_l_load_B_tile_bk_proc_U0_ap_continue) = ap_const_logic_1)) then 
                    ap_sync_reg_channel_write_local_B_3_51 <= ap_const_logic_0;
                else 
                    ap_sync_reg_channel_write_local_B_3_51 <= ap_sync_channel_write_local_B_3_51;
                end if; 
            end if;
        end if;
    end process;


    ap_sync_reg_channel_write_local_B_4_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_sync_reg_channel_write_local_B_4 <= ap_const_logic_0;
            else
                if (((dataflow_in_loop_l_ni_1_Loop_l_load_B_tile_bk_proc_U0_ap_done and dataflow_in_loop_l_ni_1_Loop_l_load_B_tile_bk_proc_U0_ap_continue) = ap_const_logic_1)) then 
                    ap_sync_reg_channel_write_local_B_4 <= ap_const_logic_0;
                else 
                    ap_sync_reg_channel_write_local_B_4 <= ap_sync_channel_write_local_B_4;
                end if; 
            end if;
        end if;
    end process;


    ap_sync_reg_channel_write_local_C_0_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_sync_reg_channel_write_local_C_0 <= ap_const_logic_0;
            else
                if (((systolic_tile_modulate_U0_ap_done and systolic_tile_modulate_U0_ap_continue) = ap_const_logic_1)) then 
                    ap_sync_reg_channel_write_local_C_0 <= ap_const_logic_0;
                else 
                    ap_sync_reg_channel_write_local_C_0 <= ap_sync_channel_write_local_C_0;
                end if; 
            end if;
        end if;
    end process;


    ap_sync_reg_channel_write_local_C_0_1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_sync_reg_channel_write_local_C_0_1 <= ap_const_logic_0;
            else
                if (((systolic_tile_modulate_U0_ap_done and systolic_tile_modulate_U0_ap_continue) = ap_const_logic_1)) then 
                    ap_sync_reg_channel_write_local_C_0_1 <= ap_const_logic_0;
                else 
                    ap_sync_reg_channel_write_local_C_0_1 <= ap_sync_channel_write_local_C_0_1;
                end if; 
            end if;
        end if;
    end process;


    ap_sync_reg_channel_write_local_C_0_2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_sync_reg_channel_write_local_C_0_2 <= ap_const_logic_0;
            else
                if (((systolic_tile_modulate_U0_ap_done and systolic_tile_modulate_U0_ap_continue) = ap_const_logic_1)) then 
                    ap_sync_reg_channel_write_local_C_0_2 <= ap_const_logic_0;
                else 
                    ap_sync_reg_channel_write_local_C_0_2 <= ap_sync_channel_write_local_C_0_2;
                end if; 
            end if;
        end if;
    end process;


    ap_sync_reg_channel_write_local_C_0_3_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_sync_reg_channel_write_local_C_0_3 <= ap_const_logic_0;
            else
                if (((systolic_tile_modulate_U0_ap_done and systolic_tile_modulate_U0_ap_continue) = ap_const_logic_1)) then 
                    ap_sync_reg_channel_write_local_C_0_3 <= ap_const_logic_0;
                else 
                    ap_sync_reg_channel_write_local_C_0_3 <= ap_sync_channel_write_local_C_0_3;
                end if; 
            end if;
        end if;
    end process;


    ap_sync_reg_channel_write_local_C_0_4_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_sync_reg_channel_write_local_C_0_4 <= ap_const_logic_0;
            else
                if (((systolic_tile_modulate_U0_ap_done and systolic_tile_modulate_U0_ap_continue) = ap_const_logic_1)) then 
                    ap_sync_reg_channel_write_local_C_0_4 <= ap_const_logic_0;
                else 
                    ap_sync_reg_channel_write_local_C_0_4 <= ap_sync_channel_write_local_C_0_4;
                end if; 
            end if;
        end if;
    end process;


    ap_sync_reg_channel_write_local_C_0_5_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_sync_reg_channel_write_local_C_0_5 <= ap_const_logic_0;
            else
                if (((systolic_tile_modulate_U0_ap_done and systolic_tile_modulate_U0_ap_continue) = ap_const_logic_1)) then 
                    ap_sync_reg_channel_write_local_C_0_5 <= ap_const_logic_0;
                else 
                    ap_sync_reg_channel_write_local_C_0_5 <= ap_sync_channel_write_local_C_0_5;
                end if; 
            end if;
        end if;
    end process;


    ap_sync_reg_channel_write_local_C_0_6_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_sync_reg_channel_write_local_C_0_6 <= ap_const_logic_0;
            else
                if (((systolic_tile_modulate_U0_ap_done and systolic_tile_modulate_U0_ap_continue) = ap_const_logic_1)) then 
                    ap_sync_reg_channel_write_local_C_0_6 <= ap_const_logic_0;
                else 
                    ap_sync_reg_channel_write_local_C_0_6 <= ap_sync_channel_write_local_C_0_6;
                end if; 
            end if;
        end if;
    end process;


    ap_sync_reg_channel_write_local_C_0_7_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_sync_reg_channel_write_local_C_0_7 <= ap_const_logic_0;
            else
                if (((systolic_tile_modulate_U0_ap_done and systolic_tile_modulate_U0_ap_continue) = ap_const_logic_1)) then 
                    ap_sync_reg_channel_write_local_C_0_7 <= ap_const_logic_0;
                else 
                    ap_sync_reg_channel_write_local_C_0_7 <= ap_sync_channel_write_local_C_0_7;
                end if; 
            end if;
        end if;
    end process;


    ap_sync_reg_dataflow_in_loop_l_ni_1_Loop_l_load_A_tile_ak_proc_U0_ap_ready_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_sync_reg_dataflow_in_loop_l_ni_1_Loop_l_load_A_tile_ak_proc_U0_ap_ready <= ap_const_logic_0;
            else
                if (((ap_sync_ready and ap_start) = ap_const_logic_1)) then 
                    ap_sync_reg_dataflow_in_loop_l_ni_1_Loop_l_load_A_tile_ak_proc_U0_ap_ready <= ap_const_logic_0;
                else 
                    ap_sync_reg_dataflow_in_loop_l_ni_1_Loop_l_load_A_tile_ak_proc_U0_ap_ready <= ap_sync_dataflow_in_loop_l_ni_1_Loop_l_load_A_tile_ak_proc_U0_ap_ready;
                end if; 
            end if;
        end if;
    end process;


    ap_sync_reg_dataflow_in_loop_l_ni_1_Loop_l_load_B_tile_bk_proc_U0_ap_ready_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_sync_reg_dataflow_in_loop_l_ni_1_Loop_l_load_B_tile_bk_proc_U0_ap_ready <= ap_const_logic_0;
            else
                if (((ap_sync_ready and ap_start) = ap_const_logic_1)) then 
                    ap_sync_reg_dataflow_in_loop_l_ni_1_Loop_l_load_B_tile_bk_proc_U0_ap_ready <= ap_const_logic_0;
                else 
                    ap_sync_reg_dataflow_in_loop_l_ni_1_Loop_l_load_B_tile_bk_proc_U0_ap_ready <= ap_sync_dataflow_in_loop_l_ni_1_Loop_l_load_B_tile_bk_proc_U0_ap_ready;
                end if; 
            end if;
        end if;
    end process;

    ap_channel_done_local_B <= ((ap_sync_reg_channel_write_local_B xor ap_const_logic_1) and dataflow_in_loop_l_ni_1_Loop_l_load_B_tile_bk_proc_U0_ap_done);
    ap_channel_done_local_B_1 <= ((ap_sync_reg_channel_write_local_B_1 xor ap_const_logic_1) and dataflow_in_loop_l_ni_1_Loop_l_load_B_tile_bk_proc_U0_ap_done);
    ap_channel_done_local_B_1_49 <= ((ap_sync_reg_channel_write_local_B_1_49 xor ap_const_logic_1) and dataflow_in_loop_l_ni_1_Loop_l_load_B_tile_bk_proc_U0_ap_done);
    ap_channel_done_local_B_2 <= ((ap_sync_reg_channel_write_local_B_2 xor ap_const_logic_1) and dataflow_in_loop_l_ni_1_Loop_l_load_B_tile_bk_proc_U0_ap_done);
    ap_channel_done_local_B_2_50 <= ((ap_sync_reg_channel_write_local_B_2_50 xor ap_const_logic_1) and dataflow_in_loop_l_ni_1_Loop_l_load_B_tile_bk_proc_U0_ap_done);
    ap_channel_done_local_B_3 <= ((ap_sync_reg_channel_write_local_B_3 xor ap_const_logic_1) and dataflow_in_loop_l_ni_1_Loop_l_load_B_tile_bk_proc_U0_ap_done);
    ap_channel_done_local_B_3_51 <= ((ap_sync_reg_channel_write_local_B_3_51 xor ap_const_logic_1) and dataflow_in_loop_l_ni_1_Loop_l_load_B_tile_bk_proc_U0_ap_done);
    ap_channel_done_local_B_4 <= ((ap_sync_reg_channel_write_local_B_4 xor ap_const_logic_1) and dataflow_in_loop_l_ni_1_Loop_l_load_B_tile_bk_proc_U0_ap_done);
    ap_channel_done_local_C_0 <= (systolic_tile_modulate_U0_ap_done and (ap_sync_reg_channel_write_local_C_0 xor ap_const_logic_1));
    ap_channel_done_local_C_0_1 <= (systolic_tile_modulate_U0_ap_done and (ap_sync_reg_channel_write_local_C_0_1 xor ap_const_logic_1));
    ap_channel_done_local_C_0_2 <= (systolic_tile_modulate_U0_ap_done and (ap_sync_reg_channel_write_local_C_0_2 xor ap_const_logic_1));
    ap_channel_done_local_C_0_3 <= (systolic_tile_modulate_U0_ap_done and (ap_sync_reg_channel_write_local_C_0_3 xor ap_const_logic_1));
    ap_channel_done_local_C_0_4 <= (systolic_tile_modulate_U0_ap_done and (ap_sync_reg_channel_write_local_C_0_4 xor ap_const_logic_1));
    ap_channel_done_local_C_0_5 <= (systolic_tile_modulate_U0_ap_done and (ap_sync_reg_channel_write_local_C_0_5 xor ap_const_logic_1));
    ap_channel_done_local_C_0_6 <= (systolic_tile_modulate_U0_ap_done and (ap_sync_reg_channel_write_local_C_0_6 xor ap_const_logic_1));
    ap_channel_done_local_C_0_7 <= (systolic_tile_modulate_U0_ap_done and (ap_sync_reg_channel_write_local_C_0_7 xor ap_const_logic_1));
    ap_done <= dataflow_in_loop_l_ni_1_Loop_l_store_C_tile_sj_proc_U0_ap_done;
    ap_idle <= (systolic_tile_modulate_U0_ap_idle and (local_C_0_empty_n xor ap_const_logic_1) and (local_C_0_1_empty_n xor ap_const_logic_1) and (local_C_0_2_empty_n xor ap_const_logic_1) and (local_C_0_3_empty_n xor ap_const_logic_1) and (local_C_0_4_empty_n xor ap_const_logic_1) and (local_C_0_5_empty_n xor ap_const_logic_1) and (local_C_0_6_empty_n xor ap_const_logic_1) and (local_C_0_7_empty_n xor ap_const_logic_1) and (local_B_4_t_empty_n xor ap_const_logic_1) and (local_B_1_t_empty_n xor ap_const_logic_1) and (local_B_2_t_empty_n xor ap_const_logic_1) and (local_B_3_t_empty_n xor ap_const_logic_1) and (local_B_3_51_t_empty_n xor ap_const_logic_1) and (local_B_2_50_t_empty_n xor ap_const_logic_1) and (local_B_1_49_t_empty_n xor ap_const_logic_1) and (local_B_t_empty_n xor ap_const_logic_1) and (local_A_0_t_empty_n xor ap_const_logic_1) and dataflow_in_loop_l_ni_1_Loop_l_store_C_tile_sj_proc_U0_ap_idle and dataflow_in_loop_l_ni_1_Loop_l_load_B_tile_bk_proc_U0_ap_idle and dataflow_in_loop_l_ni_1_Loop_l_load_A_tile_ak_proc_U0_ap_idle);
    ap_ready <= ap_sync_ready;
    ap_sync_channel_write_local_B <= ((dataflow_in_loop_l_ni_1_Loop_l_load_B_tile_bk_proc_U0_local_B_full_n and ap_channel_done_local_B) or ap_sync_reg_channel_write_local_B);
    ap_sync_channel_write_local_B_1 <= ((dataflow_in_loop_l_ni_1_Loop_l_load_B_tile_bk_proc_U0_local_B_1_17_full_n and ap_channel_done_local_B_1) or ap_sync_reg_channel_write_local_B_1);
    ap_sync_channel_write_local_B_1_49 <= ((dataflow_in_loop_l_ni_1_Loop_l_load_B_tile_bk_proc_U0_local_B_1_full_n and ap_channel_done_local_B_1_49) or ap_sync_reg_channel_write_local_B_1_49);
    ap_sync_channel_write_local_B_2 <= ((dataflow_in_loop_l_ni_1_Loop_l_load_B_tile_bk_proc_U0_local_B_2_18_full_n and ap_channel_done_local_B_2) or ap_sync_reg_channel_write_local_B_2);
    ap_sync_channel_write_local_B_2_50 <= ((dataflow_in_loop_l_ni_1_Loop_l_load_B_tile_bk_proc_U0_local_B_2_full_n and ap_channel_done_local_B_2_50) or ap_sync_reg_channel_write_local_B_2_50);
    ap_sync_channel_write_local_B_3 <= ((dataflow_in_loop_l_ni_1_Loop_l_load_B_tile_bk_proc_U0_local_B_3_19_full_n and ap_channel_done_local_B_3) or ap_sync_reg_channel_write_local_B_3);
    ap_sync_channel_write_local_B_3_51 <= ((dataflow_in_loop_l_ni_1_Loop_l_load_B_tile_bk_proc_U0_local_B_3_full_n and ap_channel_done_local_B_3_51) or ap_sync_reg_channel_write_local_B_3_51);
    ap_sync_channel_write_local_B_4 <= ((dataflow_in_loop_l_ni_1_Loop_l_load_B_tile_bk_proc_U0_local_B_4_full_n and ap_channel_done_local_B_4) or ap_sync_reg_channel_write_local_B_4);
    ap_sync_channel_write_local_C_0 <= ((local_C_0_full_n and ap_channel_done_local_C_0) or ap_sync_reg_channel_write_local_C_0);
    ap_sync_channel_write_local_C_0_1 <= ((local_C_0_1_full_n and ap_channel_done_local_C_0_1) or ap_sync_reg_channel_write_local_C_0_1);
    ap_sync_channel_write_local_C_0_2 <= ((local_C_0_2_full_n and ap_channel_done_local_C_0_2) or ap_sync_reg_channel_write_local_C_0_2);
    ap_sync_channel_write_local_C_0_3 <= ((local_C_0_3_full_n and ap_channel_done_local_C_0_3) or ap_sync_reg_channel_write_local_C_0_3);
    ap_sync_channel_write_local_C_0_4 <= ((local_C_0_4_full_n and ap_channel_done_local_C_0_4) or ap_sync_reg_channel_write_local_C_0_4);
    ap_sync_channel_write_local_C_0_5 <= ((local_C_0_5_full_n and ap_channel_done_local_C_0_5) or ap_sync_reg_channel_write_local_C_0_5);
    ap_sync_channel_write_local_C_0_6 <= ((local_C_0_6_full_n and ap_channel_done_local_C_0_6) or ap_sync_reg_channel_write_local_C_0_6);
    ap_sync_channel_write_local_C_0_7 <= ((local_C_0_7_full_n and ap_channel_done_local_C_0_7) or ap_sync_reg_channel_write_local_C_0_7);
    ap_sync_dataflow_in_loop_l_ni_1_Loop_l_load_A_tile_ak_proc_U0_ap_ready <= (dataflow_in_loop_l_ni_1_Loop_l_load_A_tile_ak_proc_U0_ap_ready or ap_sync_reg_dataflow_in_loop_l_ni_1_Loop_l_load_A_tile_ak_proc_U0_ap_ready);
    ap_sync_dataflow_in_loop_l_ni_1_Loop_l_load_B_tile_bk_proc_U0_ap_ready <= (dataflow_in_loop_l_ni_1_Loop_l_load_B_tile_bk_proc_U0_ap_ready or ap_sync_reg_dataflow_in_loop_l_ni_1_Loop_l_load_B_tile_bk_proc_U0_ap_ready);
    ap_sync_ready <= (ap_sync_dataflow_in_loop_l_ni_1_Loop_l_load_B_tile_bk_proc_U0_ap_ready and ap_sync_dataflow_in_loop_l_ni_1_Loop_l_load_A_tile_ak_proc_U0_ap_ready);
    dataflow_in_loop_l_ni_1_Loop_l_load_A_tile_ak_proc_U0_ap_continue <= local_A_0_i_full_n;
    dataflow_in_loop_l_ni_1_Loop_l_load_A_tile_ak_proc_U0_ap_start <= ((ap_sync_reg_dataflow_in_loop_l_ni_1_Loop_l_load_A_tile_ak_proc_U0_ap_ready xor ap_const_logic_1) and ap_start);
    dataflow_in_loop_l_ni_1_Loop_l_load_B_tile_bk_proc_U0_ap_continue <= (ap_sync_channel_write_local_B_4 and ap_sync_channel_write_local_B_3_51 and ap_sync_channel_write_local_B_3 and ap_sync_channel_write_local_B_2_50 and ap_sync_channel_write_local_B_2 and ap_sync_channel_write_local_B_1_49 and ap_sync_channel_write_local_B_1 and ap_sync_channel_write_local_B);
    dataflow_in_loop_l_ni_1_Loop_l_load_B_tile_bk_proc_U0_ap_start <= ((ap_sync_reg_dataflow_in_loop_l_ni_1_Loop_l_load_B_tile_bk_proc_U0_ap_ready xor ap_const_logic_1) and ap_start);
    dataflow_in_loop_l_ni_1_Loop_l_load_B_tile_bk_proc_U0_local_B_1_17_full_n <= local_B_1_i_full_n;
    dataflow_in_loop_l_ni_1_Loop_l_load_B_tile_bk_proc_U0_local_B_1_full_n <= local_B_1_49_i_full_n;
    dataflow_in_loop_l_ni_1_Loop_l_load_B_tile_bk_proc_U0_local_B_2_18_full_n <= local_B_2_i_full_n;
    dataflow_in_loop_l_ni_1_Loop_l_load_B_tile_bk_proc_U0_local_B_2_full_n <= local_B_2_50_i_full_n;
    dataflow_in_loop_l_ni_1_Loop_l_load_B_tile_bk_proc_U0_local_B_3_19_full_n <= local_B_3_i_full_n;
    dataflow_in_loop_l_ni_1_Loop_l_load_B_tile_bk_proc_U0_local_B_3_full_n <= local_B_3_51_i_full_n;
    dataflow_in_loop_l_ni_1_Loop_l_load_B_tile_bk_proc_U0_local_B_4_full_n <= local_B_4_i_full_n;
    dataflow_in_loop_l_ni_1_Loop_l_load_B_tile_bk_proc_U0_local_B_full_n <= local_B_i_full_n;
    dataflow_in_loop_l_ni_1_Loop_l_store_C_tile_sj_proc_U0_ap_continue <= ap_continue;
    dataflow_in_loop_l_ni_1_Loop_l_store_C_tile_sj_proc_U0_ap_start <= (local_C_0_empty_n and local_C_0_7_empty_n and local_C_0_6_empty_n and local_C_0_5_empty_n and local_C_0_4_empty_n and local_C_0_3_empty_n and local_C_0_2_empty_n and local_C_0_1_empty_n);
    systolic_tile_modulate_U0_ap_continue <= (ap_sync_channel_write_local_C_0_7 and ap_sync_channel_write_local_C_0_6 and ap_sync_channel_write_local_C_0_5 and ap_sync_channel_write_local_C_0_4 and ap_sync_channel_write_local_C_0_3 and ap_sync_channel_write_local_C_0_2 and ap_sync_channel_write_local_C_0_1 and ap_sync_channel_write_local_C_0);
    systolic_tile_modulate_U0_ap_start <= (local_B_t_empty_n and local_B_4_t_empty_n and local_B_3_t_empty_n and local_B_3_51_t_empty_n and local_B_2_t_empty_n and local_B_2_50_t_empty_n and local_B_1_t_empty_n and local_B_1_49_t_empty_n and local_A_0_t_empty_n);
    v217_address0 <= dataflow_in_loop_l_ni_1_Loop_l_load_A_tile_ak_proc_U0_v217_address0;
    v217_address1 <= ap_const_lv3_0;
    v217_ce0 <= dataflow_in_loop_l_ni_1_Loop_l_load_A_tile_ak_proc_U0_v217_ce0;
    v217_ce1 <= ap_const_logic_0;
    v217_d0 <= ap_const_lv32_0;
    v217_d1 <= ap_const_lv32_0;
    v217_we0 <= ap_const_logic_0;
    v217_we1 <= ap_const_logic_0;
    v218_address0 <= dataflow_in_loop_l_ni_1_Loop_l_load_B_tile_bk_proc_U0_v218_address0;
    v218_address1 <= ap_const_lv11_0;
    v218_ce0 <= dataflow_in_loop_l_ni_1_Loop_l_load_B_tile_bk_proc_U0_v218_ce0;
    v218_ce1 <= ap_const_logic_0;
    v218_d0 <= ap_const_lv32_0;
    v218_d1 <= ap_const_lv32_0;
    v218_we0 <= ap_const_logic_0;
    v218_we1 <= ap_const_logic_0;
    v219_address0 <= dataflow_in_loop_l_ni_1_Loop_l_store_C_tile_sj_proc_U0_v219_address0;
    v219_address1 <= ap_const_lv8_0;
    v219_ce0 <= dataflow_in_loop_l_ni_1_Loop_l_store_C_tile_sj_proc_U0_v219_ce0;
    v219_ce1 <= ap_const_logic_0;
    v219_d0 <= dataflow_in_loop_l_ni_1_Loop_l_store_C_tile_sj_proc_U0_v219_d0;
    v219_d1 <= ap_const_lv32_0;
    v219_we0 <= dataflow_in_loop_l_ni_1_Loop_l_store_C_tile_sj_proc_U0_v219_we0;
    v219_we1 <= ap_const_logic_0;
end behav;
